NDLANO/ndla-frontend

Dockerfile
Changes ```COPY src $APP_PATH/public``` to ```COPY public $APP_PATH/public``` in the dockerfile. The `public` folder is not included with the old version of the `Dockerfile`.
=> Changes copy src to public

src/server/contentSecurityPolicy.js
connects to https://github.com/NDLANO/Issues/issues/1096
https://test.api.ndla.no/article-api/v2/articles/6070 <- msdn
https://test.api.ndla.no/article-api/v2/articles/6297 <- issuu
https://test.api.ndla.no/article-api/v2/articles/6667 <- livestream
=> #1096: Add issuu, livestream, tomknudsen.no and msdn domains to frameSrc

src/components/license/ImageLicenseList.jsx, src/components/license/__tests__/ImageLicenseInfoDownloadUrl.js
connects to https://github.com/NDLANO/Issues/issues/934
Testing:
- Find article with image
- Attempt to download image from "Bruk innhold" and see that it downloads rather than opens in browser
=> #934: Adds query parameter to download image source

src/server/routes/forwardingRoute.js
connected to NDLANO/Issues#1144
By sending the error object from `catch` to `next`, express handles the error as 404, and is not sending it forward to the next matching route
=> dont pass error object to next in forwardingRoute #1144

src/server/server.js
N.B. The following tests require the frontend to use production api
=> Add route match for old node urls with trailing stuff

src/server/server.js
Test needs to be done with prod api
=> feat: handle different paths to node id

src/server/contentSecurityPolicy.js
Må ha med denne for at nye embeds kan vises i frontend.
=> Allw view embeds

src/__tests__/__snapshots__/routeHelpers-test.js.snap, src/__tests__/routeHelpers-test.js, src/containers/ArticlePage/components/ArticleHero.jsx, src/containers/Masthead/MastheadContainer.jsx, src/containers/Masthead/components/MastheadTopics.jsx, src/containers/Masthead/mastheadHelpers.js, src/containers/SubjectPage/components/SubjectPageContent.jsx, src/containers/TopicPage/TopicPage.jsx, src/routeHelpers.jsx
Need to be tested against prod api:
1. Go to /subjects/subject:33
2. Click on «Meny»
3. Check that links to resources contains `subject:33`.
1. Go to /subjects/subject:33
2. Click on «Funksjoner» topic link
3. Click on «Funksjonsbegrepet» topic link
4. Check that the «Funksjoner» breadcrumb link point to correct subject (`subject:33`)
=> Remove use of taxonomy path

src/server/server.js
connects to NDLANO/Issues#1575
The service mesh uses the `Host` header for outgoing requests.
This means that the proxy cannot keep the `Host` header as ex: "ndla.no" .
Enabling `trust proxy` makes `req.hostname` use `X-Forwarded-Host` if it exists.
=> #1575: Enable 'trust proxy' for express

package.json, razzle.config.js, yarn.lock
Var visst ikkje berre å sette helmet som external. Då måtte den inkluderes på ein anna måte og fant ikkje ut av det. Det enkleste er å la helmet være oppgradert og heller sette versjonen til helmet-csp til versjonen uten bowser. så kan vi heller fikse dette ein anna gong.
=> fix helmet-csp version for now

src/containers/SearchPage/__tests__/__snapshots__/searchHelpers-test.js.snap, src/containers/SearchPage/searchHelpers.js
La til fallbackparameter for språk. Vi filtrerte faktisk ut boolske parametre til søket fordi length er undefined for Boolean så eg la til en ekstra sjekk i helperkoden.
=> Add fallback parameter and fix searchHelper function

src/containers/PlainArticlePage/PlainArticlePage.jsx, src/containers/ResourcePage/ResourcePage.jsx, src/gqlSchema.json, src/queries.js
Depends on https://github.com/NDLANO/graphql-api/pull/96
Fixes NDLANO/Issues#2113
When doing SSR we use apollos `renderToStringWithData`. This waits for
graphql requests to finish before returning. When using regular fetch
calls only the initial html will be rendered.
If one wanted to use fetch to aquire data it would have to be done
before the `renderToStringWithData` function is called, and to be used
from props. (IE: Use a class component or rewrite the
`loadGetInitialProps` in defaultRoute.js)
=> #2113: Use graphql-api to fetch plain articles

src/constants.js, src/containers/WelcomePage/WelcomePage.jsx
Artikkelen på forsiden på ff hadde lenker til verktøykassa og tverrfaglige temaer. Etter sammenslåing til en server er det ikke lenker inn til dette lenger. Denne PR legger de to nye boksene med innganger til dette på forsiden.
=> Added toolbox and multidisciplinary-subject to front-page

src/App.js, src/__tests__/routeHelpers-test.js, src/components/Learningpath/LastLearningpathStepInfo.jsx, src/constants.js, src/containers/ArticlePage/ArticlePage.jsx, src/containers/Resources/Resources.jsx, src/containers/SubjectPage/components/MainTopic.jsx, src/containers/SubjectPage/components/SubTopic.jsx, src/containers/TopicPage/TopicContainer.jsx, src/queries.js, src/routeHelpers.jsx, src/shapes.js
Versjonen som er i test/staging i dag scroller berre til topp for ressurser på emner under tredje nivå. Dette løser det problemet, samt at det fikser lenker i launchpad dersom valgte emner på fleire nivå har ressurser.
=> Refactor resources and fixes scrolling for all levels.

src/iframe/IframeArticlePage.js, src/iframe/__tests__/IframeArticlePage-test.js
Etter at vi endra iframe-urler til å kunne være uten språk så feiler dette. Fiksen er ikkje avhengig av at pathen har x antall ledd.
=> Fetch resource id based on pattern

src/containers/SubjectPage/SubjectContainer.jsx, src/util/urlHelper.js
Fikser det at navigering til topic når man har locale valgt legger på duplikat locale string. 
F.eks navigering til topic her http://localhost:3000/nn/subjects/subject:26?filters=urn:filter:ca607ca1-4dd0-4bbd-954f-67461f4b96fc resulterer i at man ender opp her http://localhost:3000/nn/nn/subjects/subject:26/topic:1:191103/?filters=urn:filter:ca607ca1-4dd0-4bbd-954f-67461f4b96fc
Er en litt scuffed fiks for dette, men klarte ikke å finne noen måte å overstyre det at `history.replace` bruker `http://localhost:3000/nn` som base path.
=> fixing history.replace adding duplicate locale to path

src/iframe/IframeArticlePage.js, src/iframe/__tests__/IframeArticlePage-test.js
Det ser ut som om det faktisk var dette som gjorde at oembed-testen feila. En promise som ikkje blei resolva. PR bygger grønt i det minste.
=> Add catch to possibly fix error

package.json, src/__tests__/routeHelpers-test.js, src/containers/Masthead/components/MastheadSearch.jsx, src/containers/ResourcePage/ResourcePage.jsx, src/containers/SearchPage/SearchContainer.jsx, src/containers/SubjectPage/SubjectContainer.jsx, src/containers/SubjectPage/components/SubTopic.jsx, src/iframe/__tests__/__snapshots__/IframeArticlePage-test.js.snap, src/queries.js, src/routeHelpers.jsx, yarn.lock
Fixes NDLANO/Issues#2259
Sikrer at automatisk plukking av filter for ressurs, kun bruker filter som også finnes på emnet. 
Eksempelvis dersom et emne har filter VG1 og VG2, mens ressursen har VG1 og VG3, kan du potensiellt plukke VG3 på ressursen, og dermed få ei side uten fungerende brødsmulesti.
=> Pick filter present on topic

src/containers/Masthead/components/MastheadSearch.jsx, src/containers/SubjectPage/SubjectContainer.jsx
På grunn av manglende vask i taksonomi kan emner ha filter fra andre fag enn det dei ligger i. Det vil sei at det er mulig å automatisk plukke filter som ikkje hører heime i faget, og dermed få kombinasjoner som gir tomme fag.
Eksempel er url https://test.ndla.no/subjects/subject:8b18253e-8b0e-49d7-a97b-2240b46708cf?filters=urn:filter:6b35c125-5a82-4a30-9d60-0646c31dce32 der filteret som plukkes ikkje finnes på faget. PR gjør en ekstra sjekk på filter på subject på om filteret skal velges.
=> Check subject filters before choosing filter from topic

src/constants.js, src/containers/WelcomePage/FrontpageSubjects.jsx, src/containers/WelcomePage/WelcomePage.jsx, src/data/programmes.js, src/data/subjects.js
https://trello.com/c/2A8kKX4t/671-endre-lenker-til-nye-fagforsider
Dette er endringer på Brønnteknikk faga. Men ser at når man velger ett emne så feiler sida. F.eks på /nb/subjects/subject:6/topic:1:182061/?filters=urn:filter:765ff687-efd9-4fd9-82e7-19ba59908d26,urn:filter:01c27030-e8f8-4a7c-a5b3-489fdb8fea30
Kan du sjekke dette Gunnar? Ser ut til at det er Graphql-error
EDIT: Feiler vist berre lokalt mot prod-api. Snodigt
=> Adjust filters on "Tverrfaglige tema", "Verktøykassa" and "Brønnteknikk"

src/App.js, src/client.jsx, src/routes.jsx, src/server/routes/defaultRoute.js
Fixes NDLANO/Issues#2274
Om noen har noe bedre forslag til hvordan vi kan løse dette så er jeg _veldig_ åpen for det :smile: 
Problemet er at google re-hoster siden vår når vi og da får vi en path som ser ish sånn ut `/translate_c`.
Det gjør at react-router prøver å vise den siden (og vi har jo ikke den siden så da ender vi med en 404).
Løser det med å bruke serveren sin path+query når vi er på google-translate (Og kanskje andre sider).
- Serveren sender med requesten sin path + query
- Klienten sjekker om server requesten finnes i queryen fra `withRouter` (I praksis det samme som `window.location`)
- Dersom den gjør det så bruker vi bare "location" objektet fra serveren.
=> #2274: Don't crash when rendering under a different location

src/containers/ArticlePage/ArticlePage.jsx
https://trello.com/c/nz9f6SQU/409-bakgrunnsbilde-i-ndla-film-er-borte
=> Fix missing background-image on ndla-film articles

package.json, src/App.js, src/client.jsx, src/components/Learningpath/LearningpathEmbed.jsx, src/components/SocialMediaMetadata.jsx, src/containers/ArticlePage/ArticlePage.jsx, src/containers/FilmFrontpage/FilmFrontpage.jsx, src/containers/LearningpathPage/LearningpathPage.jsx, src/containers/Page/Page.jsx, src/containers/PlainArticlePage/PlainArticlePage.jsx, src/containers/PlainLearningpathPage/PlainLearningpathPage.jsx, src/containers/ProgrammePage/ProgrammePage.jsx, src/containers/SubjectPage/SubjectContainer.jsx, src/containers/TopicPage/TopicContainer.jsx, src/iframe/FixDialogPosition.js, src/iframe/IframeArticlePage.js, src/iframe/IframePageWrapper.jsx, src/iframe/IframeTopicPage.jsx, src/lti/LtiProvider.jsx, src/server/helpers/__tests__/Document-test.js, src/server/helpers/render.js, src/server/routes/iframeArticleRoute.js, src/server/routes/ltiRoute.js, yarn.lock
Fixes NDLANO/Issues#2274
Fikser så både adresser uten queries / `?` og adresser med språkkode funker i google translate.
~Navigering på forsiden og sånn blir blokkert av translate siden det er javascript som manipulerer på url'en (tror jeg).
Mulig vi kan hacke oss rundt det med å bruke en [annen router](https://reactrouter.com/web/api/MemoryRouter)? Men vet ikke hvor mye tid vi har lyst til å bruke på det.~
Stryk det, testa med `MemoryRouter` under google translate og det fungerer _bedre_, men ikke perfekt.
Funker ikke når vi gjør graphql-queries client side på fagsidene for eksempel, men tror siden er _relativt_ brukbar nå.
=> #2274: Make site work under google translate with language paths and without queries

src/server/routes/__tests__/__snapshots__/oembedArticleRoute-test.js.snap, src/server/routes/oembedArticleRoute.js
Dette er feilen bak https://trello.com/c/9RiTYdqV/693-læringssti-viser-ikke-fram-nn. Eksempelet er steget https://stier.staging.api.ndla.no/nn/learningpaths/499/step/3827 som viser bokmål sjølv om språket nn er med i urlen. 
Endringa er at vi gjeninfører språkkode i iframe-urlen for å være sikker på at korrekt versjon vises. Dette er kun et problem for taksonomiurler i og med at article-urler allerede hadde lang i urlen.
Det kan testes med curl ved å kjøre feks 
`curl http://localhost:3000/oembed\?url=https%3A%2F%2Fstaging.ndla.no%2Fnn%2Fsubjects%2Fsubject%3A1%2Ftopic%3A1%3A186460%2Ftopic%3A1%3A186471%2Fresource%3A1%3A178222`, berre bytt ut localhost-delen med pr-url. Sjekk at iframe-urlen har nn som del av url.
=> Add language version to iframe-url

src/components/license/VideoLicenseList.jsx, src/gqlSchema.json, src/queries.js, src/util/getStructuredDataFromArticle.js
Fixes NDLANO/Issues#2317
Depends on https://github.com/NDLANO/graphql-api/pull/122 and https://github.com/NDLANO/article-converter/pull/202
Nye metadata-felt fra article-converter. Oppdatering av lokalt gql-skjema fikk med datatyper for forklaringsøk som ikkje er tatt inn endå.
=> Add extra fields to json-ld

package.json, src/components/Learningpath/Learningpath.jsx, src/components/Learningpath/LearningpathEmbed.jsx, src/containers/ArticlePage/ArticlePage.jsx, src/containers/ArticlePage/components/ArticleHero.jsx, src/containers/LearningpathPage/LearningpathPage.jsx, src/shapes.js, src/util/__tests__/getStructuredDataFromArticle-test.js, src/util/getStructuredDataFromArticle.js, yarn.lock
Fixes NDLANO/Issues#2357
Legger på BreadcrumbList som json-metadata. Dette gjør at vi kan omgå problemer med uleselige urler ved visning av ndla--urler i google.
Test: 
Versjonen er deploya til test på grunn av manglende travisbygg.
Finn en url som viser en artikkel og sjekk i head på dokumentet at ls-json-script-tagen har breadcrumbs.
Du kan også teste adressa på https://search.google.com/structured-data/testing-tool/
=> Breadcrumb metadata

src/containers/Resources/Resources.jsx
Fixes NDLANO/Issues#2358
Henter om tilleggsressurser skal vises fra localstorage.
Test:
Finn et emne som har tilleggsressurser, feks: http://localhost:3000/subjects/subject:19/topic:1:186558/topic:1:123879/?filters=urn:filter:f3d2143b-66e3-428c-89ca-72c1abc659ea
Om du velger Tilleggstoff og laster sida på nytt skal det huskes. Det skal også hugses på andre sider som har tilleggstoff.
=> saving in localstorage if additional resources should be shown

src/containers/ResourcePage/ResourcePage.jsx, src/lti/LtiProvider.jsx
Fixes NDLANO/Issues#2370
Dersom en ressurs er flytta og kun finnes på en plass, sendes brukeren direkte til den nye plassen.
Fikser også feil label i LTI-sida.
Test:
Finn en vilkårlig ressurs-url og endre i pathen, enten ved å fjerne en topic eller berre endre et tegn. Du skal få en 301 redirect til original url.
=> Redirects user

src/style/index.css
Fjerner marg på visning av matteformler for å få samme visning som i ed.
Fjerner også css-regel som ikkje er i bruk.
=> Remove unused rules

src/containers/WelcomePage/WelcomePage.jsx
Fixes NDLANO/Issues#2382
Lagt til et script for å få opp en søkeboks under søkeresultat på ndla i google (se eksempelbilde). Går så vidt jeg vet ikke an å teste lokalt, og må kanskje deployes til prod for å sjekke om det funker (correct me if im wrong🤷‍♀️). Ifølge [googles dokumentasjon](https://developers.google.com/search/docs/data-types/sitelinks-searchbox) holder det å legge til json-ld i header, men hvis noen vet at det mangler noe mer så si fra😁
Et potensielt problem: I følge [SearchEngineJournal](https://www.searchenginejournal.com/sitelinks-search-box-not-shown/365290) er det ikke garantert at en sånn søkeboks dukker opp selv om man har implementert json-ld, men det kommer an på hva Google velger (og det står også i dokumentasjonen). Per nå dukker det opp en sånn søkeboks når man …
=> #2382 søkeboks fra ndla i google

public/static/h5p-custom-css.css
- Issue https://github.com/NDLANO/Issues/issues/2300
- Trello https://trello.com/c/u9KIMobD/760-knowit-ed-sjekk-dialogkort-i-fagpresentasjon-den-er-altfor-h%C3%B8y
Css fil som inneholder:
- css fil for å oppdatere custom css på h5per med for høye dialogbokser.
- css for å venstrestille tekst i lister i dialogkort i h5per
Legger til custom css fil fra ndla. 
Har brukt disse for testing: http://test.ndla.no/nn/article/22668 og https://test.ndla.no/nb/article/22668
Test på h5p'er med dialogkort
Denne må merges **først** for å få testet ferdig:
* PR i ed: https://github.com/NDLANO/editorial-frontend/pull/853
* PR i article-converter: https://github.com/NDLANO/article-converter/pull/215
=> add h5p-custom-css file in public folder

package.json, src/constants.js, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectArticle.jsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectPage.jsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopic.jsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopicWrapper.jsx, src/containers/SubjectPage/SubjectContainer.jsx, src/containers/SubjectPage/components/Topic.jsx, src/containers/WelcomePage/WelcomePage.jsx, src/data/subjects.js, src/gqlSchema.json, src/queries.js, src/routes.jsx, yarn.lock
Fixes NDLANO/Issues#2375
~Depends on https://github.com/NDLANO/frontend-packages/pull/733~
~Depends on https://github.com/NDLANO/graphql-api/pull/130~
Endrer tverrfaglige emner til å være 2 nivå med emner og deretter emner som vises som kortene vi har i dag.
Kan testes på `/subject:d1fe9d0a-a54d-49db-a4c2-fd5463a7c9e7` url'en
=> #2375: Rewrite multidisciplinary subjects to use topics instead of filters

src/constants.js, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectPage.jsx, src/data/subjects.js
Om du går på side for tverrfaglige tema og manuvrerer deg til en case via menyen så mister du /card fra urlen og dermed vises ikkje caset som det skal. Denne endringa tvinger gjennom at emne på tredje nivå alltid vises som case.
Test: Gå på side for tverrfaglige tema. Bruk Innhold-knappen og naviger fram til emne på tredje nivå. Du skal få opp case-visning.
=> Fjerner card fra url fordi om du går til case via meny så feiler det

src/App.js, src/containers/ResourcePage/ResourcePage.jsx, src/server/contentSecurityPolicy.js
Forsøker å fikse problemet med vindusposisjon etter å ha gått fra søkeresultat til ressurs.
Dersom du søker på ny søkeside og scroller litt ned og finner et søketreff som har fleire kontekster, så kan du klikke på  "+3 flere steder" og så velge en av lenkene i dialogen. Då kjem du til artikkelen med sida scrolla til toppen. Dersom du så bruker tilbakeknappen og velger akkurat samme lenka i dialog, så kjem du til samme sida men scrolla like langt ned som du var på søkesida.
Endringa går på at ved visning av ressurs, så sendes du til toppen dersom du er scrolla ned på sida. Sikkert ikkje optimal løsning, så kom gjerne med bedre forslag.
=> Forcing scroll to top when showing resource

src/App.js
Forhindrer at det scrolles til toppen ved navingering på tverrfaglig side nivå 1 og 2. Scroll til toppen for cases.
Test:
* Gå til side for tverrfaglige tema og scroll litt ned
* Klikk på en av emneknappene og sjekk at du ikkje sendes til toppen
* Klikk deg ned til casene og klikk på caset. No skal du havne på toppen av artikkelcaset.
=> Only scroll to top if case or subject root.

public/static/h5p-custom-css.css
Fixes NDLANO/Issues#2432
Øker padding på tekst i h5p kort slik at tekst ikke skjules bak bilder.
Før:
Etter:
=> 2432: Increasing padding for h5p-dialogcards-card-text-inner

public/static/h5p-custom-css.css
dialogkort har en posisjonering fixed som gjør at diven har en høgde 0, så derfor klarer ikkje innholdet å bli vist som tidligere.
Overstyrer posisjoneringa til relative
Før:
Etter:
=> Replace fixed with relative to give div height

src/containers/SearchPage/searchHelpers.js
I graphql-api settes resource.path til den konteksten som er gitt dersom det er valgt ett fag som søkeparameter til spørringa. Men i ndla-frontend har vi berre vist den første konteksten alltid som hovedurl. Denne endringa gjør at koden i graphql-api ikkje lenger ignoreres men benyttes for å vise lenke til en kontekst i det faget du har valgt i søket.
Test:
Gjør et tomt søk og sjå etter et treff med fleire paths: "+ x flere steder". Sjekk at hovedurl er det samme som den første i lista over ekstra steder. Finn en kontekst litt ned i lista og velg dette faget som filterparameter i søket og sjekk at treffet fremdeles vises. Men no skal hovedurlen være til det faget du nettopp valgte som filter.
=> Bruker resource.path for standard søketreff

src/data/subjects.js
https://trello.com/c/lA2DzYn4/1006-lenke-til-s%C3%B8rsamisk-som-f%C3%B8rstespr%C3%A5k-arkiv
=> Add sør-samisk archived subject

src/components/Article/ArticleContents.jsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopic.jsx, src/containers/SubjectPage/components/Topic.jsx
Fixes NDLANO/Issues#2505
Legger til mulighet for å skjule ingress i ArticleContents. Som beskrevet i issuet vises denne to ganger.
Eksempel på hvordan det ser ut i [test](https://test.ndla.no/nb/subject:39/topic:1:189087?filters=urn:filter:4ad7fe49-b14a-4caf-8e19-ad402d1e2ce6). Når man trykket på "Les emnebeskrivelse" kan man se ingress både ovenfor knappen og i innholdet som dukket opp.
Hvordan teste:
1. https://ndla-frontend-pr-659.ndla.sh
2. Åpne et emne, feks https://ndla-frontend-pr-659.ndla.sh/subject:39/topic:1:189087?filters=urn:filter:4ad7fe49-b14a-4caf-8e19-ad402d1e2ce6
2. Trykk på "Les emnebeskrivelse"
3. Ingress skal ikke dukke i innholdet.
=> Option to show/hide ingress in ArticleContents

src/containers/WelcomePage/WelcomePageSearch.jsx, src/queries.js, src/util/searchHelpers.js, yarn.lock
Fikser bugs relatert til NDLANO/Issues#2499
1. Forslag til søkeord fra tidligere søk hang igjen. Dette gjaldt spesielt dersom man søkte på et ord, lukket søket med escape-knappen og deretter gjorde et nytt søk. Da var det gamle forslaget til søkeord synlig et kort øyeblikk.
2. Forslag til søkeord vil nå alltid være forslaget som har høyest score.
Jeg så på muligheten til å droppe å vise søkeord dersom forslagene har for lav score, men dette fungerte ikke optimalt. Scoren på ordene som foreslås er generelt høy dersom det søkes på et enkeltord, og blir mye lavere dersom det søkes på flere ord. Resultatet blir i så fall at man ender opp med å kutte forslag på mesteparten av søk bestående av to eller flere ord.
=> Bugfix forslag til søkeord

src/config.ts, src/containers/FilmFrontpage/NdlaFilmFrontpage.jsx
Fjerner mulighet for å overstyre artikkeltype brukt for ndla-film i test. Etter db-dump fra prod er dette standard for alle miljø.
=> Remove custom articletype used for ndla-film in test.

src/containers/ArticlePage/articleApi.js, src/containers/PlainArticlePage/PlainArticlePage.jsx, src/gqlSchema.json, src/iframe/IframePage.jsx, src/iframe/IframePageContainer.jsx, src/iframe/__tests__/IframeArticlePage-test.js, src/lti/components/LtiBasicLaunch.jsx, src/lti/components/LtiDeepLinking.jsx, src/queries.js, src/server/routes/__tests__/__snapshots__/oembedArticleRoute-test.js.snap, src/server/routes/__tests__/iframeArticleRoute-test.js, src/server/routes/iframeArticleRoute.js, src/server/routes/oembedArticleRoute.ts
Fixes NDLANO/Issues#2566
Depends on https://github.com/NDLANO/graphql-api/pull/156
Vil alltid vise oembed-versjon på iframe-urler. Treng ikkje ha med ekstra parameter fordi iframe _er_ oembed,
=> Using new isOembed param. But not for plain article page.

src/data/subjects.js
Noen fag har `visible: false` så når man prøver å trykke på de kommer beskjeden `Siden finnes ikke` er det meningen at det skal være sånn? Faget finnes når man søker på det via swagger men kommer ikke opp via nettsiden.
eks. `Norsk SF Vg2 - 2021 BETA` og `Norsk YF Vg2 - 2021 BETA`
=> linked tax-2 subjectId and removed filter from beta subjects

src/components/Learningpath/Learningpath.jsx, src/components/Learningpath/LearningpathEmbed.jsx, src/components/Learningpath/LearningpathIframe.tsx
Fixes NDLANO/Issue#2567
Har lagt til nesten samme komponenten som viser oembeds i learningpath-frontend i ndla-frontend for å ha en listener som følger med på når iframer for ndla-artikler lastes inn i læringssteg, så de vises i sin fulle størrelse i stedet for i en liten iframe som må scrolles i.
F.eks. i artikler som dette: https://ndla-frontend-pr-685.ndla.sh/subject:42/topic:1:198227/topic:1:198361/resource:1:170189/7501?filters=urn:filter:22dee9ab-5b1a-4c23-8c97-c68107b881bb vil det nå heller vises i en fullsize iframe. 
Andre iframes som er en del av artiklene som vanlig blir ikke påvirket av dette, f.eks: https://ndla-frontend-pr-685.ndla.sh/subject:6/topic:1:182849/topic:1:175043/resource:1:176514/22?filters=urn:filter:01c27030-e8f8-4a7c-a5b3-489fdb8fea30
=> 2567 utvide visning av oembed artikler i læringssteg

src/containers/ArticlePage/ArticlePage.jsx, src/containers/FilmFrontpage/FilmFrontpage.jsx, src/containers/LearningpathPage/LearningpathPage.jsx, src/containers/MultidisciplinarySubject/components/MultidisciplinarySubjectArticle.jsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopic.jsx, src/containers/PlainArticlePage/PlainArticlePage.jsx, src/containers/PlainLearningpathPage/PlainLearningpathPage.jsx, src/containers/ProgrammePage/ProgrammePage.jsx, src/containers/SubjectPage/SubjectContainer.jsx, src/containers/SubjectPage/components/Topic.jsx, src/containers/TopicPage/TopicContainer.jsx, src/iframe/IframeArticlePage.js, src/iframe/IframeTopicPage.jsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/util/__tests__/titleHelper-test.ts, src/util/titleHelper.ts
Ny helper som lager tittel-element på formatet 'Artikkel - Fag - NDLA'.
Alle titler på sider skal være på samme format som tidligerer, men med artikkelnavnet først og ikkje som nest siste ledd.
Test:
Sammenlign titler på sider fra pr og test.ndla.no.
=> Add htmlTitle helper. Use helper to generate titles.

src/server/podcastRssFeed.ts
Fixes NDLANO/Issues#2682
Test:
Sjekk url /podkast/3/feed.xml og sjekk at komma mellom episoder og forfattere er borte. Author skal også kun være NDLA og ikkje henta fra episodene.
=> Fjerner komma og authors fra generert xml.

src/containers/Masthead/components/MastheadTopics.tsx, src/containers/Masthead/mastheadHelpers.ts, src/graphqlTypes.ts
Ref https://github.com/NDLANO/frontend-packages/pull/853.
Har lagt inn en midlertidig fiks som gjør at visning av ugrupperte ressurser vises korrekt. Dette burde reverseres så fort PRen over er ute i prod.
Oppdaterte samtidig et par interfaces som ikke så ut til å stemme.
=> Temporary fix to show ungrouped resources

src/containers/SearchPage/SearchContainer.jsx, src/containers/SearchPage/SearchInnerPage.jsx, src/containers/SearchPage/components/SearchHeader.jsx
Fixes NDLANO/Issues#2722
Depends on https://github.com/NDLANO/frontend-packages/pull/858
Fjerner også dobbel språkvelger fra søkesida. Jeg fjernet også "Filtrer på innholdstype" når det bare er en innholdstype i tillegg til for søk uten treff.
=> 2722 handle no search results

src/containers/Masthead/components/MastheadTopics.tsx
Tilknyttet NDLANO/Issues#2718
Oppgaven er ferdig, men det ble gjort en midlertidig sortering i ndla-frontend fram til ny versjon av pakker ble tatt i bruk. Fjerner nå denne sorteringen siden ny pakker brukes.
Hvordan teste:
- Åpne PR-instans
- Gå til feks: /subject:1:a3c1b65a-c41f-4879-b650-32a13fe1801b/topic:2:1:187398/topic:4:1:165209/
- Listen på denne siden skal være ugruppert. Dersom du åpner masthead skal det vises en liste med de samme ressursene som også er ugruppert og likt sortert.
=> Remove temporary sorting of ungrouped resoures

src/containers/MultidisciplinarySubject/MultidisciplinarySubjectArticlePage.jsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectArticlePage.tsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectPage.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinarySubjectArticle.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopic.jsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopic.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopicWrapper.tsx, src/gqlSchema.json, src/queries.ts
Akuttsak fra ndla.no. Emner for tverrfaglige tema vises ikkje lenger som dei skal. Har kopiert kode fra Topic.tsx inntil videre, men sida bør omskrives til typescript.
Avhenger av https://github.com/NDLANO/graphql-api/pull/190 og https://github.com/NDLANO/article-converter/pull/274
Test:
Klikk deg inn på pr-installasjon og velg tverffaglige tema. Visuelt element skal vises når du klikker deg inn på et kort.
=> Fiks visning av emne for tverrfaglig tema.

src/containers/ArticlePage/ArticlePage.jsx, src/util/getArticleScripts.ts
https://github.com/NDLANO/Issues/issues/2702
Jeg klarer ikke å gjenskape feilen lenger. Virker som at dette kan oppstå når MathJax ikke er null, men ikke har initialisert seg ferdig. Problemet løste seg først når jeg la inn en typeof-check. Risikoen vil eventuelt være at typeset ikke blir kjørt hvis man virkelig beveger seg fort. 
Dette er en vanskelig fiks å teste. Her er hvordan man enklest kan fremkalle den.
1.  Gå til en artikkel på ndla.no, f.eks https://ndla.no/subject:1:ca607ca1-4dd0-4bbd-954f-67461f4b96fc/topic:1:89f902cb-98f4-4acc-be79-d3e2f40a8bf1/topic:1:5bd0cbfd-14fe-4201-b1c7-baa4e1504b48/resource:46831ee6-48ab-4525-a483-21961291267f
2. Hard refresh siden. 
3. Før siden har lastet ferdig, klikk på "utholdenhet"-breadcrumben. 
4. Naviger deg tilbake til artikkelen.
=> Initial attempt at fixing MathJax error

src/containers/Resources/Resources.jsx, src/queries.ts
Fixes NDLANO/Issues#2769
Depends on ~https://github.com/NDLANO/graphql-api/pull/193~
Fikser sortering av ressurser ved å legge til parameter i graphql. Det er fordi uten parameter så hentes ressursen med rank=undefined og då havner ressursen øverst i lista. Legger også til active-flagg i ugrupperte ressurser.
Test: Sjekk følgende artikler at ugrupperte ressurser kjem i korrekt rekkefølge og at Du er her vises.
https://ndla-frontend-pr-788.ndla.sh/subject:20/topic:1:186732/topic:1:187167/resource:1:151951
https://ndla-frontend-pr-788.ndla.sh/subject:1:a3c1b65a-c41f-4879-b650-32a13fe1801b/topic:2:1:187398/topic:4:1:165209/resource:1:116671
=> Fixes sorting of resources by adding topicid as param to graphql

src/containers/MovedResourcePage/MovedResourcePage.jsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts
Fixes https://github.com/NDLANO/Issues/issues/2771
Setter ny sidetittel for "sider som har flyttet". 
Hvordan teste:
* besøk /subject:80063181-61d8-4c52-9bbc-4313376175a2/topic:b34684b3-3e91-44ee-88b4-1c3e588586dc/topic:1cc14972-df1f-4294-b19b-1c2472f5489a/topic:a00fc42f-30b9-44f4-94ad-76adcaee3079/resource:1:193411
* sjekk at sidetittel er `Siden har flyttet - NDLA` istedenfor `NDLA`
=> fixed site title for moved resource page

src/I18nWrapper.tsx, src/components/Article/CompetenceGoals.jsx, src/containers/FilmFrontpage/NdlaFilmFrontpage.jsx, src/containers/ResourcePage/ResourcePage.jsx, src/util/runQueries.ts
Under arbeid
Fixes NDLANO/Issues#2778
Fikser en feil der feil språkversjon blir hentet. Legger på `accept-language`-parameter manuelt basert på i18n.
Problemet ser ut til å oppstå i de fleste sider i ndla frontend
Hvordan teste:
1. Sørg for at du allerede har besøk PR-instansen og at språket er satt til nn.
2. Lukk deretter siden og åpne /subject:1:78e538a3-78bf-4db2-af00-2ca7d721cb25/topic:2:198170/topic:2:198460/, uten language prefix.
3. Teksten som vises skal være på nynorsk. Gjør du det samme i test får du bokmål.
=> 2778 bugfix language graphql query

src/containers/SearchPage/searchHelpers.js
Fixes https://github.com/NDLANO/Issues/issues/2784
La på en statisk bredde. Funksjonaliteten brukes kun for å vise flyttede topics og ressurser. Feilen kommer av at et `Image` nå wrappes i en `StyledImageWrapper`, som gjør at `SearchResultItem`-scss'en overstyres.
=> Added a static width to resultsWithContentTypeBagdeAndImage

src/containers/LearningpathPage/LearningpathPage.jsx, src/containers/Masthead/MastheadContainer.tsx, src/containers/TopicPage/TopicContainer.jsx
Fixes NDLANO/Issues#2860
Gjør at breadcrumbs har samme språk overalt.
Test:
* Åpne test.ndla.no og klikk deg fram til en artikkel. Bytt språk til nynorsk. Breadcrumb for artikkel er nynorsk. Scroll ned slik at breadcrumb skjules, og breadcrumb i masthead vises. Denne er på bokmål.
* Gjør det samme i denne branchen, og sjekk at breadcrumb i masthead er samme som for artikkel.
=> Use locale as parameter.

src/config.ts
This makes boolean environment variables false if they are not set to
`true` when converted to lowercase. This makes FEIDE_ENABLED act as
expected.
Kan testes ved å sjekke at FEIDE ikonet ikke dukker opp dersom `FEIDE_ENABLED` er satt til `false` feks istedet for å mangle.
=> #2874: Handle boolean fallbacks in config

src/style/index.css
Legger på en px padding for å gjøre matte litt penere.
Uten padding: 
Med padding:
Det er en liten forskjell men den er synlig, spesiellt på B. Sjekk også /article/31308 i pr-installasjon.
=> Justerer matte styling.

public/static/mathjax-config.js, src/style/index.css, src/util/getArticleScripts.ts
Setter nyeste mathjax. Måtte endre litt på stylinga for at ikkje formler skulle kuttes, pga endring i bredde på feks vektorer.
Gammel mathjax:
Ny mathjax:
Vektorpiler er penere opptegna. Avstand mellom formler er litt større på grunn av padding, men det måtte til for ikkje å kutte noen av vektorene:
=> Upgrade mathjax and adjust styling to fix rendering.

package.json, yarn.lock
Bumper for å få alpha-versjon av pakke.
Test
* Søk opp artikkel som er tilleggstoff, og klikk deg inn på den. Artikkelen skal vises i launchpad sjølv om tilleggstoff er skjult.
* Om du navigerer deg fra ressursen forsvinner den.
=> Show active resource anyways

src/containers/SearchPage/SearchInnerPage.jsx
Fixes NDLANO/Issues#2837
Den andre feilen der henting av flere søkeresultater ikke fungerer ser det ut som er fikset allerede?
Hvordan teste:
* Åpne test.ndla.no
* Gå til søkesida.
* Klikk på filter Simulering under fagstoff, og du får 34 treff
* Klikk på knapp Fagstoff øverst, og du går inn i gruppa med simulering valgt og 34 treff.
* Klikk på Fjern filter. Fagstoff skal fortsatt ha 34 resultater og Simulering skal fortsatt være markert. (I master blir markeringen av simulering fjernet)
=> Do not reset subtypes on reset content type filter in search

src/components/Status.tsx, src/containers/NotFoundPage/NotFoundPage.tsx
La en `ts-ignore` i Status for å unngå å type StaticContext. Dette kommer til å endre seg når vi oppgraderer til React Router 6. Venter derfor med å ta den jobben til den kommer.
=> Converted NotFoundPage to TypeScript

package.json, src/components/Article/Article.tsx, src/constants.ts, src/containers/ResourcePage/ResourcePage.tsx, yarn.lock
Fixes NDLANO/Issues#2888
Depends on https://github.com/NDLANO/frontend-packages/pull/928
Depends on https://github.com/NDLANO/article-converter/pull/290
Denne gjør at vi hydrater `CopyParagraphButton` komponenten, og at vi
scroller til en id om den finnes i url-fragmentet (etter #) i `Article`.
Denne er litt omfattende å teste, men fremgangsmåten blir noe som det her:
- Link `@ndla/ui` inn i article-converter og ndla-frontend (på branchene fra PR'ene over)
- Spinn opp article-converter med `yarn start`
- Spinn opp graphql (master) med `yarn start-with-local-converter`
- Spinn opp ndla-frontend med `yarn start-with-local-graphql-and-article-converter`
- Test at link ikonet dukker opp når du hovrer over h2 titler i artikler.
- Test at lenken blir kopiert når du trykker på den
- Test at …
=> #2888: Scroll to header if hash in `Article` matches header

src/data/programmes.ts
Fixes NDLANO/Issues#2922
Test:
* Sjekk at Sammfunnsfaglig engelsk ligger under Vg3 for Studiespesialisering.
=> Added subject to programme

src/containers/Masthead/components/MastheadTopics.tsx
Fixes https://github.com/NDLANO/Issues/issues/2925
Funksjonen som ble passert inn i `toSubject` returnerte ikke en verdi, men kalte bare på en funksjon som returnerte en verdi.
Feilen kan testes ved å gå n antall nivåer dypt i et fag, for deretter å trykke på "gå til fagforside" i Masthead. Dette skal ta deg til ndla.no/subject:$URN.
=> Fix subject page link by returning something from handleSubjectClick

src/containers/ArticlePage/ArticlePage.tsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectArticlePage.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinarySubjectArticle.tsx, src/containers/ResourcePage/ResourcePage.tsx
Fixes https://github.com/NDLANO/Issues/issues/2970
Hopping til innhold er avhengige av at innholdet skal ha id'en som passeres ned i `skipToContentId`. Dette så ut til å ha blitt erstattet med den faktiske artikkelen sin ID. 
Valgte å ikke legge det inn på Iframe-endepunktene, da de ikke støtter hopping til innhold uansett.
=> Change Article id to skipToContentId

src/iframe/index.tsx, src/server/routes/iframeArticleRoute.js
Fixes https://github.com/NDLANO/Issues/issues/2956
Ser ut som at `window.hasHydrated = true` gjorde susen. Tror absolutt at SSR-prosessen kan forenkles litt, men det får skje en annen gang.
=> Fix emotion cache for iframe endpoints

src/I18nWrapper.tsx
Fixes https://github.com/NDLANO/Issues/issues/2983
Kan testes ved å følge instruksjonene i trello-kortet, bare at man erstatter ndla.no med localhost:3000.
=> Account for parameters when doing automatic language redirects

src/containers/SubjectPage/components/Topic.tsx, src/util/imageHelpers.ts
Fixes NDLANO/Issues#2977
Fjerner crop-informasjon fra visuelt element som sendes inn til `Topic`-komponenten. Sirkelformet bildet som er croppet skal da vises i full størrelse ved ekspandering.
Hvordan teste: Sammenlign disse to. I test skal ekspandert bilde være croppet. Det skal det ikke være i PR-instans.
https://test.ndla.no/en/subject:1:1f1865fc-e4cc-48a0-918f-3530485ec424/topic:1:ae0e6304-d30e-4d3f-8e94-306d1a884e10
og
https://ndla-frontend-pr-877.ndla.sh/en/subject:1:1f1865fc-e4cc-48a0-918f-3530485ec424/topic:1:ae0e6304-d30e-4d3f-8e94-306d1a884e10
=> Do not use crop on previewing topic visual element in full size

src/server/helpers/render.js, src/server/routes/defaultRoute.js
Hydrering av apollo-state viste seg å være brukket. Vi kalte rett og slett på `client.extract()` for tidlig, så `apolloState` var alltid et tomt objekt. Nå funker det faktisk ordentlig. Konsekvensen av dette er at vi slipper å se at siden blir hydrert, for deretter å gå rett tilbake i en loading-state. Nå slipper vi å gjøre doble graphql-kall!
Merk derimot at dette fortsatt er et problem for iframe-endepunktet. Der er det litt vanskeligere å fikse opp i ting, da apollo-klienten først opprettes lenger ned i treet. Skal se nærmere på det i morgen, men kan godt hende det ender opp i egen PR.
=> Fixed apolloState and client-side hydration

src/containers/FilmFrontpage/NdlaFilmFrontpage.tsx, src/containers/SubjectPage/components/MovedTopicPage.tsx, src/gqlSchema.json, src/graphqlTypes.ts, src/queries.ts
Denne PR-en er ikke lenger relatert til NDLANO/Issues#2978.
Henter nå kun nye versjon av GQL-skjemaer fra graphql-api og retter opp i typefeil som oppsto. Som diskutert brukes fragments nå for ikke-fullstendige spørringer på objekter. Dette gjør at vi får generert matchende TS-typer.
=> Fix GQL errors

src/containers/LearningpathPage/LearningpathPage.tsx
Forårsaket av TS-omskrivningen i https://github.com/NDLANO/ndla-frontend/pull/837.
=> Fixed typescript error in LearningpathPage

src/components/license/licenseHelpers.ts, src/containers/FilmFrontpage/FilmFrontpage.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopic.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopicWrapper.tsx, src/containers/SubjectPage/SubjectContainer.tsx, src/containers/SubjectPage/components/SubjectPageContent.tsx, src/containers/SubjectPage/components/SubjectPageInformation.tsx, src/containers/SubjectPage/components/Topic.tsx, src/containers/SubjectPage/components/TopicWrapper.tsx, src/containers/ToolboxSubject/ToolboxSubjectContainer.tsx, src/containers/ToolboxSubject/components/ToolboxTopicContainer.tsx, src/containers/ToolboxSubject/components/ToolboxTopicWrapper.tsx, src/gqlSchema.json, src/graphqlTypes.ts, src/queries.ts
Feilen kommer av at vi prøvde å bruke en fragment av en type som ikke lenger gjaldt for forklaringer. 
Jo mer "riktig" GQL-typene blir, jo vanskeligere blir det å type det ordentlig. Kanskje det er på tide at vi ser nærmere på colocation snart?
=> Update schema and fix resulting typescript errors

src/containers/ToolboxSubject/ToolboxSubjectContainer.tsx
Fixes https://github.com/NDLANO/Issues/issues/2998
Løsningen er ikke kjempepen. Når man klikker på et emne vil `setSelectedTopics` kalles to ganger. Vi kan dog ikke lytte på klikk i Masthead herifra, så det er den "reneste" måten å gjøre det på.
=> Empty selectedTopics when pathname changes

package.json
Litt overkill å formatere hele prosjektet når man genererer typer, men da slipper vi den obligatoriske "fmt"-commiten.
=> Call yarn format after when calling generate-gql-types

src/components/license/LicenseBox.tsx, src/components/license/TextLicenseList.tsx
Tittel har ikke tidligere blitt vist før i lisensboks for tekst ved klikk på "regler for bruk".
Nå skal tittel vises dersom det finnes.
Hvordan teste:
1. Åpne en artikkel.
2. Trykk på "regler for bruk"
3. Velg fanen "tekst".
4. Tittel på artikkel skal vises øverst i den hvite boksen.
=> Add title to text tab in article license box

src/components/VisualElement/VisualElementLicenseButtons.tsx, src/components/license/ConceptLicenseList.tsx, src/components/license/H5pLicenseList.tsx, src/components/license/VideoLicenseList.tsx, src/gqlSchema.json, src/graphqlTypes.ts, src/queries.ts
Avhengig av og merges samtidig som https://github.com/NDLANO/graphql-api/pull/237
copyText er fjernet for alt bortsett fra tekst, bilde og podcast. Fjerner derfor bruken av dette.
=> Update graphql types. Remove copyText from multiple figure types in code

src/components/VisualElement/VisualElementWrapper.tsx
Fixes https://github.com/NDLANO/Issues/issues/3031
Istedenfor å plukke første copyright-array henter vi første som inneholder > 1 elementer.
=> Pick first non-empty list of copyrightholder

src/components/license/AudioLicenseList.tsx, src/components/license/ConceptLicenseList.tsx, src/components/license/H5pLicenseList.tsx, src/components/license/ImageLicenseList.tsx, src/components/license/LicenseBox.tsx, src/components/license/TextLicenseList.tsx, src/components/license/VideoLicenseList.tsx, src/components/license/licenseFragments.ts, src/components/license/licenseHelpers.ts, src/graphqlTypes.ts
Prøver å unngå en massiv PR med colocated fragments, så inntil videre har ikke dette noen umiddelbar effekt annet enn at typene endrer seg.
Bør også nevnes at jeg foreslår en navngivningskonvensjon på colocated fragments her: Tanken inntil videre er `$componentName_$schemaType`. Dersom man lager en fragment på `Article` i komponenten `LicenseBox` vil navnet da være `LicenseBox_Article`, mens det genererte typenavnet vil være `GQLLicenseBox_ArticleFragment`. På sikt kunne vi endret autogenererte navn til å være `LicenseBox_Article`, så lenge vi sier at underscore kun skal brukes i GQL-typer.
=> Added colocated fragments to all LicenseBox components

src/components/Article/ArticleContents.tsx, src/containers/Resources/Resources.tsx, src/containers/SubjectPage/components/Topic.tsx, src/containers/SubjectPage/components/TopicWrapper.tsx, src/graphqlTypes.ts, src/util/transformArticle.ts
Dette kommer også med en positiv side-effekt: lasting av topics blir veldig raskt (for det meste).
En ulempe vi begynner å støte på her er at wrapping av exporten fører til at `.fragments` ikke lenger finnes. Man kan fjerne HOC der det er mulig, men der det ikke kan gjøres må vi eksportere fragments separat.
=> Topic colocation

src/components/VisualElement/VisualElementWrapper.tsx
Fikser forespørsel fra Trello. Denne er klar for review, men avventer merge til jeg har fått tommel opp på Trello også.
Rettighetshaver og opphaver skal vises samtidig om begge deler eksisterer.
=> Show both creators and rightsholders in visualelement if exists

src/containers/PodcastPage/Podcast.tsx
To små endringer:
- Knappen som åpner lisensinformasjon for bilde har nå label "Bruk bilde" og ikke "Bruk innhold".
- Bilde med copyright viser nå ikke knapp for kopiering av kildehenvisning.
=> Change open image license label. Hide reference button on copyright

src/components/Learningpath/LearningpathEmbed.tsx, src/containers/Resources/Resources.tsx
Vi trenger å sende med subjectid til disse endepunkta for at korrekt path skal plukkes ut.
Test:
* Må kjøres lokalt med NDLA_ENVIRONMENT=prod
* Åpne artikkelen http://localhost:3000/nb/subject:7509b507-548d-48e1-bef3-a06758e4820c/topic:109b4977-b2d1-4895-b24c-9ec1ba911bec/resource:bd019e72-a6a6-4644-beda-6161574cc405
* Neste må gjøres uten å laste sida på nytt for å unngå å ødelegge cache:
* I menyen velg Alle fag -> Norsk (SF vg3) 2022/2023 - BETA -> Tekst i kontekst -> Sammensatte tekster
* I launchpad til emnet skal artikkelen du først gikk til ligge, men med korrekt path fra emnet.
Alternativt, bruk pr-installasjon og finn en artikkel som brukes i fleire emner og gjør tilsvarende.
=> Legger på parameter for å forsikre at korrekt path velges.

src/server/programmeSitemap.ts, src/server/server.ts
Veldig enkel generering av sitemap for programområder.
Test
* Sjekk path /sitemap-utdanningsprogram.txt og sjå at du får ut lista med områder.
=> Simple programme sitemap generation.

src/containers/SearchPage/searchHelpers.tsx
Fixes https://github.com/NDLANO/Issues/issues/3045
Faller tilbake til metabilde-alttekst
=> Prefer resource name over meta image alttext on search page

src/client.tsx
Avhengig av https://github.com/NDLANO/article-converter/pull/314
Portaler som rendres likt på både klient og server er avhengig av `removeUniversalPortal`, mens de som går gjennom `article-converter` først krasjer. Dette sørger for at vi ikke fjerner portaler fra `article-converter`.
Kan testes ved å spinne opp article-converter, graphql og ndla-frontend lokalt, for deretter å sjekke at http://localhost:3000/nn/subject:1:f18b0daa-6507-4025-8998-b8a11c8ccc70/topic:5:dbc23651-7216-4610-bc38-dde58f013724/topic:3:fe851509-1f3c-4fef-9922-ae05ff1a4fba/resource:5edb583f-b7a9-4d04-8f3b-58100188e8ce ikke krasjer.
=> Check for article-converter flag before removing portal

package.json, src/components/AlertsContext.tsx, src/containers/Masthead/MastheadContainer.tsx, src/containers/WelcomePage/WelcomePage.tsx, src/graphqlTypes.ts, src/queries.ts, src/schema.graphql, yarn.lock
Fixes NDLANO/Issues#3037
Banner utvides med mer funksjonalitet:
- Rendering av markdown og dermed støtte for lenker.
- Bruk av tag "permanent" på https://github.com/NDLANO/oppetid/issues for å gjøre at banner ikke kan lukkes.
- Ved lukking av banner vil det ikke lenger vises for brukeren selv etter refresh.
Bruk gjerne dette issuet til å teste: https://github.com/NDLANO/oppetid/issues/47
1. Sjekk at lenke rendres.
2. Lukk banner og refresh siden. Banner skal ikke dukke opp igjen med mindre localStorage slettes eller "permanent"-tag skrus på.
3. Legg til "permanent"-tag og sjekk at lukk-knapp forsvinner når taggen er satt.
=> 3037 extended alert functionality

now.json, package.json, yarn.lock
Følgende endringer er gjort:
- deploy i vercel bruker nå node 14 og ikke node 12.
- Byttet ut deprecated @now/node-server og byttet ut med @vercel/node.
- Oppdaterte ndla-ui samtidig.
=> Bugfix now deploy

src/App.tsx, src/I18nWrapper.tsx, src/client.tsx, src/components/VersionHashContext.tsx, src/i18n.ts, src/routes.tsx, src/server/routes/defaultRoute.js, src/util/apiHelpers.ts
Fixes https://github.com/NDLANO/Issues/issues/3080
Avhengig av https://github.com/NDLANO/graphql-api/pull/247
Kan testes ved å kjøre mot lokal graphql, og sette `versionHash=ae9f` som queryParam. Da skal du kunne navigere en spesifikk versjon av taksonomi inntil du gjør en full refresh av siden.
=> Add version-hash parameter to App

src/containers/PodcastPage/Podcast.tsx
Fikser tre feil i podkaster oppdaget på https://ndla.no/podkast/3:
- Ved klikk på "bruk bildet" på scrolles man alltid til øverste podkast.
- Viser riktige forfattere på caption på bilde. Dette ble tidligere hentet fra podkast og var derfor identisk.
- Viser opphavere OG rettighetshavere, alternativt bearbeidere dersom de andre ikke finnes.
Angående siste vises ikke lenger "Leverandør", "Korrektur" osv foran navn til forfattere. Har ikke sett at dette brukes på figurer andre steder lenger, så fjernet det derfor.
Hvordan teste:
1. Åpne en podkast-serie som har flere episoder med samme bilde.
2. Sjekk at scroll gjøres til den aktuelle episoden ved trykk på bildelisens
3. Forfattere på bilde og podkast skal nå være forskjellig
4. Bearbeidere på bilde og podkast skal kun vises dersom annet …
=> Podcast license fixes

src/util/getStructuredDataFromArticle.ts
Fixes https://github.com/NDLANO/Issues/issues/3093
Forces json-ld to be duplicated in ssr and client.
Test:
* Finn en artikkel med video og lim urlen inn i https://validator.schema.org/
* Sjekk at du kun får en article og breadcrumb
=> Removing contentUrl to avoid fastly_token.

src/graphqlTypes.ts, src/iframe/IframePage.tsx, src/server/contentSecurityPolicy.ts
Depends on https://github.com/NDLANO/graphql-api/pull/255
NDLANO/Issues#3123
Viser visuelt element for emneartikler
Test:
* Må kjøres lokalt med graphql-api
* Åpne http://localhost:3000/lti og klikk på en av emneartklene og sjekk at du får visuelt element
=> Adds visual element for iframe topic article

e2e/integration/resource_page.spec.ts, package.json, src/components/Learningpath/Learningpath.tsx, src/containers/ArticlePage/components/ArticleHero.tsx, src/containers/Masthead/MastheadContainer.tsx, yarn.lock
Har oppdatert brødsmulestier til siste versjon. Her skal det ikke være noen endringer. Brødsmulestier skal se ut og oppføre seg likt som før. Noen små variasjoner i marginer osv kan det være.
Noen steder brødsmulestier finnes
- Masthead i ndla-film. Dukker opp ved scroll
- Masthead i artikler, emner. Trykk feks inn på tverrfaglige emner. Dukker opp ved scroll.
- Toppen av læringsressurs
- Toppen av læringsressurs i ndla film
=> Implement new breadcrumbs

src/client.tsx, src/constants.ts, src/lti/LtiProvider.tsx, src/lti/index.tsx, src/server/routes/defaultRoute.js
Relatert til https://trello.com/c/IMRsQNDm/1725-bug-bokm%C3%A5l-artikkel-p%C3%A5-nynorsk-url
I prod nå vil det oppstå en mismatch i språket som brukes av server og client dersom man går til /nn/ når det lagrede språket ditt er `nb`. Da blir man automatisk redirectet til `/nb/`, men dette skjer client-side. Siden er allerede returnert fra serveren, og vil derfor være på nynorsk. Det er uheldig.
Løsningen er å flytte det lagrede språket fra localStorage til cookies. Da har vi muligheten til å lese det på server, for deretter å sette riktig språk uavhengig av om `basename` egentlig matcher. Dette kan føre til litt rare situasjoner, som i at `/nn/` kan returnere bokmål, men det er kanskje ikke så viktig? Alternativt kan vi gjøre en redirect til /nb/ på server.
=> Set stored language as a cookie instead of in local storage

e2e/integration/topic_page.spec.ts, src/containers/ArticlePage/components/ArticleHero.tsx, src/containers/WelcomePage/FrontpageSubjects.tsx, src/i18n.ts, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts
Som tittelen forteller. Fikser https://trello.com/c/SxY8ouUe/1731-legge-til-utfyllende-tekst-i-gult-varslingsfelt-p%C3%A5-toppen-av-siden-for-beta
=> Overstyrer en tekst fra frontend-packages for å slippe å bumpe ndla-ui.

src/containers/SearchPage/searchHelpers.tsx
Closes https://github.com/NDLANO/Issues/issues/3164 
Dersom man søker på test i https://test.ndla.no/lti og velger første emne, var url-en https://test.ndla.no/article-iframe/urn:20086/20086. For emner uten kontekst (som denne) skal riktig url nå være https://test.ndla.no/article-iframe/article/20086.
=> Fix correct url for subjects without context

src/server/server.ts
Fixes NDLANO/Issues#3179
allow-from ignoreres uansett av frameguard, samt at fleste nettlesere ikkje lenger støtter det. Behovet vi hadde for å godkjenne sti.ndla.no er borte for lengst.
=> Old sti-url is long gone. No need for embedding anymore.

src/components/Article/Article.tsx, src/components/CompetenceGoals.tsx, src/iframe/IframeArticlePage.tsx, src/iframe/IframeTopicPage.tsx
Fixes NDLANO/Issues#3161
Bruker isOembed for å sette at søk etter kompetansemål skal åpne i ny fane. Brukes kun fra iframe-sidene.
=> Send isOembed-param to CompetenceGoalTab

src/containers/MyNdla/folderMutations.ts
Her har jeg gjort en liten bommert. Dette fikser tre ting:
* Sletting av mapper på rotnivå
* Oppdatering av antall ressurser/submapper på en rotmappe
* Å legge til ressurser på nylig opprettede rotmapper.
=> Save new folders as refs instead of full objects in order to fix mutations on root folders

src/components/MyNdla/LoginComponent.tsx, src/containers/MyNdla/Folders/FoldersPage.tsx
* Add alt text to login image.
* Adjust spacing in login modal
* Remove description from login modal resource
* Disable add folder button when already adding
https://trello.com/c/rhsB2KVt/120-innloggingsbilde-mangler-alt-tekst
https://trello.com/c/Ln84Zmmp/114-det-f%C3%B8rste-dialogvinduet-har-litt-rar-tekstfont-og-spacing
https://trello.com/c/bUeKQMHa/115-hvis-jeg-legger-til-en-ny-mappe-i-dialogvinduet-s%C3%A5-er-ny-mappe-knappen-fortsatt-aktiv-dersom-jeg-klikker-p%C3%A5-ny-mappe-s%C3%A5-forsvinn
=> My NDLA adjustments

src/components/MyNdla/AddResourceToFolder.tsx
https://trello.com/c/cLKZmc1R/147-lenke-b%C3%B8r-ligge-p%C3%A5-mappenavn-ikke-vis-ord
Avhengig av https://github.com/NDLANO/frontend-packages/pull/1263
=> Remove show translation in favor of having the folder link as the link name

src/components/MyNdla/AddResourceToFolder.tsx
Tags skal nå loades ved førte åpning av modal for å legge til en ressurs i min ndla.
Hvordan teste:
- Start lokalt
- Åpne feks /subject:1:8bfd0a97-d456-448d-8b5f-3bc49e445b37/topic:5:1:165344/topic:4:1:165378/resource:1:100791
- Klikk på hjerte øverst til høyre, legg til noen tags og lagre i en mappe.
- Refresh siden og klikk på hjertet igjen. Tags skal lastes inn med en gang. (På test vises tags som tomt ved første åpning)
=> Load tags after importing folders

src/data/programmes.ts, src/data/subjects.ts
Faget vart splitta i ulike programfag i sommar, dette er no tomt.
>Naturbruk (NA-NAB vg1) er jo delt opp i Naturbasert næringsaktivitet (NA-NAB vg1) og Naturbasert produksjon og tjenesteyting (NA-NAB vg1), så da bør Naturbruk (NA-NAB vg1) fjernes fra forsida. Nå ligger den der helt tømt for innhold.
=> Faget naturbruk er endra

src/containers/MyNdla/Folders/ResourceList.tsx, src/containers/MyNdla/MyNdlaPage.tsx, src/containers/MyNdla/Tags/TagsPage.tsx
Fixes https://trello.com/c/nlxTDuuO/129-metabilder-i-lenker-skal-ha-tomt-alt-attributt
Bilder i ressurser skal ha tom alt-tekst siden dette er inni en lenke. Dette skal nå gjelde på alle tre undersider på min ndla.
=> Dont show alt text in resource image

src/containers/MyNdla/Folders/FoldersPage.tsx, src/util/folderHelpers.tsx
https://trello.com/c/JT0Uv2a0/153-antall-undermapper-og-ressurser-viser-ikke-ressurser-i-undermapper
Teller alle mapper og ressurser under en mappe. Kom ikke på noen mer effektiv måte å gjøre det på enn memoization, men kom gjerne med forslag!
=> Add recursive counting for subfolders and resources on a folder resource

src/containers/MyNdla/Folders/FoldersPage.tsx, src/containers/MyNdla/MyNdlaPage.tsx, src/containers/MyNdla/folderMutations.ts
https://trello.com/c/t6C9nLMU/160-har-slettet-alle-mapper-p%C3%A5-min-ndla-f%C3%A5r-da-et-litt-ulogisk-bilde-p%C3%A5-min-side
Jeg klarte aldri å gjenskape problemet, men jeg så at det var flere ressurser som lå igjen i cache etter sletting. Dette kommer mest sannsynligvis av at en/flere queries fortsatt referer til de. Hvis dette ikke holder må vi nesten begynne å slette queries fra cache.
Fikser også https://trello.com/c/xnSAmtRk/159-f%C3%A5r-to-mapper-hvis-jeg-trykker-enter-veldig-raskt-to-ganger-p%C3%A5-rappen på mappe-siden, men ikke i modal.
=> Add additional garbage collection to reduce risk of invalid ui results

src/util/apiHelpers.ts
Sender versionHash kun dersom den er fra parameter. Unngår å alltid sende 'default'. Kjem pr i graphql også.
=> Send kun versionHash dersom den er satt fra url

src/containers/Masthead/MastheadContainer.tsx
Sammen med aria-hidden vil dette føre til at ikonet ignoreres fullstendig.
=> Remove alt text from Feide icon in My NDLA link

src/containers/Resources/Resources.tsx
https://trello.com/c/317gqktD/195-det-g%C3%A5r-ikke-lenger-an-%C3%A5-favorittmerke-fra-launchpad-i-en-tverrfaglig-ressurs
=> Added onToggleAddToFavorites logic for ungrouped resources

src/containers/Page/Layout.tsx
Sammenlign tab-navigering med nåværende frontend. Merk at tab-navigering bakover alltid vil sørge for at det fokuserte elementet er synlig i denne løsningen, mens det ofte vil være skjult i den gamle.
Fixes https://github.com/NDLANO/Issues/issues/3217
=> Added dynamic scroll padding to ensure focusable elements do not end behind the masthead

src/containers/Masthead/MastheadContainer.tsx
Var et problem med at masthead breadcrumb'en ikke ble oppdatert om man navigerte til forsiden.
Kan testes ved å navigere til en side som har breadcrumb (Feks `/subject:e18b8bf0-326b-45f6-8e95-982de8f34264/`), for så å navigere til forsiden igjen og scrolle ned og se at breadcrumben i mastheaden er tom.
=> Reset initial state in masthead if empty params

src/components/FeideLoginButton/FeideLoginButton.tsx
https://trello.com/c/bLt2yBNd/204-masthead-ikonet-for-min-ndla-beskriver-ikke-form%C3%A5let-sitt-n%C3%A5r-man-er-innlogget
=> Use aria-label My NDLA instead of username

src/components/AuthenticationContext.tsx, src/containers/Login/LoginProviders.ts, src/containers/Login/LoginSuccess.tsx, src/server/helpers/openidHelper.ts, src/util/authHelpers.ts
Fixes https://github.com/NDLANO/Issues/issues/3270
Legger til default-parameter `prompt: none` til feide-login'en.
Dersom login feiler med `interaction_required` error så setter vi `needsInteraction` i `AuthenticationContext`.
Kan testes ved å se at feidelogin fungerer som før, med mindre du allerede er logget inn (Men ikke har cookie). Da skal login gå uten å trenge å gå innom-feide siden.
=> Implement promptless login to feide

src/containers/Masthead/MastheadContainer.tsx
Kan testes ved å se at masthead querien ikke gjør et graphql-kall som feiler dersom vi trykker oss tilbake til forsiden fra et emne.
=> Fix initial masthead state reset

src/server/routes/defaultRoute.js
Fixes NDLANO/Issues#3263
Tar med originale parametre i redirect på grunn av språk.
Test:
* Gå inn på pr.-installasjon og endre språk til nn
* Lim inn url /search?subjects=urn:subject:1:19dae192-699d-488f-8218-d81535ce3ae3&grepCodes=KM2688
* Du skal tas til nn-versjonen av sida med parametrene beholdt. I test blir parametre strippa bort.
=> Use originalUrl for redirect to preserve params

src/components/FeideLoginButton/FeideLoginButton.tsx, src/containers/AccessDeniedPage/AccessDeniedPage.tsx, src/containers/MyNdla/MyNdlaPage.tsx, src/server/server.ts, src/util/urlHelper.ts
Innlogging feilet når man hadde et basename. Dette tar hensyn til det. Ikke pent, men funksjonelt. Kommer dette til å knekke proxy, @gunnarvelle? Isåfall må vi finne en lur måte å unngå `/nn/{log(in|out)}/`
=> Handle different language prefix cases for logging in and out

src/server/server.ts
`"" ?? "fallback"` returnerer visst `""`, og ikke `"fallback"`. Dette fikser det, slik at vi ikke lenger får en tom language-cookie.
=> Handle case where languageCookie is empty properly

src/client.tsx, src/server/routes/defaultRoute.js
Fixes https://github.com/NDLANO/Issues/issues/3273
(tror jeg)
Kan testes ved å sjekke at vi rendrer orginal path og setter cookien til språket fra pathen dersom du ikke har en fra før av.
Dersom du har cookie, skal du bli redirected som før.
=> Stop redirecting to 'nb' if we don't have a cookie

src/server/helpers/Document.tsx
Fun fact: Grunnen til at "Hopp til innhold" alltid er synlig er at det er det aller første i emotion-css-strengen.
=> Remove dollar sign that breaks the first css object extracted by emotion

src/components/MyNdla/AddResourceToFolder.tsx
Fikser en feil der valgt mappe ble overstyrt dersom man opprettet ny mappe. Se https://trello.com/c/c6ROMy8O/269-feilmelding-etter-oppretting-av-ny-mappe-i-trestruktur.
Hvordan teste:
- Naviger inn i mappene (A) og finn en ressurs. Trykk legg til mappe/emneknagg.
- Opprett umiddelbart en ny mappe (B) i trestruktur.
- Feilmelding tidligere ville vise at ressursen allerede finnes, dette fordi valgt mappe-id ble tilbakestilt til våre A og ikke B. 
- Lagre og se at ressurs ble lagret i mappe B som forventet.
=> Prevent overriding selected folder on saving new folder in treestructure

src/components/MyNdla/AddResourceToFolder.tsx
Ved lagring av ressurs med nye tags i en mappe der ressursen allerede eksisterte førte til duplikat i cachen. Bruker en eksisterende sjekk til å droppe lagring i mappe dersom den allerede finnes. Se https://trello.com/c/YTp9329I/270-duplikate-ressurser-i-test
Kan framprovoseres i test ved å oppdatere tags og lagre ressursen i en mappe der den allerede finnes. Tilsvarende teste PR lokalt.
=> Prevent saving duplicate resource when already in folder

public/static/mathjax-config.js, src/containers/ArticlePage/ArticlePage.tsx, src/containers/LearningpathPage/LearningpathPage.tsx, src/containers/PlainArticlePage/PlainArticleContainer.tsx, src/containers/PlainLearningpathPage/PlainLearningpathContainer.tsx, src/util/getArticleScripts.ts
Generering av aria-label kan av og til føre til at typeset feiler ved rerender. Dette forhindrer at sida krasher på grunn av en error som ikkje plukkes opp. Ser ikkje ut som om det har praktisk betydning.
Test:
Denne sida har eg opplevd har feila ved hypping lasting: https://test.ndla.no/nb/subject:1:3ae2c40f-4661-4863-9987-4944ff534974/topic:2:165540/topic:2:165558/resource:1:95726
Tilsvarende url i pr bør rendres uten feil.
=> Add catch for mathjax error

package.json, src/components/MyNdla/AddResourceToFolder.tsx, yarn.lock
Fikser tre feil.
Det skal ikke lenger dukke opp duplikate tags i tagvelger etter man oppretter mappe i trestruktur.:
https://trello.com/c/lLKLenan/271-duplikater-av-tags-i-tagforslaget-i-tagvelgeren
Forhindrer framtidige feilmeldinger på mappeside pga en liten feil i BlockResource der det ikke ble tatt hensyn til tomme lister.  Kommer fra pakkeoppdatering:
https://trello.com/c/IUi3BC7Q/272-navigering-i-sidemeny-ved-blokkvisning-gir-feilmelding
I trestruktur var det kun mulig å opprette opptil fire mapper i dybden. Dette er nå oppdatert til fem som er riktig. Kommer fra pakkeoppdatering:
https://trello.com/c/23BtFFVi/273-mismatch-mellom-maks-mappedybde-i-mappevisning-og-trestruktur
=> Myndla hotfixes

src/graphqlTypes.ts, src/schema.graphql, src/util/apiHelpers.ts
Skille på typer for artikler og læringssti for foldermeta.
Testes sammen med [NDLANO/graphql-api](https://github.com/NDLANO/graphql-api/pull/278)
Test:
* Hent foldermeta for artikkel og læringssti som deler id:
* Læringssti id 3: /subject:1:01c27030-e8f8-4a7c-a5b3-489fdb8fea30/topic:2:182849/topic:2:175043/resource:1:176514 
* Artikkel id 3: /subject:1:19dae192-699d-488f-8218-d81535ce3ae3/topic:2:179373/topic:2:170165/resource:1:124037
=> Separate types for foldermeta for articles and learningpath

src/App.tsx, src/client.tsx, src/components/AuthenticationContext.tsx, src/containers/PrivateRoute/PrivateRoute.tsx, src/iframe/index.tsx, src/lti/index.tsx, src/server/routes/defaultRoute.js, src/server/routes/iframeArticleRoute.tsx, src/server/server.ts, src/util/apiHelpers.ts
Dette vil kreve at vi tilpasser koden litt de stedene vi ikke kan serverside rendre feide ting (IE penere loading rundtom).
I fremtiden kan vi kanskje velge å skrive oss helt vekk fra cookies sånn at vi er tryggere på at det ikke skjer igjen, men dette vil i alle fall ikke lekke credentials.
=> Stop passing cookie to apollo client on server

src/containers/MyNdla/Tags/TagsPage.tsx
Blokkvisning i emneknagg-siden skal nå vise blokkressurs og ikke listeressurs.
=> Fix block view in tags page

src/containers/MyNdla/Folders/FolderList.tsx
Fixes https://github.com/NDLANO/Issues/issues/3315
Kan også fikse selve input-komponenten, men med dårligere brukeropplevelse. Input er såpass liten at placeholder-teksten kuttes tidlig.
=> Move new folder input outside of block wrapper to avoid overflow issues

package.json, yarn.lock
Legger til `@babel/core` og `graphql-tag` som devDeps, og oppdaterer eslint.
=> Reduce peer dep warnings

Dockerfile, src/server/helpers/openidHelper.ts
Ved innlogging ble det ofte logget pm2-problemer der opptil flere av instansene krasjet og ble startet på nytt. Vi vet ikke hvorfor, men det burde uansett ikke være nødvendig med både kubernetes og pm2 for lastbalansering. Har ikke klart å gjenskape noen feilmeldinger etter denne endringen ble gjort. 
Har samtidig skrevet om slik at Issuer bare hentes en gang per ndla-frontend instans. Det burde gjøre både innlogging og utlogging raskere. Det loggføres dersom Issuer ikke finnes og må hentes på nytt.
PRen er manuelt deployed til test slik at det kan verifiseres at det fungerer der.
=> Fikse 502-feilmelding ved innlogging

package.json, razzle.config.js, yarn.lock
Fikser https://github.com/NDLANO/ndla-frontend/security/dependabot/57
Fikser https://github.com/NDLANO/ndla-frontend/security/dependabot/47
Fikser https://github.com/NDLANO/ndla-frontend/security/dependabot/48
Fikser https://github.com/NDLANO/ndla-frontend/security/dependabot/49
Fikser https://github.com/NDLANO/ndla-frontend/security/dependabot/32
Fikser https://github.com/NDLANO/ndla-frontend/security/dependabot/26
Fikser https://github.com/NDLANO/ndla-frontend/security/dependabot/25
I tillegg er dette første steg til å komme oss over på webpack 5, som igjen vil fjerne en hel haug med vulns. 
Endringene i razzle-configen måtte til for å bevare vår nåværende logging. `infrastructureLogging` fjerner litt noise som forteller deg hvilke porter webpack-ting kjører på, mens `stats` fjerner …
=> Bump webpack-dev-server to most recent version

package.json, yarn.lock
Bumper cypress et par minor-versjoner for å slippe unna `listr`. Dette fikser ikke en spesifikk vuln, men får oss nærmere. Ser ut til å kjøre fint lokalt, både med vanlig build og prod-build.
=> Slightly bump cypress to avoid old chalk version

src/lti/index.tsx
Upon inspection it seems like ltiData always is undefined (image1), this is most likely due to ltiData being inserted into the initialProps and not the `DATA` object itself (image2).
image1:
image2:
You need to test this yourselves but I have attached my basic form data that doesnt work for me, (I only get the modal saying "Det fungerte ikke å sette inn innholdet automatisk.")
=> Read ltiData from initialProps variable in window.DATA

package.json, src/graphqlTypes.ts, src/schema.graphql, yarn.lock
Avhengig av https://github.com/NDLANO/graphql-api/pull/268.
Oppdaterer graphql-typer og bumper samtidig apollo-klienten
=> Update apollo dep and graphql types

src/containers/PrivateRoute/PrivateRoute.tsx
Fixes https://github.com/NDLANO/Issues/issues/3306
Bruk av Navigate fungerer kun i kontekst av react router. Bytter det ut med en hard page reload som tar oss til det faktiske server-endepunktet, som tar seg av resten av innlogginsflyten.
=> Fix private route login redirection

package.json, yarn.lock
Fikser https://github.com/NDLANO/ndla-frontend/security/dependabot/84
Fikser https://github.com/NDLANO/ndla-frontend/security/dependabot/14
Eneste breaking changes i changelog er økning av påkrevd node-versjon.
=> Bump postcss-loader

src/server/routes/defaultRoute.js
Fikser denne feilen:
```
TypeError: Cannot read properties of undefined (reading 'isMobile')
```
=> Prevent isMobile error in defaultRoute

package.json, yarn.lock
Vi har allerede en indirekte dep på v6, så bumper like gjerne den direkte dep'en også.
=> Bump serialize-javascript dep to match other version in lockfile

package.json, yarn.lock
Cross-env er nå i maintenance mode, men tenker det er greit å i det minste være på nyeste versjon.
=> Bump cross-env to latest

package.json, yarn.lock
TypeScript 4.9 er ute, og har mer performant file-watching.
=> Bump typescript to 4.9

src/graphqlTypes.ts, src/util/getStructuredDataFromArticle.ts
Fant en feil i generert json-ld for kjerneelement der verdier fra læreplanen var brukt. 
Kan testes på /subject:1:09410bfa-5b0d-470b-8727-5006e711bc1f/topic:1:25d7645a-b089-4418-b79c-59ad819aa515/resource:1:4045
=> Bruker korrekte verdier for kjerne-element

src/containers/MyNdla/MyNdlaMobileMenuPage.tsx, src/util/folderHelpers.tsx
Ser ut som at dette har blitt glemt bort ved overgang til navigasjonslenker på toppnivå. Tror vi kan gjøre dette litt mer uu-vennlig, men fint å få et review på dette med en gang. Kan testes av alle ved å spoofe user-agent som mobil i browser.
=> Do not use old tree structure way of showing mobile navigation

src/util/apiHelpers.ts
Filtrerer ut GQL-feilmeldinger som oppstår på grunn av 404. Logger fortsatt server-side. Disse ender ofte opp med å bare være `undefined:undefined` i loggly.
=> Only send GQL error messages to loggly if they are not 404s

src/containers/MyNdla/Folders/DraggableFolder.tsx
Fixes NDLANO/Issues#3316
Fikser en feil der mapper og ressurser med lang tekst overflyter containeren sin.
Se nærmere beskrivelse i issue. Må testes lokalt
=> Prevent folders and resources from overflowing container

src/containers/LearningpathPage/LearningpathPage.tsx
Fixes https://ace.useit.se/ax/accessibility-issues-report.php?show=731&shared=9116698184701048&lang=nb#issue3704
Sidetittel oppdateres ikke når man bytter læringssteg. Dette fører til at fokus ikke resettes, og at sideendring ikke leses opp.
=> Update page title when changing learning step

src/containers/AllSubjectsPage/AllSubjectsPage.tsx, src/containers/AllSubjectsPage/LetterNavigation.tsx, src/containers/AllSubjectsPage/SubjectCategory.tsx, src/containers/Masthead/drawer/BackButton.tsx
Et par feilrettinger som er rapportert inn på alle fag-siden og ny navigasjon.
Større heading
--------
Mindre margin rundt bokstavfilter og subjects. Første gir plass til flere bokstaver på små skjermer.
-------
Breakpoint mellom mobilWide og tablet hvor denne ikke ble vist
=> Fix ul margin overrides on mobile on allsubjects page. Larger H2 font size on mobile subject category

src/messages/messagesNB.ts, src/messages/messagesNN.ts
Fant en liten feil på nynorsk og bokmål visning av podkast.
Oppdaterer translations slik at disse nå bruker `page` og ikke `pageNumber`.
Hvordan teste:
Åpne /podkast
Sjekk at sidetall vises i tittel på alle språk
=> Fix podcastpage page number translation

src/components/VersionHashContext.tsx, src/containers/Page/Layout.tsx
Fixes https://github.com/NDLANO/Issues/issues/3436
Tenkte det var et greit sted siden vi allerede har littegran logikk der og det allerede fantes en `Helmet`. Forslag tas i mot med åpne armer 🤗
Kan testes ved å se at man får med en `meta` tag som ligner på denne når man spesifiserer `?versionHash=123`
```html
<meta name="robots" content="noindex">
```
=> Add robots meta noindex tag when versionHash is specified

src/components/MyNdla/AddResourceToFolderModal.tsx
Fikser et problem der man i en liten stund får feil modalinnhold når man ikke er logget inn og prøver å legge til en ressurs.
Kan testes ved å throttle nettet sitt og legge til en ressurs uten å være logget inn.
=> Show list resource loading indicator while fetching resource metadata

src/containers/Masthead/drawer/TopicMenu.tsx
Fixes https://trello.com/c/u8b2UrEZ/300-ugruppert-launchpad-leser-ikke-opp-innholdstypene-i-menyen
Kan testes ved å sjekke aria-label på ugrupperte ressurser i skuffen.
=> Add content type to aria label in masthead drawer item

src/components/Article/ArticleContents.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinarySubjectArticle.tsx, src/util/getArticleScripts.ts
Hverken `ArticleContents` eller `MultidisciplinarySubjectArticle` inkluderer scripts når de rendrer en artikkel. Er dette noe vi trenger å legge til støtte for?
=> Include h5p scripts in head if h5p is present in article

src/server/routes/ltiRoute.tsx
En liten mismatch mellom typing av språk mellom skriving og lesing av språk til window.DATA.
html-tag i /lti skal nå vise riktig språk og ikke object: object
=> Fix html meta language on lti page

src/containers/SharedFolderPage/SharedFolderPage.tsx, src/containers/SharedFolderPage/components/FolderMeta.tsx
https://trello.com/c/9ojboioa/316-test-deling-landingsside-delt-mappe-mangler-padding
David lærer har en god mappe å teste dette på. "Jonas sin mappe" legger på ekstra padding basert på sidebar, mens "Undermappe" legger på ekstra padding basert på FolderMeta.
=> Add more padding to shared folder meta page

src/containers/MyNdla/folderMutations.ts, src/graphqlTypes.ts, src/schema.graphql
Avhengig av https://github.com/NDLANO/graphql-api/pull/321
Fikser en feil som Angelica fant. Dette kan testes på David-brukeren under "Angelica sin hovedmappe". Feilen er som følger:
Dersom du starter på Min NDLA og går til forhåndsvis mappe gjennom knapp vil du se alle undermappene til den delte mappen, uavhengig av om de er delt eller ikke. Dersom du starter på forhåndsvis mappe og går til Min NDLA ser du bare delte mapper, og ikke private mapper.
Det finnes nok bedre løsninger som ikke krever nytt kall til serveren, men dette er bra nok.
=> Do not share cache between regular folders and shared folders to avoid cache mismatches

src/components/Learningpath/LearningpathEmbed.tsx, src/graphqlTypes.ts
Fikser en feil som fører til at noen læringssteg ikke vises når ny article-converter er skrudd av.
Læringsstier begynner nå å bli ganske så rotete. Her er det jeg har prøvd å få til:
* Dersom vi har en fullverdig artikkel lagret i læringsstien og ny article-converter er _skrudd av_, hent data på nytt med article-converter skrudd på.
* Dersom vi har en fullverdig artikkel lagret i læringsstien og ny article-converter er _skrudd på_, bruk eksisterende data.
* Dersom dataen finnes som en embed, hent ut ID fra embed og hent data med ny article-converter.
* Embeds som ikke er på NDLA.no skal vises som vanlig embed.
* Ingen data skal hentes for introduksjonssteg.
For å teste dette må man kjøre lokalt med article-converter skrudd både på og av.
Kan testes med f.eks …
=> Always use new article converter for learning path steps

src/components/license/ImageLicenseList.tsx, src/components/license/LicenseBox.tsx
Test: Åpne en artikkel og klikk på Regler for bruk. Sjekk at kildehenvisning til bilde inneheld lenke til artikkelsida uten undefined der artikkelid skal være.
=> Fikser manglende bilde-id i kildehenvisning

src/containers/ArticlePage/components/ArticleHero.tsx
Sjekk forskjellen på brødsmulesti på en film-artikkel her og på test. Nå kan man klikke på brødsmulestien igjen.
=> Fix breadcrumb on ndla film page

package.json, yarn.lock
Eneste breaking er at vi ikke lenger kan bruke node 12. Det kan vi leve med.
=> Major bump of concurrently for node 18 support

src/App.tsx, src/config.ts, src/iframe/index.tsx, src/server/helpers/Document.tsx
Dropper håndtering av gaTrackingId fordi GA3 er på vei ut.
=> Removing gaTrackinId from ndla-frontend.

src/containers/SearchPage/searchHelpers.tsx
I test så vil slice fjerne første leddet, og det er der subtypen ligger, mens den tidligere antageligvis låg sist.
Sammenlign labels fra test og fra pr-installsjon og sjekk at subtyper som "Oppgave" vises under "Oppgaver og aktiviteter"
=> Fixes missing sub-types in search-result

src/containers/ResourceEmbed/components/ResourceEmbed.tsx
Fixes https://trello.com/c/SZ1o4EwI/317-skjule-regler-for-bruk-n%C3%A5r-tom
Hadde egentlig en litt mer fancy løsning, men TypeScript nektet å la meg type det ordentlig.
=> Only show license box if embed contains copyright

src/util/apiHelpers.ts
Fjerner bruken av `eduPersonPrimaryAffiliation`, bruker heller `eduPersonAffiliation`
depends on https://github.com/NDLANO/frontend-packages/pull/1786
=> Updated to match future frontend-packages edits

src/util/__tests__/getStructuredDataFromArticle-test.js, src/util/getStructuredDataFromArticle.ts
Jeg kan ingenting om json-ld, men det krasjer visstnok i safari når man har en array med verdier. Baserte meg på https://stackoverflow.com/questions/76995140/safari-throws-when-parsing-json-ld. Ser ut som at det validerer fint
=> Use a different json-ld structure to fix crash in Safari

src/util/getArticleScripts.ts
Dette forenkler prosessen ved å endre skjermleserspråk i MathJax ved å inline SRE-konfigurasjonen til MathJax inn i `getArticleScripts`. Det fjerner også feilmeldingen "redeclaration of const params" når man går fra en side med MathJax til en annen side med MathJax. Kan testes ved å sjekke at SRE-språket i en MathJax-artikkel endres når sidespråket endres.
Tar over for https://github.com/NDLANO/ndla-frontend/pull/1293
=> Set MathJax config directly instead of setting it from a script

src/server/contentSecurityPolicy.ts
Det fungerte ikke å spinne opp ndla-frontend lokalt med safari.
=> Ensure localhost usage in safari does not automatically upgrade http to https

src/containers/WelcomePage/Components/Programmes.tsx
Fixes https://trello.com/c/acxCFgCL/433-menybilde-vises-ikke-p%C3%A5-tablet-breakpoint-bommert
Denne komponenten vises kun dersom vi parser user-agent til å være tablet eller mobil. Da kan vi like så godt vise den uavhengig av skjermstørrelse.
=> Show programme image regardless of breakpoint

package.json, src/client.tsx, src/interfaces.ts
Nå som vi har en hook-basert tracking-løsning trenger vi ikke lenger å ha vår egentlig router-implementasjon. 
Vår gamle (pre RR-6) implementasjon kan ses her: https://github.com/NDLANO/ndla-frontend/commit/1e61f8a0f2ffa58976bcbb409f2ab35dc511ff24#diff-569ca76b06e4d37aa02c89f6387f4edabb8afc5248af38311a126361a4df63ea
=> Replace custom router implementation with standard react-router components

src/containers/Masthead/components/MastheadSearch.tsx
https://github.com/NDLANO/Issues/issues/3772
La det til på keydown (istedenfor keypress), da chrome hadde en lei tendens til å legge til `/` i query
=> Open search with slash

src/containers/Masthead/components/MastheadSearch.tsx
element is an input or a textare
=> Do not allow slash focus when search modal is open, or when the active

src/containers/MyNdla/components/UserInfo.tsx
Fikser https://trello.com/c/exOheewW/476-feil-oversettelse-av-brukerkategori-fra-feide
=> Invert user check

.github/workflows/ci.yml, Dockerfile, package.json
Bumper node for sikkerhetsfikser. Bygger fint lokalt, og kjører via docker så ingen kompabilitetsproblemer.
=> Use node 18.18

src/config.ts, src/server/server.ts
Jan hos NDLA ønsker å få tak i feide_auth cookie fra ai.ndla.no for å sjekke at brukere faktisk er logga inn. 
Det såg ikkje ut som om feideDomain var i bruk så brukte den i stedet for å lage en ny. dev må ha localhost for at cookie skal settes.
=> Repurpose feideDomain for feide cookie

src/constants.ts, src/containers/ProgrammePage/ProgrammePage.tsx
For å hjelpe alle som har lagra gammel url kan en 301 hjelpe. 
Merk at i redirect-record peikes det på 'pabygg__6ea1ed34e5e7' mens taksonomi returnerer 'påbygg__6ea1ed34e5e7'. Dette går bra fordi det er '__6ea1ed34e5e7' som er signifikant del av urlen. ~Eg måtte ta bort øå fra redirects på grunn av at det feila. Det beste hadde vore å bruke korrekt path, så kom gjerne med forslag.~
Test:
Forsøk å gå til en gammel programfagurl som pabygg eller studiespesialiering og sjå at du redirectes til korrekt side.
=> Redirect if old programme path

src/config.ts, src/containers/MyNdla/MyNdlaPage.tsx, src/containers/MyNdla/configQueries.ts, src/graphqlTypes.ts, src/schema.graphql, src/util/apiHelpers.ts
Depends on https://github.com/NDLANO/backend/pull/333 and [NDLANO/graphql-api/](https://github.com/NDLANO/graphql-api/pull/384)
~Får henta config fra backend men det funker ikkje å lese det ut fra value-feltet. Aner ikkje kvifor og finn ikkje ut av det.~
Kun eg som ikkje kan kode.
Test:
Kjør lokalt (fordi vercel ikkje funker med feide) og logg inn som frank_foreleser. Du skal få opp kampanjeblokk. Andre brukere skal ikkje få (om dei ikkje er i Universitetet i Rogn).
=> Fetches config from backend in stead of config.

src/components/LtiContext.tsx, src/containers/SearchPage/searchHelpers.tsx, src/iframe/IframeArticlePage.tsx, src/lti/LtiIframePage.tsx, src/lti/LtiProvider.tsx, src/lti/index.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts
Tenk å trenge så vanskelig kode bare for å legge til en tilbakeknapp.
LTI var ikke så veldig glad i sidenavigering, så jeg følte meg litt tvunget til å implementere client-side routing. Har testet med saLTIre og på localhost:3000. Kan eventuelt spørre Haldor om de har mulighet til å teste med en PR-instans.
Sjekk at LTI fungerer som det gjorde før når man ikke tester med LTI-integrasjon. Akkurat saLTIre er det nok greiest at vi tester sammen på jobb, da det er litt umulig å sette opp
=> Add a back button to LTI resources

src/containers/MyNdla/FavoriteSubjects/FavoriteSubjectsPage.tsx, src/containers/MyNdla/MyProfile/MyProfilePage.tsx, src/containers/MyNdla/components/MyNdlaTitle.tsx
Oppdaterer stylingen på myNdlaTitle. Selv om komponenten er litt barebone nå tenker jeg den er fin å ha for å få satt på `SKIP_TO_CONTENT_ID`
=> Added new design to myNdlaTitle

src/containers/MyNdla/Arena/TopicPage.tsx
Brukeren navigeres automatisk til den nyopprettede tråden, noe skjermleseren vil plukke opp
Fixes https://trello.com/c/Rg9pffyk/573-manglende-tekst-for-myndlaarenacreatetopic
=> Remove redundant snackbar from topic creation

src/containers/MyNdla/Arena/components/ArenaForm.tsx
Fikser en feil der bakgrunnen på inputet i lenke-editoren forsvant.
=> Make input appear as intended by not wrapping the entire MarkdownEditor in a InputContainer

src/containers/MyNdla/Arena/components/PostCard.tsx
Fixes https://github.com/NDLANO/Issues/issues/3861
Brukt en div istedet i Text wrapperen, siden det parsede inneholdet allerede er paragraphs.
=> Fixing double paragraph trouble

src/containers/MyNdla/Folders/FolderActions.tsx, src/containers/MyNdla/Folders/FolderButtons.tsx, src/containers/MyNdla/components/SettingsMenu.tsx
Fixes https://github.com/NDLANO/Issues/issues/3865
Forhåndsvisning-knappen forsvant også i en merge, så den er også lagt på igjen.
=> Preview-button in settingsmenu not focusable with keyboard navigation

src/containers/MyNdla/components/NotificationList.tsx
fikser https://trello.com/c/v6JAsPtl/611-manglende-spacing-mellom-navn-og-svarte-p%C3%A5
Mista en spacing i en merge, kunne kanskje ha brukt `&nbsp;`, men syntes det var like ryddig å bare legge på en space der.
Liker ikke tanken på å ha space i oversettelsen så dette var det jeg slo meg ned på.
=> Added spacing that got lost

src/containers/MyNdla/Arena/PostsPage.tsx, src/containers/MyNdla/Arena/components/PostCard.tsx, src/containers/MyNdla/arenaQueries.ts, src/graphqlTypes.ts
Depends on https://github.com/NDLANO/graphql-api/pull/413
Henter location på bruker og viser på post. Dropper affiliation-felt som uansett var feil.
=> Fetch location on user and display.

src/containers/MyNdla/Arena/PostsPage.tsx, src/containers/MyNdla/Arena/components/PostCard.tsx
fixes https://github.com/NDLANO/Issues/issues/3871
Added word-wrap on postcard incase of long links or texts. Fixed margin left when mobile postspage.
Så at mobil versjonen ikke matcha designet så la inn en mega rask fiks for det også.
=> Link does'nt break

src/containers/Masthead/components/MastheadSearch.tsx
Reduserer størrelsen på søk på mobil. Ser ikke ut som at nåværende søkefelt fører til overflow, men det er ikke langt unna. Syntes selv at det gir mer mening at den tar opp like mye plass som de andre knappene i masthead.
=> Make masthead search button smaller on mobile

src/containers/ErrorPage/__tests__/__snapshots__/ErrorPage-test.js.snap, src/containers/Page/components/Footer.tsx
Zendesk knappen tok spacing og gjorde så vi fikk et hvitt skille mellom footer og main content. Gjelder kun minndla og frontpage-artikler"
=> Fjerner bare den hvite spacingen som kom med zendeskbutton

src/containers/MyNdla/Arena/components/PostCard.tsx
PostCards ble for brede for skjermen, og gjorde at en måtte scrolle til side på mindre skjermer. Denne lille tweaken fikser det problemet.
Feilen kan sees på f.eks. https://test.ndla.no/minndla/arena/topic/151 ved minimere skjermbredde.
=> PostCard width fix

src/components/MarkdownEditor/FloatingLinkEditorPlugin.tsx
Fjerner autofocus når du blar gjennom teksten. Om du beveger cursor inn i en link block så vil fokus gå direkte inn i link popover. Popoveren vil også dekke ordet.
=> Moved link to be floating below word initially also

src/containers/MyNdla/components/NotificationList.tsx, src/containers/MyNdla/nodebbQueries.ts
Skip nodebb query fetch if nodebb not enabled. Default to deleted user if user object doesn't exist in notifications list
=> Small tidying 

e2e/apiMock.ts
Ser at vi ikke har noen god måte i vite når en GQL batch request forandrer seg som vil gjøre at testene feiler. 
Legger til en `console.error` for å gi beskjed om det skjer, vi kan også vurdere om vi skal partially matche fixtures om vi ikke får perfekt match.
=> Added error log if mock route operationname is not matching

src/containers/ErrorPage/ErrorPage.tsx, src/iframe/IframePage.tsx, src/server/server.ts
Dette fjerner en del hydreringsfeil som kan oppstå når man f.eks sender ugyldige parametre til GraphQL. Kan gjenskapes i prod ved å gå til ndla.no/concept/123asd. Burde vi gå for en mer robust løsning enn dette? Feil som oppstår i koden vår blir allerede catchet på toppnivå, og plukkes opp av feilhåndtering på toppnivå i express.
=> Load ErrorPage bundle instead of normal bundle when encountering an unrecoverable error

src/components/license/LicenseBox.tsx, src/components/license/TextLicenseList.tsx, src/graphqlTypes.ts, src/schema.graphql
Depends on https://github.com/NDLANO/graphql-api/pull/437
Legger til blokk for copyrightembed under tekst i regler for bruk.
Testes på https://ndla-frontend-pr-1762.ndla.sh/article/38557
=> Show license for textblocks

src/server/server.ts
Dette sørger for at man ikke må restarte dev-serveren hvis man rerendrer med ugyldig syntax.
=> Add rudimentary error handling for cases where the vite dev server fails to parse a render route.

src/containers/SharedFolderPage/components/FolderMeta.tsx
Dette er satt til true på icon uansett.
=> Remove redundant ariahidden prop

src/containers/SearchPage/SearchContainer.tsx
Fixes https://trello.com/c/VT40vNOn/798-s%C3%B8k-filtrer-ut-fag-som-resultat-om-du-allereie-er-i-eit-fag
=> Only show subject search results when no subject ids are present

src/containers/MyNdla/nodebbQueries.ts
Fikser [#4008](https://github.com/orgs/NDLANO/projects/2/views/9?pane=issue&itemId=60029601)
En liten bug der skip i querien overskriver andre skips
p.s. må koble lokalt mot nodeBB
=> remove skip that overwrites other skips

src/server/routes/oembedArticleRoute.ts
Har irritert meg litt at vi returnerer 500 på /oembed dersom api returnerer 410
=> Return message according to status

src/containers/MyNdla/MyNdlaPage.tsx
Fixes NDLANO/Issues#4021
Min NDLA-brukere fra rogaland skal ha egen url under eksamen, med autentisering basert på datohash.
=> Use different ai-url for rogaland for exams

e2e/specs/unauthenticated/search.spec.ts, src/containers/SearchPage/SearchContainer.tsx, src/containers/SearchPage/SearchInnerPage.tsx, src/containers/SearchPage/components/SearchFilterContent.tsx, src/containers/SearchPage/components/SearchHeader.tsx, src/containers/SearchPage/components/SearchSubjectResult.tsx, src/containers/SearchPage/components/SubjectFilter.tsx, src/containers/SearchPage/components/searchTypes.ts
NB! Disser ikke like det som er i prod i dag.
* Filtre er flyttet fullstendig ut av søke-inputet. De ligger nå samme sted uavhengig av om man er på stor/liten skjerm. 
* Søke-input har endret utseende. Det er nå en "stock" Input-komponent med transparent bakgrunn. Vil vi at den skal være likere det den var før?
* Fag-resultater fyller ikke alltid lenger skjermen når det ikke er nok resultater til å fylle griden. 
* Ressurstype-filtrering er forenklet ganske drastisk. Det er nå bare en liste med knapper som wrapper til neste linje dersom det ikke har plass på en linje. Dette var før to ("tre") forskjellige komponenter: En fullverdig liste, en scrollbar liste og en modal.
=> Move some search components over from frontend-packages.

package.json, yarn.lock
Fikser to svakheter:
- https://security.snyk.io/vuln/SNYK-JS-SERIALIZEJAVASCRIPT-6147607
- https://security.snyk.io/vuln/SNYK-JS-GRAPHQL-5905181
=> Bump serialize-javascript & graphql versions

e2e/apiMocks/unauthenticated_server.spec.ts_That_invalid_urls_return_status_400.har, e2e/specs/unauthenticated/server.spec.ts, src/server/server.ts
Noen feil vil inneholde en statuskode vi kan returnere.
Feks så finner jeg en del "rare" url'er ifra prometheus metrikkene våre fra noen dårlige hackerangrep der vi returnerer 500.
- Returnerer fra feilen bare dersom statuskoden'en fra feilen er 400-599.
- Dette er det express gjør by default så tenkte det var smart oppførsel
- Catcher og returnerer en generisk feilmelding dersom errorRouten vår feiler
- Skjedde med de rare url'ene lokalt. Går ut i fra at det ikke skjer særlig ofte, men tenker det er lurt å fange de uansett.
=> Return status code from error if it exists

src/containers/SharedFolderPage/components/Folder.tsx, src/containers/SharedFolderPage/components/FolderResource.tsx, src/routeHelpers.tsx
Fixes https://github.com/NDLANO/Issues/issues/4035
...MEN; denne bør testes. ~~Jeg har ikke klart å gjenskape problemet som er beskrevet i https://trello.com/c/XOWL0aTf/836-minndla-delte-mapper-bug-forh%C3%A5ndsvising, og~~ jeg er egentlig tvilende til at å fjerne preview-endepunktet er svar på problemet (heller at det fikser et symptom på et annet problem eller noe som henger igjen). For å gjenskape feilen, har jeg:
1. Funnet ei delt mappe på en testbruker
2. Logget inn på en annen testbruker
3. Gått inn på lenka og trykket Kopier Mappe + lagret den (også i en mappe som heter Favoritter, for sikkerhets skyld)
4. Gått inn igjen i MinNDLA, åpnet delt mappe for Favoritter og valgt mappa som nettopp er kopiert i strukturen
Når jeg kopierer en mappe, lages vel egentlig en ny mappe hos meg med …
=> Removing usage of the preview endpoint

src/server/server.ts
Siden labelen ikke blir begrenset på antall paths vi har, men alle paths som finnes blir lablet så blir det litt tungt for prometheus.
Ref: https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels
=> Stop including path label for prometheus metrics

e2e/apiMock.ts
Vi har 2 flaky tester som ikke spiller på lag når testene kjøres lokalt headless. 
Playwright defaulter til baseurl når den åpner en page, men usikker på hvordan det håndteres om den det awaites til at den siden blir loadet. Ved å legge til at page automatisk loader `/` så fungerer alt samt. at vi har kontroll på at `/` er loadet før vi starter testene våre iallefall og at server er oppe å kjører.
=> Defaults to frontpage when creating a playwright page

src/containers/SubjectPage/components/SubjectTopic.tsx
Fixes NDLANO/Issues#4065
topicPath kan være tom (sjølv om det då sannsynligvis skyldes manglende data fra taksonomi), men skal peike på rot for kontekst som er subjectid.
=> Replace possible empty topicpath[0] with subjectid

src/server/server.ts, src/util/handleError.ts, src/util/logger.ts
- Legger til request path på logger på server siden.
- Setter opp logging til å være plaintext fremfor json
Tenkte det ville vært nyttig å ha med requestpathen i loggene for å enklere kunne reprodusere feil.
Personlig liker jeeg ikke json-feilmeldingene våre så veldig godt så jeg endret winston-saken til å logge plaintext istedet. Kan droppe og bare ha med requestPath i json objektet om andre har andre preferanser på json vs plaintext.
=> Request path logging & plaintext logging

src/iframe/embedIframeIndex.tsx, src/server/podcastRssFeed.ts, src/server/render/defaultRender.tsx, src/server/render/iframeArticleRender.tsx, src/server/render/iframeEmbedRender.tsx, src/server/routes/oembedArticleRoute.ts, src/server/routes/podcastFeedRoute.ts, src/server/server.ts, src/util/apiHelpers.ts, src/util/handleError.ts
Legger på litt mer info på graphql feilmeldinger i ndla-frontend og endrer levelet til `warn` dersom feilen svarte med statuskode < 500.
=> Add requestPath and other graphql context to graphql errors

src/containers/Page/Layout.tsx, src/containers/WelcomePage/Components/Programmes.tsx, src/containers/WelcomePage/WelcomePage.tsx
Dropper `FrontpageArticle` fullstendig. Tenker heller at vi kan tilpasse vanlig `Article` eller `OneColumn` til hva nå enn bredden på dette skal være. For at denne skal se riktig ut må noen oppdatere marginer for alle frontend-komponenter. Må med andre ord få inn ting som https://github.com/NDLANO/frontend-packages/pull/2390, samt at man må publisere og bumpe pakker igjen.
=> New frontpage

src/containers/ErrorPage/ErrorPage.tsx, src/containers/ErrorPage/__tests__/__snapshots__/ErrorPage-test.tsx.snap, src/containers/Page/Layout.tsx, src/containers/Page/components/Footer.tsx
Kom frem til at det var like greit å basere footeren på `OneColumn`, i og med at det er den faktiske sidestørrelsen vår. Konsekvensen av dette er at vi ikke lenger bruker `FooterBlock` fra frontend-packages. Den ville isåfall bare inneholdt et par linjer med css, som jeg ikke helt ser verdien i å ha i frontend-packages fremfor her.
=> New Footer

src/components/MyNdla/AddResourceToFolder.tsx, src/components/MyNdla/CopyFolder.tsx, src/containers/MyNdla/Arena/components/ArenaCategoryForm.tsx, src/containers/MyNdla/Arena/components/ArenaForm.tsx, src/containers/MyNdla/Arena/components/FlagPostModalContent.tsx, src/containers/MyNdla/Folders/components/FolderForm.tsx
Fjerner LoadingButton bruk, inntil videre er aria-label bare loading, syntes ikke det gir kjempemye verdi å la det være mer beskrivende .. men det kan oppdateres om noen er uenige
=> Remove LoadingButton usage

src/containers/AllSubjectsPage/AllSubjectsPage.tsx
Fixes https://github.com/NDLANO/Issues/issues/4101
Problemet var at `const [filter, _setFilter] = useState<string[]>(convertToArray(parse(location.search).filter) || [ACTIVE_SUBJECTS]);` aldri ble falsy (ingen filter betød at at convertToArray ville returnere `[undefined]` som er en truthy verdi). Har skrevet den marginalt om slik at den nå gjør det den skulle.
=> Fixing subject page filters

src/util/handleError.ts
Var visst en bug her med faktisk `Error` objekter :shrug: 
De oppfører seg visst litt annerledes enn vanlige objekter
=> Log `Error` type correctly

src/containers/AboutPage/AboutPageContent.tsx
Reverts NDLANO/ndla-frontend#1949
Oppdaget at dette brekker genereringen av brødsmulesti og navigering til Om ndla sider fra meny-drawer 😅 Tror vi skal se om vi finner en annen løsning på problemet!
Brødsmulesti ser man blir feil når man laster inn denne feks: https://ndla-frontend-master.vercel.app/about/jobb-hos-oss
Burde nok åpne det opprinnelige issuet igjen om denne tas inn!
=> Revert "Forsøk på å gjøre about-menyen mer robust."

src/containers/MyNdla/folderMutations.ts
Fixes NDLANO/Issues#4129
Gjør det slik at du får oppdatert cache ved kopiering av mappe.
Lager branches basert på både prod og test med denne commiten putta inn.
=> Handle existing as object and not array

src/components/MyNdla/ListResource.tsx
Ser ut som den skal midtstilles [figma](https://www.figma.com/design/E4Y9nwHcDVTETrEQFxf3bD/Components-2024?node-id=683-13669&m=dev)
Burde kanskje gjøre samme på `ListItem`? Den ser litt rart ut i Storybook når "List" er valgt og tittelen er ikke sentrert med resten av innhold @Jonas-C
=> fix resourceitem alignment

src/components/NavigationBox.tsx, src/components/Topic/Topic.tsx, src/containers/SubjectPage/SubjectContainer.tsx, src/containers/SubjectPage/components/SubjectTopic.tsx
Fixes https://trello.com/c/18ZSMXKy/22-lite-luft-mellom-emner-og-tittel-l%C3%A6ringsressurser
Vanskelig å ta stilling til alle mulige komposisjoner. Data-attributter ser ut til å være den greieste løsningen.
=> fix: properly pad each block in transportation pages

src/config.ts, src/util/DebugInMemoryCache.ts, src/util/apiHelpers.ts
Legger til `DEBUG_GRAPHQL_CACHE` flagget som tar i bruk den nye `DebugInMemoryCache`.
Alt den gjør er å logge warnings når man finner noe i cachen som mangler et felt.
Den er ikke perfekt så den blir nok litt støyete å ha enabled by default, men jeg tipper den er fin å ha når vi skal debugge hvorfor noe ikke hydreres riktig eller sånn
=> Add `DEBUG_GRAPHQL_CACHE` flag

src/components/MediaList/LicenseBylineDescriptionList.tsx, src/iframe/__tests__/__snapshots__/IframeArticlePage-test.tsx.snap
fikser: [trello](https://trello.com/c/JrMnMo0U/78-kulepunkt-har-ikke-innrykk-p%C3%A5-andre-linje-i-gjenbruksboks)
=> Fix lists license

src/server/routes/oembedArticleRoute.ts, src/util/apiHelpers.ts, src/util/error.ts, src/util/handleError.ts
Tidligere så ble dette til nestede-logger som så sånn her ut:
```json
{"message":{"level":"error","message":"hallo"}}
```
det ble slitsomt å lese og `ndla logs` slet naturligvis litt med det.
Denne fikser problemet :smile:
=> Provide more info with oembed error logs

src/components/Learningpath/LearningpathEmbed.tsx, src/components/Learningpath/LearningpathIframe.tsx
Fixes https://trello.com/c/59ktoriR/102-ene-steget-i-denne-l%C3%A6ringssteget-ser-litt-rart-ut-kanskje-det-er-noe-feil-med-selve-l%C3%A6ringsstien
This allows NDLA articles and embeds to control the height of the iframe, removing the need for an inner scroll bar
Other embeds rest can still use `ExternalEmbed`
=> fix: Reintroduce LearningpathIframe for ndla iframes. 

src/containers/Masthead/drawer/MastheadDrawer.tsx
https://trello.com/c/d9ssEtTv/91-mobilmeny-kollapser-hver-gang-man-pr%C3%B8ver-%C3%A5-g%C3%A5-opp-niv%C3%A5
Som en fiks på denne tenkte jeg at ettersom menyen uansett fyller hele skjermen på mobil så kan vi likegreit toggle closeOnInteractOutside propen 🤔
=> Prevent masthead drawer closing on mobile emulation when navigating

src/containers/Masthead/drawer/DrawerPortion.tsx, src/containers/Masthead/drawer/TopicMenu.tsx
=> Fix spacing in mobileview in MastheadDrawer

src/containers/FilmFrontpage/FilmSlideshow.tsx
Tar det tilbake sånn ca som det var før. Litt usikker på om dette faktisk leses opp i det hele tatt, da det ligger inne i en lenke som er `aria-hidden`. Sånn var det i gamle løsningen også.
=> fix: add back slideshow metadata

src/components/MyNdla/Folder.tsx, src/containers/MyNdla/components/SettingsMenu.tsx
Fixes https://trello.com/c/wwpJSG0v/137-feil-knappetype-og-tekstfarge-min-ndla-mapper
=> fix: update folder info text color. Use clear icon for settings menu

src/containers/MyNdla/Folders/components/FolderActionHooks.tsx
Focus handling when creating new folders is both hacky and difficult when on mobile. The dialog for folder creation is nested within another dialog we have no real control over. Furthermore, focus handling diverges between different browsers. Instead, redirect the user to the newly created folder.
Dette dropper egentlig bare hele fokus-debatten. Tror også dette på sikt vil sørge for at vi kan forenkle fokus-håndtering for alle andre meny-komponenter i Min NDLA.
Vet egentlig ikke helt hvem i NDLA dette må igjennom.
=> feat: redirect when creating a new folder

src/routes.tsx, src/server/contentSecurityPolicy.ts, src/server/server.ts
Fikser https://trello.com/c/t0ywLDVe/205-matomo-page-overlay
Bruker frame-ancestors i stedet for xFrameOptions. Dersom frameancestors er satt vil uansett nettlesere ignorere header.
For adresser med lti og -iframe i seg returneres '*' for å signalisere at alt er lov.
=> Replace frameguard with frameAncestors.

src/components/MyNdla/AddResourceToFolder.tsx
https://trello.com/c/MyxisYjy/101-beskjeden-om-at-ressursen-er-lagret-i-en-mappe-lenker-ikke-videre-til-mappen
Brukte bare standard styling for Safelink, mulig dette skal oppdateres (?)
=> Display link to folder in toast when resource is added to folder

src/components/MyNdla/BlockResource.tsx, src/components/MyNdla/Folder.tsx, src/components/MyNdla/ListResource.tsx
Fikser opp i:
https://trello.com/c/GPApTwlV/152-h2-bruk-b%C3%B8r-v%C3%A6re-lik-arena-mapper
https://trello.com/c/GYoYs5sZ/149-lenkene-i-nylig-m%C3%A5-ikke-v%C3%A6re-h2
https://trello.com/c/QNyLsC12/150-lenkemapper-m%C3%A5-ikke-v%C3%A6re-h2
https://trello.com/c/Jm9FbEiJ/144-tittel-klippes-p%C3%A5-min-ndla (går ut i fra at vi aldri ønsker lineClamp på title i ListResource)
=> Fix heading levels my ndla page + remove title lineClamp in ListResource

src/containers/MyNdla/Arena/components/ArenaListItem.tsx
Fikser opp i:
Rart vi ikke har lagt merke til dette før, vært sånn ganske lenge 😅
=> Fix weird arenaCard spacing

src/server/api.ts, src/util/apiHelpers.ts, src/util/error/NDLAApolloErrors.ts, src/util/error/NDLAError.ts, src/util/error/StatusError.ts, src/util/error/index.ts, src/util/handleError.ts
Oppdaget at det var en del errors som ikke er errors i test fremdeles.
Prøver å rette opp i det :smile: 
Lager `Error` typer for graphql feilene for å sende litt mer informasjon rundt :smile:
=> Improve loglevel handling of graphql-errors

src/containers/Resources/ResourceItem.tsx
releates to https://github.com/NDLANO/frontend-packages/pull/2536
fikser også siste bit av denne: https://trello.com/c/n0onxltl/83-uu-plassering-vises-kun-med-farge
=> Add/update current ListItem styling

src/components/Topic/Topic.tsx
Samme oppførsel som i artikkel-ingress, I guess
=> fix: do not hyphenate overflowed titles. Instead, overflow anywhere

src/components/Learningpath/Learningpath.tsx
Kjører introduksjon gjennom article-converter for å få riktige lister.
Fikser https://trello.com/c/KtWH0aPe/255-feil-p%C3%A5-listevisning-i-introduksjon-p%C3%A5-l%C3%A6ringsstier
=> fix: proper article styling for learningpath introduction

src/components/MyNdla/CopyFolder.tsx, src/components/MyNdla/CopyFolderModal.tsx, src/components/MyNdla/Folder.tsx, src/containers/MyNdla/Folders/components/FolderShareModalContent.tsx, src/containers/SharedFolderPage/components/SaveLink.tsx
Fixes https://trello.com/c/5tZVb69C/143-min-ndla-dialog-ved-del-mappe-klikkbar-lenke-til-siden-jeg-st%C3%A5r-p%C3%A5
=> fix: do not show link title when a folder is not meant to be interacted with

src/config.ts
Vi setter domain på feide_auth cookie for at ai.ndla.no skal kunne plukke den opp og bruke den for autentisering. Men når vi kjøre denne på vercel så settes denne til localhost, noko som gjør at setting av cookie feiler og innlogging ikkje godtas.
Dette gjør det mogeleg å sette feide_domain til vercel.app slik at innlogging skal fungere.
=> Make it possible to override feide domain for cookie

src/server/server.ts, src/util/sentry.ts
Disse feilene dukker opp _mye_ og jeg er rimelig sikker på at de er ufarlige (skjer pga adblockers og andre extensions).
Tror vi bare slutter å sende de til sentry i første omgang.
=> Reduce sentry errors

src/util/handleError.ts, src/util/sentry.ts
Dette er feil som 401,403,404,410 osv. Ting som ikke ville blitt logget som faktiske feil på server.
=> Stop sending informational errors to sentry

src/App.tsx, src/components/AuthenticationContext.tsx, src/containers/ErrorPage/ForbiddenPage.tsx, src/containers/MyNdla/Arena/AdminCheck.tsx, src/containers/MyNdla/Arena/ArenaAdminPage.tsx, src/containers/MyNdla/Arena/ArenaCheck.tsx, src/containers/MyNdla/Arena/ArenaFlagPage.tsx, src/containers/MyNdla/Arena/ArenaNotificationsPage.tsx, src/containers/MyNdla/Arena/ArenaPage.tsx, src/containers/MyNdla/Arena/ArenaSingleFlagPage.tsx, src/containers/MyNdla/Arena/ArenaUserListPage.tsx, src/containers/MyNdla/Arena/CategoryEditPage.tsx, src/containers/MyNdla/Arena/NewCategoryPage.tsx, src/containers/MyNdla/Arena/NewTopicPage.tsx, src/containers/MyNdla/Arena/PostsPage.tsx, src/containers/MyNdla/Arena/TopicPage.tsx, src/containers/MyNdla/LearningPath/LearningPathCheck.tsx, src/containers/MyNdla/LearningPath/LearningPathPage.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
Fant plutselig ut av at det gikk an å få tilgang til mer eller mindre alt i arena så lenge en var logget på. 
Er heller ikke så veldig fin av at man må skrive tilgangslogikk i hver eneste route. Dette splitter tilgangslogikken i arena inn i to blokker: admin og arena-tilgang. Konsekvensen av dette er at vi mister litt fleksibilitet rundt åpenhet, men det er nok verdt det.
Burde nok testes nøye.
=> Fix: arena access

package.json, src/server/api.ts, yarn.lock
Dette fungerte irriterende bra sammen med https://github.com/julianlam/nodebb-plugin-session-sharing
Må berre sette prop-navn i settings på session-sharing plugin
=> Sets cookie that nodebb should recognize

src/containers/ResourcePage/ResourcePage.tsx, src/containers/Resources/ResourceItem.tsx, src/containers/SubjectPage/components/TopicWrapper.tsx, src/util/handleError.ts
Dette gjør at vi ikke lenger viser feilmelding dersom en av ressursene i en topic resulterer i en 403.
(Med mindre det er den du står på).
Forhåpentligvis så skal det ikke skje så ofte, men vi er nok litt utsatte med læringsstier siden de endrer status ved redigering(?)
Kan testes her: http://localhost:3000/subject:20/topic:1:194565/resource:1:179880?disableSSR=true
Og her: http://localhost:3000/subject:20/topic:1:194565/?disableSSR=true
=> Handle recoverable errors on `ResourcePage` and `TopicWrapper`

src/components/AuthenticationContext.tsx
Noe `noen ⬆️` har laget for lenge siden som var i bruk eller mest sannsynlig ikke blitt brukt utenom testing? 🌡️ 
Så ingen bruksområder av metodene 👯
=> Removed unused authcontext methods

package.json, src/containers/MyNdla/Arena/components/FlagCard.tsx, src/containers/MyNdla/Arena/components/FlaggedPostCard.tsx, src/containers/MyNdla/Arena/components/MainPostCard.tsx, src/containers/MyNdla/Arena/components/PostCard.tsx, src/containers/MyNdla/MyNdlaPage.tsx, src/containers/MyNdla/components/NotificationList.tsx, src/i18n.ts, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts, src/util/__tests__/formatDate-test.ts, src/util/formatDate.ts, yarn.lock
Fikser en hydrerings feil på https://test.ndla.no/about/utlysninger
Kan testes lokalt med `TZ="UTC" yarn start`
Ideelt sett så burde vi sikkert droppet serverside rendering for alle datoer (eller i alle fall gjort en oppdatering på klient om tidssonen er forskjellig), men kanskje litt for mye hassle?
=> Use CET timezone when rendering timezones

src/components/Scripts/Formbricks.tsx
Fixes https://ndlano.sentry.io/issues/9619584/events/43c59c94e2874c788f992c30f56b6e46/?project=4508018776735824
Jeg klarer ikke reprodusere denne feilen (Ser ut som det er en safari-only feil også), så er litt vanskelig å vite om den er fiksa.
=> Attempt to fix formbricks init error

src/components/MyNdla/AddResourceToFolder.tsx
Regelen var skrudd av før, men den er egentlig fin. Forteller oss bare om tilfeller der vi f.eks kan ende opp med `text}` i DOM
=> chore: put quotes inside template string to be more explicit about intent

src/server/api.ts, src/server/server.ts
Denne kræsjet tidligere fordi `next("route")` rutet til errorhandleren med litt rare parametere
Hvem prøvde å si at typescript var typesikkert :nerd_face: 
Kan testes ved å se at rare url'er ikke kræsjer applikasjonen.
Feks http://localhost:3000/nb/subject:7509b507-548d-48e1-bef3-a06758e4820c/topic:e387b5d7-62c1-4a14-82d1-999beb95e926/topic:120cf233-a240-44e6-b9ff-651ff97369da/7509b507-548d-48e1-bef3-a06758e4820c/topic:e387b5d7-62c1-4a14-82d1-999beb95e926
=> Fix crashing express error handler

src/containers/Masthead/components/MastheadSearch.tsx, src/containers/SearchPage/components/SearchHeader.tsx
Fikser https://trello.com/c/TO7O1Wkw/1148-hermetegn-blir-quot-i-s%C3%B8k
i18next escaper automatisk quotes. Utnytter oppbyggningen av oversettelsen til å droppe å sende inn query som et parameter, og legger det heller til på slutten av oversettelsesstrengen. Da slipper vi å skru av escaping i i18next.
=> fix: properly render quotes in missing results text

src/components/Learningpath/LastLearningpathStepInfo.tsx
Fixes https://ndlano.sentry.io/issues/12881342/?project=4508018776735824&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=12
=> fix: only show resources if both parent and root exists

src/server/render/defaultRender.tsx
La merke til at dette ikke funket helt som det skulle. `test.ndla.no/en` med locale satt som "nb" redirecter kun på klient, og ikke på server.
=> fix: redirect to correct locale server-side

e2e/specs/authenticated/MyNDLAMenu.spec.ts, src/server/routes/__tests__/__snapshots__/oembedArticleRoute-test.ts.snap, src/server/routes/__tests__/oembedArticleRoute-test.ts, src/server/routes/oembedArticleRoute.ts, src/statusCodes.ts
Fant mange innslag av henting av artikkel med id undefined. Det er fordi oembed-endepunktet om kalla med en kontekst som er læringssti returnerer iframe-url med undefined i seg.
Eks
```
{"type":"rich","version":"1.0","height":480,"width":854,"title":"Ein enkel veg til heilt grei nynorsk","html":"<iframe aria-label=\"Ein enkel veg til heilt grei nynorsk\" src=\"https://ndla.no/article-iframe/nb/urn:resource:2937bdb1-564f-4352-be34-512bcfeff644/undefined\" height=\"480\" width=\"854\" frameborder=\"0\" allowFullscreen=\"\" />"}
```
=> Add error on learningpath oembed

src/routes.tsx, src/util/urlHelper.ts
Fikser 400-feil ved oembedkall på https://ndla.no/oembed?url=https://ndla.no/subjects/nn/subject:3d9454e8-460e-42c7-8f28-71663fbbf6e6/topic:ff48ed85-dbc5-4b98-a3b2-4212fd341c1a/topic:07a16836-8498-478e-a718-ece26ea52c3f/resource:1:186293
Siden vi godtar adressa i frontend burde vi godta den via oembed
=> Handles oembeds better

src/containers/Page/Layout.tsx
Sørger for at vi ikke faller tilbake til default description, som førte til at vi rendret to meta-tags på de fleste sider. Dette vil nok føre til at det er noen sider som ikke har description, spesielt innenfor Min NDLA. Er det problematisk?
=> fix: do not insert two description tags

src/components/Learningpath/Learningpath.tsx
Bakgrunnen til læringsstier fylte ikke siden lenger.
[test.ndla.no/learningpaths/3393/steps/19708](test.ndla.no)
/learningpaths/3393/steps/19708 på instansen for å se løsningen
=> Added height to styledpagecontainer learningpath

src/containers/MyNdla/Learningpath/components/ExternalForm.tsx
Fikser opp i en kommentar jeg hadde på en annen PR:
> Ikke direkte relatert til denne, så det kan sikkert gjøres i egen PR, men vi burde kanskje sjekke at url er på riktig format før vi sender av gårde requesten i formen for å legge til innhold fra et annet nettsted? Får veldig mange "Invalid URL"- feil fra gql hvis man prøver å skrive noe i input-feltet
=> External learningpath step form: Validate url before triggering request

src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
Syntes forsåvidt det er litt dumt at vi har helt like keys i ndla-frontend og i frontend-packages, fort gjort at noe blir feil 😅
=> Remove unused duplicate translation

src/containers/AboutPage/AboutPageContent.tsx
Dette er en reversering av denne: https://github.com/NDLANO/ndla-frontend/pull/2334/files#diff-7931196238d57c50b5d545aa690b836511c19be71364e0bee0f589250dd46925 for å fikse at footeren overflower på om-ndla-sider nå!
Vet ikke om dette brekker noe av parallax oppførselen? @gunnarvelle
=> Reintroduce overflowX: 'hidden' to prevent page overflow

src/containers/Resources/Resources.tsx
Monsido klager på at vi må gi mer info om switchen da den ligger i et form. Tenker vi fikser problemet ved å slette form-elementet.
=> fix: do not wrap switch in form

src/containers/MyNdla/Learningpath/EditLearningpathStepsPageContent.tsx, src/containers/MyNdla/Learningpath/EditLearningpathTitlePage.tsx, src/containers/MyNdla/Learningpath/PreviewLearningpathPage.tsx, src/containers/MyNdla/Learningpath/components/LearningpathStepListItem.tsx, src/containers/MyNdla/Learningpath/components/TitleForm.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
Hedvig ville helst at kun et skjema skulle være åpent om gangen.
Endrer fargen på neste knapp til secondary.
=> Kun et skjema åpent omgangen!

src/server/getManifestChunks.tsx, vite.config.ts
Our css is atomic, and our component library is used throughout the app. We'll probably save a couple of KB by not splitting it across chunks. This can (and maybe should) be revised at a later point, once we can start chunking by endpoint
=> chore: do not split css into chunks.

src/components/MediaList/MediaList.tsx
Fixes https://trello.com/c/keAmeaVD/1283-lenker-i-kildefelt-skal-ikke-v%C3%A6re-klikkbare
Kommer ikke på noen andre felter som kan være lenker sånn i farta.
=> fix: do not render source/origin links

src/containers/FilmFrontpage/AllMoviesAlphabetically.tsx, src/containers/FilmFrontpage/MovieGrid.tsx, src/containers/Masthead/components/MastheadSearch.tsx, src/containers/MyNdla/Learningpath/components/ResourcePicker.tsx, src/containers/TopicPage/MovedTopicPage.tsx, src/graphqlTypes.ts, src/queries.ts, src/schema.graphql, src/util/apiHelpers.ts
Unions og interfaces er ordentlig rotete i GQL. Avhengig av https://github.com/NDLANO/graphql-api/pull/559
=> refactor: support node search results

package.json, src/containers/MyNdla/Folders/components/DraggableFolder.tsx, src/containers/MyNdla/Folders/components/DraggableResource.tsx, src/containers/MyNdla/Folders/components/FolderList.tsx, src/containers/MyNdla/Folders/components/ResourceList.tsx, src/containers/MyNdla/Folders/util.ts, src/containers/MyNdla/Learningpath/EditLearningpathStepsPageContent.tsx, src/containers/MyNdla/Learningpath/components/DraggableLearningpathStepListItem.tsx, src/containers/MyNdla/Learningpath/components/DraggableListItem.tsx, src/containers/MyNdla/Learningpath/learningpathMutations.ts, src/containers/MyNdla/components/DragHandle.tsx, src/containers/MyNdla/dndUtil.tsx, src/graphqlTypes.ts, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts, src/schema.graphql, yarn.lock
del 2 av https://trello.com/c/GhgD0gyH/1291-drag-and-drop-p%C3%A5-steg-i-l%C3%A6ringssti
fixes https://github.com/NDLANO/Issues/issues/4307
depends on https://github.com/NDLANO/graphql-api/pull/561
=> Implement dnd for learningpath steps

src/components/Learningpath/components/ExternalStep.tsx, src/components/Learningpath/components/LearningpathStep.tsx
Om du legger inn en url som feiler i opengraph så vises ikkje eksternt steg. Dette fikser det.
Eks: http://localhost:3000/nb/minndla/learningpaths/3538/preview/20137 som frank_foreleser
=> Show external step even if opengraph fails

src/containers/MyNdla/Learningpath/components/DraggableLearningpathStepListItem.tsx, src/containers/MyNdla/Learningpath/learningpathMutations.ts
Oppdaterer cache når man endrer rekkefølge på læringsstisteg! Resetter også valgt steg når man sletter et steg
=> Update cache on changed learningpath step order

src/server/routes/oembedArticleRoute.ts, src/util/__tests__/urlHelper-test.ts, src/util/urlHelper.ts
Litt kjipere logikk, men løsriver oss fra funksjonalitet som ikke støttes i react router 7
=> refactor: do not rely on matchPath for old subject paths

src/containers/Masthead/components/MastheadSearch.tsx, src/containers/SearchPage/SubjectFilter.tsx
I dag vises emner som Fagstoff. Dette fikser det, samt legger inn fag i lista.
=> Enable search for nodes in masthead. Show correct resourcetype.

src/mutations/learningpathMutations.ts
Hvis man sletter et læringsstisteg  så kan man nå redigere andre steg etterpå
=> Update revision in cache when step is deleted

src/containers/FilmFrontpage/AllMoviesAlphabetically.tsx, src/containers/FilmFrontpage/MovieGrid.tsx
Vi viser ikkje filmkategorier sortert. Og av og til kjem det duplikater på a-å lista. Ser ut som om dette hadde noe å sei.
=> Adds sort param to avoid duplicates (maybe)

e2e/apiMock.ts, e2e/specs/authenticated/MyNDLAFolder.spec.ts, e2e/specs/authenticated/MyNDLAMenu.spec.ts, e2e/specs/unauthenticated/frontpage.spec.ts, e2e/specs/unauthenticated/iframe.spec.ts, e2e/specs/unauthenticated/multidisciplinary.spec.ts, e2e/specs/unauthenticated/search.spec.ts, e2e/specs/unauthenticated/subjects.spec.ts, e2e/specs/unauthenticated/toolbox.spec.ts, e2e/specs/unauthenticated/topic.spec.ts, e2e/specs/unauthenticated/topicMenu.spec.ts, e2e/utils.ts
Flytter litt util metoder ut i en util fil for å filen litt ryddigere, refaktorer navnene for å bli mer tydigere. 
Gjør om `mockWaitResponse` til å bli `waitGraphql` for å kunne ta den i bruk gjennom test metoden istedenfor.
=> Opprydning i playwright extension.

src/util/error/NDLAApolloErrors.ts, src/util/handleError.ts, src/util/sentry.ts
Akkurat graphql feil vil nok være litt klønete uansett siden stacktracene ikke er fra der queryen er (wtf apollo)
men vi vil i alle fall få med samme type kontekster som i loggene:
=> feat: send more error context data to sentry

Dockerfile
Nye alpine versjonen lar oss ikke installere pakker globalt uten et flagg.
Siden det _egentlig_ ikke er anbefalt så kan vi kanskje bare bruke den i repoene :nerd_face: 
noen som vet om vi bruker denne pakken til noe annet enn det som er i `run-ndla-frontend.sh`?
Kanskje vi bare kunne droppet hele greia?
=> fix: install awscli from `apk` rather than `pip`

src/containers/MyNdla/Learningpath/EditLearningpathStepsPage.tsx, src/containers/MyNdla/Learningpath/EditLearningpathTitlePage.tsx, src/containers/MyNdla/Learningpath/PreviewLearningpathPage.tsx, src/containers/MyNdla/Learningpath/SaveLearningpathPage.tsx, src/fragments/learningpathFragments.ts, src/graphqlTypes.ts
Bare en visuell bug. Kan teste ved å dele en læringssti fra en bruker, logge inn på en annen og lime inn redigeringslenke til stien du delte. F.eks http://localhost:3000/nb/minndla/learningpaths/3394/edit/title på alle andre brukere enn Daniel.
=> fix: do not show edit form when accessing a shared learningpath you do not own

src/components/Learningpath/components/LearningpathStep.tsx
Avoid showing learning path title in different box if possible.
Fixes https://github.com/ndlano/issues/issues/4347
Ser ut som at dette er to forskjellige bugs egentlig. Den ene ble innført når vi ikke lenger krevde ingress, den andre ble innført i https://github.com/NDLANO/ndla-frontend/pull/2450. 
Det er klin umulig å vite helt sikkert om et steg er et tekststeg fra læringsstier i Min NDLA, eller om det er et rent tekststeg som er opprettet i stier. Blir derfor litt gjetning på hvordan vi skal velge riktig visning.
=> fix: properly display learning path steps when ingress is undefined.

src/containers/Masthead/components/MastheadSearch.tsx, src/containers/SearchPage/SearchContainer.tsx
Tror dette er en bug i react router!
=> fix: encode and decode query parameter to avoid converting whitespace to plus sign

src/components/MyNdla/TreeStructure.tsx
Fikser problem rapportert i trello.
=> fix: update `newFolderParentId` when selection is changed

src/containers/TopicPage/TopicPage.tsx, src/server/routes/oembedArticleRoute.ts, src/util/error/index.ts, src/util/handleError.ts
Passer på at vi ikke kan sende inn ikke-feil til `handleError`.
Har sett en del av disse i loggene:
```json
{
"level": "error",
"message": "Unknown error: undefined",
"service": "ndla-frontend",
"timestamp": "2025-05-16T06:25:18.818Z"
}
```
mistenker at det ikke er faktiske feil, men bare vi som logger litt mye når vi får 404 eller manglende data.
=> Improve exception logging

src/iframe/embedIframeIndex.tsx, src/server/podcastRssFeed.ts, src/server/render/defaultRender.tsx, src/server/render/iframeArticleRender.tsx, src/server/render/iframeEmbedRender.tsx, src/server/routes/oembedArticleRoute.ts, src/util/urlHelper.ts
Tidligere så kræsjet vi med 500 dersom oembed ruten fikk en ikke-gyldig oembed url.
Legger også til query parametere til `requestPath` i loggene.
=> fix: return 400 if `/oembed` gets non-valid url

src/containers/Masthead/MastheadMenu.tsx
Fixes https://trello.com/c/evZcw8c4/1396-menyen-klikker-jeg-p%C3%A5-min-ndla-i-menyen-uten-%C3%A5-v%C3%A6re-innlogget-blir-jeg-sendt-gjennom-innlogging-via-feide-men-s%C3%A5-tilbake-til-for
=> fix: redirect to my ndla when logging in from menu

src/containers/ResourceEmbed/AudioPage.tsx, src/containers/ResourceEmbed/ConceptPage.tsx, src/containers/ResourceEmbed/ImagePage.tsx
Fixes https://github.com/NDLANO/Issues/issues/4385.
Tror Brightcove alltid er numerisk?
=> fix: return 404 for non-numeric embed id

src/Document.tsx, src/client.tsx, src/containers/ErrorPage/ErrorEntry.tsx, src/i18n.ts, src/iframe/embedIframeIndex.tsx, src/iframe/index.tsx, src/interfaces.ts, src/lti/index.tsx, src/server/api.ts, src/server/locales/locales.ts, src/server/render/defaultRender.tsx, src/server/render/errorRender.tsx, src/server/render/iframeArticleRender.tsx, src/server/render/iframeEmbedRender.tsx, src/server/render/ltiRender.tsx
Oversettelsene våre ble tidligere lagt inn i en chunk, som automatisk håndterte cache-busting for oss når chunken endret seg. Det er ikke tilfellet lenger. Hasher innholdet i oversettelses-filene, slik at vi automatisk invaliderer de i cachen når de endrer seg.
=> fix: cache bust translation files
