NDLANO/ndla-frontend

server/server.js
Commoncraft embedder fast.wistia.com
https://ndla-frontend.staging.api.ndla.no/article/163
=> Adds fast.wistia.com to csp for commoncraft

package.json, src/components/Article.jsx, src/phrases/phrases-nb.js, yarn.lock
See also https://github.com/NDLANO/frontend-packages/pull/118
=> Remove writtenby-message

package.json, server/routes/defaultRoute.js, src/components/license/LicenseBox.jsx, src/components/license/TextLicenseList.jsx, src/containers/Resources/Resources.jsx, src/phrases/phrases-en.js, src/phrases/phrases-nb.js, yarn.lock
* Fixes ssr issue with locale in url
* Fixes ssr of ndla-tabs
* New ResourceGroup messages
=> Bump ndla packages

src/components/Article.jsx, src/iframe/IframeArticlePage.js, src/iframe/__tests__/__snapshots__/IframeArticlePage-test.js.snap
Fixes large spacing on narrow screens:
=> Fix narrow screen spacing

.gitignore, src/containers/PlainArticlePage/PlainArticlePage.jsx, src/util/transformArticle.js
Resolves: https://trello.com/c/mi6yhfxV/515-feil-ved-datovisning-for-videoressurser
=> #919 - Added missing transform to PlainArticlePage

package.json, src/server/helpers/Document.js, src/server/routes/defaultRoute.js, src/server/routes/iframeArticleRoute.js, yarn.lock
Resolves: 
- https://trello.com/c/z54HvN58/528-menyknapp-responderer-ikke-i-ie11
- https://trello.com/c/pmbrgGac/530-launcher-vises-ikke-i-ie11
=> Adds useragent, loads babel-polyfill if IE family

src/server/contentSecurityPolicy.js
Resolves: https://github.com/NDLANO/Issues/issues/996
=> Improved csp fix for vg.no

src/containers/Masthead/MastheadContainer.jsx, src/containers/TopicPage/TopicPage.jsx, src/phrases/phrases-en.js, src/phrases/phrases-nb.js, src/phrases/phrases-nn.js, src/queries.js
Tests:
* Topic page shows «Sist oppdatert» date in norwegian format
* Make sure NRK viedo is display in the «Sosiale medier i folkets tjeneste» resource
=> Minor bug fixes

src/server/robots.txt, src/server/server.js
Resolves https://github.com/NDLANO/Issues/issues/1149
May require additional options? https://expressjs.com/en/api.html#res.sendFile
=> Serving ndla.no robots.txt with own additions

src/components/ZendeskButton.jsx, src/queries.js
=> Graphql server caching

src/containers/ArticlePage/components/ArticleErrorMessage.jsx, src/containers/SubjectsPage/SubjectsPage.jsx, src/containers/TopicPage/components/TopicsPageErrorMessage.jsx
=> fix: gif path typo

src/containers/SubjectPage/SubjectPage.jsx
=> Removes loading check

src/containers/WelcomePage/WelcomePageInfo.jsx
Resolves https://github.com/NDLANO/Issues/issues/1198
=> fix: correct link prop for component

e2e/integration/topic_menu_spec.js, src/phrases/phrases-en.js, src/phrases/phrases-nb.js, src/phrases/phrases-nn.js
=> phrases updates

.prettierignore, src/queries.js
Fixes: https://trello.com/c/Kybnkt9Q/679-feil-visning-av-emner-p%C3%A5-fagforsider
=> Fix topic apollo cache bug

e2e/support/index.js, src/util/apiHelpers.js
=> Change token handling

src/containers/Resources/resourceHelpers.js, src/containers/SubjectPage/components/SubjectEditorChoices.jsx
=> fix: Handling of resources with missing contentUri

src/containers/SearchPage/SearchContainer.jsx, src/containers/SearchPage/__tests__/searchSelectors-test.js, src/containers/SearchPage/searchSelectors.js
Select context based on selected filter. If more than one subjects are selected the first one is used.
=> Ndlano/issues#1238 søk kontekst

yarn.lock
=> Fix module loading exception in embed bundle

src/constants.js, src/containers/WelcomePage/FrontpageSubjects.jsx, src/containers/WelcomePage/__tests__/FrontendSubjectsProduction-test.js, src/routeHelpers.jsx, src/server/routes/__tests__/forwardingRoute-test.js, src/server/routes/forwardingRoute.js
=> Subject allow list

src/containers/Resources/__tests__/getResourceGroups-test.js, src/containers/Resources/getResourceGroups.js
=> Filter out duplicate supplementary resources

src/server/contentSecurityPolicy.js
New embeds for naturfag. Links to NDLANO/issues#1508
=> Added new embeds

src/containers/SearchPage/searchHelpers.js
Fix to correctly show links to all search result contexts
=> Show all search result contexts

.gitignore, src/containers/ArticlePage/ArticlePage.jsx, src/containers/Masthead/MastheadContainer.jsx, src/containers/TopicPage/TopicPage.jsx, src/gqlSchema.json, src/queries.js
Depends on https://github.com/NDLANO/graphql-api/pull/33
=> Add subject id to resources queries

src/containers/TopicPage/TopicPage.jsx
=> Fix TopicPage hydration issue

src/containers/SubjectPage/components/SubjectPageTopics.jsx
Connects to NDLAND/issues#1492
Hides both from subjectpage and menu.
=> Hide filters when ony one

src/containers/ArticlePage/ArticlePage.jsx, src/gqlSchema.json, src/queries.js
Connects to NDLANO/issues#1574
=> Added filters from url to query

run-ndla-frontend.sh, src/config.js
connects to NDLANO/Issues#1545
=> #1545: Handle environment with underscore in name

src/containers/Masthead/components/MastheadTopics.jsx
=> Fix resource link in topic menu

src/containers/Masthead/components/MastheadTopics.jsx, src/containers/Masthead/components/__tests__/MastheadTopics-test.js, src/containers/Masthead/mastheadHelpers.js
=> Fix topic path in menu

.travis.yml
=> Update travis secret

src/containers/ArticlePage/ArticlePage.jsx, src/containers/Masthead/MastheadContainer.jsx, src/gqlSchema.json, src/queries.js
Depends on NDLANO/graphql-api/pull/44
=> Add subjectid as parameter to ensure context

src/config.js, src/server/routes/__tests__/__snapshots__/ltiRoute-test.js.snap, src/server/routes/__tests__/__snapshots__/oembedArticleRoute-test.js.snap, src/server/routes/ltiRoute.js
=> Added possible values

src/client.jsx, src/containers/TopicPage/TopicPage.jsx, src/server/routes/defaultRoute.js
Fixes bug where document crashed the server side rendering. Fixed with already existing config variables and passing down basename.
=> Fixes crash with document

src/App.js, src/components/SocialMediaMetadata.jsx, src/components/__tests__/__snapshots__/getAlternateLanguages-test.js.snap, src/components/__tests__/getAlternateLanguages-test.js, src/containers/ArticlePage/ArticlePage.jsx, src/containers/PlainArticlePage/PlainArticlePage.jsx, src/containers/TopicPage/TopicPage.jsx, src/containers/WelcomePage/WelcomePage.jsx, src/iframe/IframeArticlePage.js, src/shapes.js
=> Adds basename to context api. Fixes problem with alternate links in meta

src/containers/FilmFrontpage/NdlaFilmFrontpage.jsx, src/queries.js
Connects to NDLANO/Issues#1783
=> Contexter ndlafilm

package.json, src/containers/ErrorPage/ErrorPage.js, src/containers/ErrorPage/__tests__/ErrorPage-test.js, src/containers/ErrorPage/__tests__/__snapshots__/ErrorPage-test.js.snap, src/containers/FilmFrontpage/NdlaFilmFrontpage.jsx, src/containers/Page/components/Footer.jsx, src/queries.js, src/server/routes/errorRoute.js, yarn.lock
Hent ut korrekt versjon av about for filmforside.
=> Uses correct about text.

e2e/integration/subjects_page_spec.js, e2e/integration/topic_menu_spec.js, e2e/integration/topic_page_spec.js, package.json, src/containers/WelcomePage/WelcomePageInfo.jsx, yarn.lock
Endrer navn på kategori på forsida.
=> Change name

package.json, src/components/Learningpath/Learningpath.jsx, src/containers/ArticlePage/ArticlePage.jsx, src/containers/FilmFrontpage/MoreAboutNdlaFilm.jsx, src/containers/FilmFrontpage/NdlaFilmFrontpage.jsx, src/containers/LearningpathPage/LearningpathPage.jsx, src/containers/Masthead/MastheadContainer.jsx, src/containers/PlainArticlePage/PlainArticlePage.jsx, src/containers/PlainLearningpathPage/PlainLearningpathPage.jsx, src/containers/Resources/Resources.jsx, src/containers/SearchPage/SearchPage.jsx, src/containers/SubjectPage/SubjectPage.jsx, src/containers/SubjectPage/components/layout/SubjectPageDouble.jsx, src/containers/SubjectPage/components/layout/SubjectPageSingle.jsx, src/containers/SubjectsPage/SubjectsPage.jsx, src/containers/TopicPage/SubTopics.jsx, src/containers/TopicPage/TopicPage.jsx, src/iframe/IframeArticlePage.js, yarn.lock
=> Remove redux and reselect, remove compose calls

src/containers/SearchPage/components/SearchFilters.jsx
Trello: https://trello.com/c/q26RMtpe/232-spr%C3%A5kboks-i-s%C3%B8k-forvirrende
=> Removed language-search-filter from search-page

package.json, src/containers/ErrorPage/__tests__/__snapshots__/ErrorPage-test.js.snap, src/containers/Page/components/Footer.jsx, yarn.lock
IMPORTANT: Dependent on PR in frontend-packages: https://github.com/NDLANO/frontend-packages/pull/544/
=> Added link to youtube in footer

package.json, src/containers/Page/components/Footer.jsx, yarn.lock
La til footerSocialMediaLinksYoutube på nn/nb/en.
Frontend-packages oppdatert med oversettingar.
henger saman med https://github.com/NDLANO/frontend-packages/pull/550
=> La til footerSocialMediaLinksYoutube på nn/nb/en.

src/components/license/H5pLicenseList.jsx
=> Use h5p-icon

src/components/SocialMediaMetadata.jsx, src/containers/ArticlePage/ArticlePage.jsx, src/containers/LearningpathPage/LearningpathPage.jsx, src/containers/PlainArticlePage/PlainArticlePage.jsx, src/containers/SubjectPage/SubjectPage.jsx, src/containers/TopicPage/TopicPage.jsx, src/iframe/IframeArticlePage.js, src/iframe/IframeTopicPage.jsx, src/shapes.js
And adds optional chaining to simplify code.
=> Use correct metaimage

package.json, yarn.lock
Denne er fiksa så då kan vi ta i bruk siste helmet og helmet-csp.
https://github.com/helmetjs/csp/issues/89
=> Bump helmet

src/gqlSchema.json, src/util/apiHelpers.js
Fikser caching av søkeresultat med samme id og type.
Avhenger av NDLANO/graphql-api/pull/87
=> Updated graphqlschema and fix for searchresults

package.json, src/components/Article/Article.js, src/iframe/__tests__/__snapshots__/IframeArticlePage-test.js.snap, yarn.lock
Legger til rendering av markdown for artikkelingress. Avhenger av NDLANO/frontend-packages/pull/587
=> Added markdown render to ndla-frontend

package.json, src/config.js, src/constants.js, src/containers/Masthead/MastheadContainer.jsx, src/containers/ResourcePage/ResourcePage.jsx, src/containers/SubjectPage/SubjectPage.jsx, src/containers/TopicPage/TopicPage.jsx, src/routes.jsx, src/server/server.js, yarn.lock
Fixes NDLANO/Issues#2032
Fixes NDLANO/Issues#2057
=> Redirect to 404 for all unknown adresses

src/containers/SearchPage/SearchPage.jsx, src/containers/SearchPage/__tests__/__snapshots__/searchHelpers-test.js.snap, src/containers/SearchPage/searchHelpers.js
Fixes NDLANO/Issues#2069
Bruker locale som søkeparamter på søkesida
=> Searches with locale

src/containers/SearchPage/components/SearchFilters.jsx
Fixes NDLANO/Issues#2083
2083 fikses her. Trenger ikke gjøre noe i frontend-packages.
=> Filter on id instead of name

src/containers/TopicPage/TopicContainer.jsx, src/containers/TopicPage/TopicPage.jsx
Fixes NDLANO/Issues#2092
Tror denne skal fikse tracking for topic. Fra koden set det ut som om det er samme problem i SubjectPage og PlainLearningpathPage så vi bør sjekke om tracking fungerer der.
Det er en del kode relatert getInitialProps() i App og defaultRoute som jeg tror kan fjernes etter #424, men har ikke rørt noe der.
=> 2092 topic page tracking

src/containers/SubjectPage/SubjectContainer.jsx
=> Remove twitter from subject page

src/components/Article/Article.js
NDLANO/Issues#2141
Support linebreak -> br
=> Added breaks-parameter in markdown

src/config.js, src/containers/FilmFrontpage/NdlaFilmFrontpage.jsx
Depends on NDLANO/deploy/pull/249
=> use env variable to select article type

src/constants.js
Salg service reiseliv Vg1 lenken i menyen hadde feil subject-id
=> Fixed wrong subject-id on subject in menu

package.json, src/components/license/LicenseBox.jsx, src/components/license/OembedItem.jsx, src/containers/ResourcePage/ResourcePage.jsx, src/containers/SubjectPage/SubjectPage.jsx, src/containers/TopicPage/TopicPage.jsx, src/gqlSchema.json, src/iframe/__tests__/__snapshots__/IframeArticlePage-test.js.snap, src/queries.js, src/util/transformArticle.js, yarn.lock
Fixes NDLANO/Issues#2164
Depending on NDLANO/graphql-api/pull/100
=> 2164 oembed link

src/containers/Masthead/MastheadContainer.jsx, src/containers/Masthead/components/MastheadSearch.jsx
Fixes https://github.com/NDLANO/Issues/issues/2159
- Added useEffect on searchfield to force rerender if subjectId changes
=> Added useEffect to rerender searchField

src/containers/ResourcePage/ResourcePage.jsx, src/queries.js
Fixes NDLANO/Issues#2185
Viser 404-side dersom det åpnes en ressurs som ikkje finnes i det faget/emnet.
=> Show NotFoundPage when location not in paths

src/gqlSchema.json, src/queries.js
NDLANO/Issues#2186
Uses new fields from graphql to fetch suggestions in search.
=> Added fetching suggestions

src/server/contentSecurityPolicy.js
=> Added support for molview embeds

src/constants.js
Fikser https://trello.com/c/rhOFxLoH/592-fjerne-i-arbeid-fra-forsida
=> Remove beta-tag from subjects

src/constants.js
Elektrofag Vg1 -> Elektro og datateknologi Vg1
Teknikk og industriell produksjon Vg1 ->  Teknologi- og industrifag Vg1
=> Oppdaterer namna i meny slik at dei er korrekte

src/gqlSchema.json, src/queries.js
NDLANO/Issues#2204
Depends on NDLANO/search-api/pull/111 and NDLANO/graphql-api/pull/106
=> Fetch traits

src/components/Article/CompetenceGoals.jsx
=> Hide empty competence goal tabs

src/containers/ArticlePage/ArticlePage.jsx, src/containers/ArticlePage/components/ArticleHero.jsx, src/containers/Masthead/components/MastheadTopics.jsx, src/routeHelpers.jsx
Fjerner også filtervalg fra meny og legger på filter på lenke til fagforside.
=> Bruker filternavn i stedet for fagnavn dersom det er valgt.

package.json, src/containers/MovedResourcePage/MovedResourcePage.jsx, src/containers/ResourcePage/ResourcePage.jsx, yarn.lock
Fixes NDLANO/Issues#2229
Depends on https://github.com/NDLANO/frontend-packages/pull/672
=> 2229 links to moved resources

package.json, src/containers/SearchPage/searchHelpers.js, src/gqlSchema.json, src/queries.js, yarn.lock
Depends on https://github.com/NDLANO/search-api/pull/117 and https://github.com/NDLANO/graphql-api/pull/112
Viser søkeresultat med filter fra kontekst. Viser også longname fra filter på treff i andre fag.
=> Add filter to url and show longname in contexts

src/containers/ResourcePage/ResourcePage.jsx, src/containers/SubjectPage/SubjectPage.jsx
=> Add filter to url

src/containers/LearningpathPage/LearningpathPage.jsx
=> Fix learningpath math

src/components/Article/ArticleContents.jsx, src/containers/SubjectPage/components/MainTopic.jsx, src/containers/SubjectPage/components/SubTopic.jsx
Legger på transformering av artikkel for å formatere datoer.
=> Transform article

e2e/integration/subjects_page_spec.js, e2e/integration/topic_page_spec.js, src/data/programmes.js, src/data/subjects.js
https://trello.com/c/e9fOnk9G/650-enkelte-fag-trenger-%C3%A5-linkes-til-p%C3%A5-andre-m%C3%A5ter-i-ny-navigasjon
=> Changes to subject-structure

src/util/__tests__/searchHelpers-test.js, src/util/searchHelpers.js
=> Get subjects from data/subjects

src/containers/Masthead/MastheadContainer.jsx, src/containers/Masthead/components/MastheadSearch.jsx, src/containers/SearchPage/searchHelpers.js
Har du et filter valgt på sida sendes dette videre til søkesida og presenteres ferdigvalgt.
=> Send filterid to search-page

src/containers/WelcomePage/WelcomePage.jsx, src/containers/WelcomePage/WelcomePageSearch.jsx, src/data/subjects.js, src/util/searchHelpers.js
=> 2246 search subjects rewrite

src/routeHelpers.jsx
Fixes https://github.com/NDLANO/Issues/issues/2261
=> Viser filter i breadcrumb uten å endre subject.

package.json, src/containers/SubjectPage/SubjectContainer.jsx, src/util/apiHelpers.js, yarn.lock
Put subject-name in subheader field.
=> Bumped packages to get subheader styling.

src/components/Article/Article.js
=> Remove check

package.json, yarn.lock
Bumper for å få inn https://github.com/NDLANO/frontend-packages/pull/706 som fikser manglende SSR.
=> Bump ndla-ui to get ndla-hooks

src/data/programmes.js
https://trello.com/c/0DX7KF1Y/740-endring-samisk
Legge til sørsamisk... under fellesfag på yrkesutdanninger
=> Add "Sørsamisk som førstespråk..." to common subjects

src/containers/ProgrammePage/ProgrammePage.jsx
Legger på dimension 5 for programme page.
=> Add dimensions for programme page

src/data/subjects.js
https://trello.com/c/J7zqzQh9/414-endre-navn-p%C3%A5-fagkategorier-i-alle-fag
=> Change subject-category names on frontpage

package.json, src/components/Learningpath/LearningpathEmbed.jsx, yarn.lock
=> Learningpath fix

package.json, src/containers/SearchPage/searchHelpers.js, yarn.lock
Depends on https://github.com/NDLANO/frontend-packages/pull/712.
Fixes NDLANO/Issues#2332
=> Add breadcrumb to subject to enable mouseover

src/containers/ArticlePage/ArticlePage.jsx, src/containers/LearningpathPage/LearningpathPage.jsx, src/containers/SubjectPage/SubjectContainer.jsx, src/containers/SubjectPage/components/Topic.jsx, src/containers/TopicPage/TopicContainer.jsx, src/util/filterHelper.js, src/util/trackingUtil.js
https://github.com/NDLANO/Issues/issues/2321
Sende valgt filter som ny custom dimension #2321
eksempel her: https://trello.com/c/tHs43Gxv/743-custom-dim-namnet-p%C3%A5-filteret-filters-vert-sendt-i-custom-dimention-nr-19
=> 2321 custom dimension 19 filter

src/containers/MultidisciplinarySubject/MultidisciplinarySubjectPage.jsx
[Side for tverrfaglig tema](https://ndla.no/nb/subjects/subject:d1fe9d0a-a54d-49db-a4c2-fd5463a7c9e7?filters=urn:filter:7ab1cc5c-4f79-4bb4-b1ab-bef7c41aed66,urn:filter:3645d7c4-63af-469a-a502-38e53d03d6c7,urn:filter:1e3b4fd0-3245-42b5-8685-db02c5592acc) feiler i dag fordi enkelte emner er uten metadata.
=> Added checks for valid data

src/components/Learningpath/LearningpathEmbed.jsx, src/components/license/ConceptLicenseList.jsx, src/containers/ArticlePage/ArticlePage.jsx, src/containers/PlainArticlePage/PlainArticlePage.jsx, src/containers/TopicPage/TopicContainer.jsx, src/iframe/IframeTopicPage.jsx, src/server/helpers/Document.js, src/server/helpers/__tests__/__snapshots__/Document-test.js.snap, src/util/__tests__/getStructuredDataFromArticle-test.js, src/util/getStructuredDataFromArticle.js
Transformert artikkel har endra datofelt som trengs i metadata. ingenting av det som gjøres i transformeringa brukes i generering av skjemadata så kan like gjerne bruke originale data her.
=> Bruker ikkje-transformert artikkel. Legger på abstract som felt.

src/data/programmes.js
https://trello.com/c/Wl9MuN1W/427-fjerne-matematikk-2p-y-fra-fellesfag-p%C3%A5-yrkesfaglige-program-p%C3%A5-vg2
=> Remove "Matematikk 2P-Y" from Vg2

src/server/helpers/Document.js, src/server/helpers/__tests__/__snapshots__/Document-test.js.snap
Relatert: https://github.com/NDLANO/frontend-packages/pull/724
=> Include "Source Code Pro" font

src/util/getStructuredDataFromArticle.js
https://github.com/NDLANO/Issues/issues/2404
=> Legger til url og logo i publisher data

src/data/programmes.js, src/data/subjects.js
https://trello.com/c/XGsxuiCC/884-naturfag-sf-skal-vere-under-fellesfag-om-ein-velger-alle-fag-p%C3%A5-forsida-p%C3%A5-ndlano
=> Move "Naturfag (SF)" to common subjects

src/containers/MultidisciplinarySubject/MultidisciplinarySubjectArticle.jsx, src/containers/SearchPage/searchHelpers.js, src/queries.js
Viser tag for Tilleggstoff på samme måte som det gamle søket.
=> Add label for additionalresources

src/gqlSchema.json, src/queries.js
Fixes NDLANO/Issues#2426
Depends on https://github.com/NDLANO/graphql-api/pull/136
Legger på ekstra parameter for å få like mange treff på nynorsk og bokmål.
Har henta schema med node 10.14.1 men likevel kom det med fleire endringer enn nytt parameter.
=> Add fallback parameter

src/containers/MultidisciplinarySubject/MultidisciplinarySubjectArticle.jsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectArticlePage.jsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectPage.jsx, src/containers/MultidisciplinarySubject/components/MultidisciplinarySubjectArticle.jsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopic.jsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopicWrapper.jsx, src/queries.js, src/routes.jsx, src/server/helpers/__tests__/__snapshots__/Document-test.js.snap
https://github.com/NDLANO/Issues/issues/2421
=> showResources var alltid false

src/gqlSchema.json, src/queries.js
Fixes NDLANO/Issues#2419
Depends on https://github.com/NDLANO/graphql-api/pull/137
=> Remove related content from learningpath

.eslintrc, jest.config.js, package.json, prettier.js, razzle.config.js, src/components/license/TextLicenseList.jsx, src/components/license/VideoLicenseList.jsx, src/interfaces.ts, tsconfig.json, yarn.lock
Fixes NDLANO/Issues#2453
Kopiert fra ed og listing. Vet ikke hva alt gjør, men ser ut som det fungerer
=> Add typescript

src/containers/SubjectPage/SubjectPage.jsx
Fixes NDLANO/Issues#2418
Test:
* Gå inn på et fag
* Bytt filter i urlen med et filter fra et annet fag
Forventet resultat: Urlen skal endres tilbake med et filter fra det originale faget (ikke vise en tom side som før)
=> Replace incorrect filter

src/containers/MovedResourcePage/MovedResourcePage.jsx, src/gqlSchema.json, src/queries.js, src/shapes.js
Fixes NDLANO/Issues#2343
Depends on https://github.com/NDLANO/graphql-api/pull/140
=> 2343 fix moved resource

package.json, yarn.lock
Fixes NDLANO/Issues#2450
Denne PRen fikser to ting:
1. Når du har gjort et søk på ndla.no, men enda ikke markert et resultat med piltaster så vil enter-klikk ta deg til søkesiden. Dette tilsvarer trykk på "se alle treff på søk" som er øverste resultat.
2. Oppdaget en bug. Ved søk på feks "tr" på test.ndla.no så ble ikke alle resultater fremhevet ved trykk nedover med piltaster. Dette gjaldt hvertfall resultater under kategorien "Fag". Skal fungere nå.
Hvordan teste:
- https://ndla-frontend-pr-637.ndla.sh/
- Skriv en tilfeldig string i søkefeltet. Trykk deretter enter og du skal tas til søkesiden med strengen du skrev inn.
- Skriv en tilfeldig string i søkefeltet. Naviger med piltastene og se at resultater av typen "Fag" blir fremhevet.
=> Upgrade ndla/ui

src/style/index.css
Legger inn overflow og bakgrunnsfarge
=> Setter mathjax bredde til å følge bredden til containeren

src/containers/Masthead/components/MastheadMenu.jsx, src/routeHelpers.jsx
Fikser valgt underemne i meny som Angeilca har kommentert her: https://trello.com/c/WjGhXGZK/890-tilby-visning-av-programomr%C3%A5dene-i-menyen
=> Fix preselected subtopics in menu

src/util/__tests__/searchHelpers-test.js, src/util/searchHelpers.js
Skal kun få treff på fag dersom du søker på minst to tegn.
Test: Gå til søkesida og sjekk at du kun får opp fag om du skriver to tegn eller meir.
=> Limit search for subjects to two chars or more

package.json, src/components/Learningpath/Learningpath.jsx, src/queries.js, yarn.lock
Oppdateringer for nye ikoner fra NDLANO/frontend-packages#766
- Hvert steg har ikoner etter hvilket innholdstype de har
- Det er også oppdatert sånn at læringsstimeny-modalen på mobil lukker seg når man trykker på et steg
=> Learningpath update from frontend packages

src/util/trackingUtil.js
Fixes NDLANO/Issues#2465
Legger på to nye dimensjoner til GA.
Test. Åpne feks artikkel https://ndla-frontend-pr-649.ndla.sh/subject:40/topic:1:196016/topic:1:196025/resource:1:74558?filters=urn:filter:cfa0043e-c52f-4930-b9c3-c65dcefafb62 og inspiser trackingUtil.js og sjå at dim 10 og 20 har verdier.
=> Add grep dimensjons

src/containers/MultidisciplinarySubject/MultidisciplinarySubjectPage.jsx
Fixes NDLANO/Issues#2468
Scrollingen er gjort litt anderledes enn i SubjectPage fordi hierarkiet er litt anderledes
=> Add scrolling to multidisciplinary-subject-page

src/components/Article/ArticleContents.jsx
Setter default verdi for showIngress til `true`. Flytter samtidig default-verdien for modifier til `defaultProps`.
=> 2505 hide ingress. Kodeforbedring

src/client.jsx, src/components/Learningpath/Learningpath.jsx, src/constants.ts, src/containers/Locale/SelectLocale.jsx
NDLANO/Issues#2100
Fjerner siste rest av cookies.
=> Switch coockies with localstorage

src/data/subjects.js
Nytt fag som vises under alle fag: Informasjonsteknologi Vg2 - 2021 BETA
=> Add beta-subject

package.json, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopic.jsx, src/containers/SubjectPage/components/Topic.jsx, yarn.lock
Rendrer markdown i embebeskrivelse.
Test:
Sjekk emnet Deltagelse under Tverrfaglige tema, Demokrati og medborgerskap. Der skal teksten Sosiale medier stå i kursiv.
=> Rendering markdown in topic

src/data/subjects.js
Egen fane med betafag, pluss ndla-film som fag for å støtte filtrering i søk.
=> Added beta subjects

src/data/subjects.js
=> Two new beta subjects

src/containers/SearchPage/SearchContainer.jsx, src/containers/SearchPage/SearchInnerPage.jsx, src/containers/SearchPage/components/SearchHeader.jsx
Test:
* Gå til søkeside
* Velg filter
* Velg underfilter
* Deselect filter
-> Underfilter skal da også bli resatt
=> Subfilter fix

src/data/programmes.js
Tom gruppe for informasjon om manglende programfag.
=> Add empty group

package.json, src/data/subjects.js, yarn.lock
Med hjelp frå språkkyndige Anne.
=> Oversetting av ein del filter/fagnamn

package.json, yarn.lock
=> Bumper for å få ny pil på forsida.

src/data/subjects.js
Beta-fliken har fått tre nye lenker.
=> Tre nye betafag

src/containers/SubjectPage/SubjectPage.jsx, src/gqlSchema.json, src/queries.js
Depends on https://github.com/NDLANO/graphql-api/pull/164
Fixes: https://trello.com/c/8E5DdyPi/78-skjule-skjulte-subjects-som-kontekstmulighet
Master merge + new feature
How to test:
1) Wait for graphql merge
2) Visit /subject:1/topic:1:172568
3) You should be redirected to /subject:1:f481da3f-253f-4548-b8a0-524fc6f00b56/topic:2:172568
------
1) Visit https://ndla-frontend-pr-654.ndla.sh/subject:1/topic:1:172568
2) You should see `Siden har flyttet, men du kan finne den her`
=> Fix topics uten filter

src/containers/ProgrammePage/ProgrammePage.jsx, src/data/subjects.js, src/util/programmesSubjectsHelper.js
Legger på mulighet til å spesifisere topicid i hardkoda liste med subjects.
Test: Under /utdanning/teknologi-og-industrifag Vg2, skal dei tre lenkene under Brønnteknikk ha med topic i url.
=> Makes it possible to link directly to topic in subject.

e2e/fixtures/subjectpageWithTopicGraphQL.json, e2e/integration/topic_page_spec.js, src/containers/SearchPage/searchHelpers.js, src/containers/SubjectPage/SubjectPage.jsx, src/containers/SubjectPage/components/MovedTopicPage.tsx, src/gqlSchema.json, src/queries.js
fixes https://github.com/NDLANO/Issues/issues/2596
Before:
After:
=> fixed alternate topic path view

src/containers/SubjectPage/components/MovedTopicPage.tsx, src/graphqlTypes.ts, tsconfig.json
Koden virker og gir ønska resultat, men typescript er ikkje fornøgd.
=> Flytt funksjon for å slå sammen resultat.

src/containers/MultidisciplinarySubject/MultidisciplinarySubjectPage.jsx, src/data/subjects.js
=> Move some subjects around

src/server/podcastRssFeed.ts, src/util/audioApi.ts
Master bygget feiler pga disse to tingene.
Noen som har en idé om hvorfor `tsc` ikke fanger det før?
=> Fix build problems

.github/workflows/ci.yml, Dockerfile, package.json, src/containers/SubjectPage/SubjectContainer.tsx, src/containers/SubjectPage/SubjectPage.tsx, src/containers/SubjectPage/subjectPageHelpers.tsx, src/routeHelpers.tsx
Fiksa release bygget ved å sette på `@ts-ignore` mellom tsx og jsx filer. Bumpa også node til v14.16. Lagde en issue på dette issue https://github.com/NDLANO/Issues/issues/2654
=> Update node to 14.16

src/config.ts, src/containers/Page/components/Footer.jsx
NDLANO/Issues#2656
Legger til overstyring av urler via konfig.
=> Added possibility to override urls

package.json, src/client.tsx, src/server/helpers/Document.js, src/server/helpers/render.js, src/server/routes/defaultRoute.js, src/server/routes/errorRoute.js, src/server/routes/iframeArticleRoute.js, src/server/routes/ltiRoute.js, src/util/getArticleScripts.js, yarn.lock
Fjernet tilsynelatende ubrukt kode og minsket duplikater. 
Fjernet emotion-cache da den ikke så ut til å være i bruk. Så ut som cache-løsningen var for emotion/css, mens emotion/css ikke brukes i prosjektet (se https://emotion.sh/docs/ssr). 
Om ytelsen er endret, kan det gi tegn på at jeg fjernet noe som var i bruk. Men lokalt så jeg bare forbedringer i lighthouse. Testet også med now-instansen vs test.ndla.no, og de nokså likt resultat.
=> Refactor render functions

src/util/getContentType.tsx
Fixes https://github.com/NDLANO/Issues/issues/2688
=> Fixed issue where article-iframe links would fail due to a faulty conditional

src/containers/Resources/Resources.jsx
Dep: https://github.com/NDLANO/frontend-packages/pull/831
=> Fix content-type-name on ungrouped resources after update

src/data/programmes.ts
Update programmes.ts
- sørsamisk stod to ganger på byggfag vg1 og vg2
- Feil kultur og kommunikasjon 1-fag var lenket opp på studspes vg2 og vg3 (både musikk, idrett, kunst og vanlig studspes)
=> Fagretting 1 oktober

src/containers/ToolboxSubject/components/ToolboxTopicWrapper.tsx
Fixes https://github.com/NDLANO/Issues/issues/2713
=> Added spinner when a topic is loading

src/data/subjects.ts
https://trello.com/c/gCYFmMAz/137-endre-navn-p%C3%A5-tabs
=> Change name of subject categories on frontpage

package.json, src/containers/SearchPage/components/SearchHeader.jsx, src/data/subjects.ts, src/util/programmesSubjectsHelper.ts, yarn.lock
Depends on ~https://github.com/NDLANO/frontend-packages/pull/870~
Fixes NDLANO/Issues#2742
Spesifiserer kategori som skal vises på forsida. Kun Alle, utgått og kommende skal vises.
Test:
* Åpne pr-installasjon
* Vis forsida og sjekk at kun tre grupper vises.
=> Adds visible to category.

src/containers/SubjectPage/components/Topic.tsx, src/containers/ToolboxSubject/components/ToolboxTopicWrapper.tsx, src/data/programmes.ts, src/data/subjects.ts, src/util/searchHelpers.ts
=> Enable one subject, and rearrange others.

src/util/apiHelpers.ts
localStorage ble forsøkt brukt ved SSR som førte til feilmelding, samt visning av 404-side. Dette er nå fikset:
Hvordan teste:
1. /subject:1:9b7e7534-c072-4412-b8ef-df076308cad0/topic:1:3d79c5be-7830-49b5-8e6d-55c90e6c4f94/resource:1:181315
2. Skal fungere i PR-instans
3. Skal ikke fungere i test.
=> Feide token is not fetched on SSR

package.json, src/App.tsx, src/containers/Masthead/MastheadContainer.tsx, src/containers/Masthead/components/MastheadMenu.tsx, src/containers/Masthead/components/MastheadTopics.tsx, src/containers/ProgrammePage/ProgrammePage.jsx, src/interfaces.ts, src/routeHelpers.tsx, src/routes.tsx, src/util/programmesSubjectsHelper.ts, yarn.lock
Fixes NDLANO/Issues 2780
Depends on https://github.com/NDLANO/frontend-packages/pull/888 (for å fjerne propType warnings)
Test:
Meny er lagt til på søkeside og programside og skal se ut og oppføre seg som i designmanualen:
https://designmanual.ndla.no/?path=/story/s%C3%B8k--s%C3%B8keside-re-design
https://designmanual.ndla.no/?path=/story/fag-og-emnesider--2-programside
=> 2780 show menu on program and search page

src/App.tsx, src/containers/ErrorPage/ErrorPage.tsx, src/containers/Page/Page.tsx, src/containers/Page/components/Footer.jsx
Fixes NDLANO/Issues#2858
Sender korrekt zendesk-språk. Har også rydda litt rundt bruk av locale som parameter.
Test:
* I test vises zendesk-på engelsk. I denne versjonen vises den på norsk. For å teste lokalt må du ha NDLA_ZENDESK_WIDGET_KEY satt i terminalen du starter appen med. Denne finner du i deploy.
* Pr-installasjon: https://ndla-frontend-pr-810.ndla.sh
=> 2858 use correct zendesk language

src/containers/ToolboxSubject/ToolboxSubjectContainer.tsx
Viser banner på verktøykassa.
Test:
Sjekk Verktøykassa for elev i pr-installasjon. Der er det satt bannerbilde.
=> Show banner on toolbox page

src/server/contentSecurityPolicy.ts
NDLA tester xAPI fra h5p i test og må ha tilgang til et par adresser.
=> Legger til xapi og kf-adresse kun for test.

src/components/FeideLoginButton/FeideLoginButton.tsx, src/components/FeideLoginButton/feideApi.ts, src/server/contentSecurityPolicy.ts
Henter informasjon om innlogga bruker. Ikkje gitt at vi skal vise navn og epost men tenker ndla skal få meine noko om det. Dette gjør det eklere å vise primærrolle også.
=> Feide add userinfo

src/data/programmes.ts
=> tryggleik -> sikkerheit

src/containers/ToolboxSubject/ToolboxSubjectContainer.tsx
Fikser denne: https://github.com/NDLANO/ndla-frontend/pull/822#issuecomment-987703986
=> Use `socialMediaMetaData` as tracker title for `ToolboxSubjectContainer`

src/containers/MultidisciplinarySubject/MultidisciplinarySubjectArticlePage.tsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectPage.tsx, src/containers/ResourcePage/ResourcePage.tsx, src/containers/ToolboxSubject/ToolboxSubjectPage.tsx
Hvordan dette brakk `routes.tsx` for andre komponenter skjønner jeg ikke helt. Skal se mer på, men mistenker at det vil føre til en overhaling av `routes` også.
=> Converted ResourcePage to TypeScript

src/containers/PlainArticlePage/PlainArticlePage.jsx, src/containers/PlainLearningpathPage/PlainLearningpathPage.jsx, src/iframe/IframeArticlePage.js, src/iframe/IframeTopicPage.jsx
Forteller søkemotorer at dei ikkje skal indeksere alle sider.
=> Do not index standalone pages.

src/containers/SubjectPage/SubjectContainer.tsx
NDLANO/Issues#2908
Fikser slik at tilbakeknapp kan brukes til å gå oppover ei fagside.
=> Gjør det slik at navigering i fagside kan skje begge veier

src/components/AuthenticationContext.tsx, src/components/FeideLoginButton/FeideLoginButton.tsx, src/containers/Page/components/FeideFooter.tsx, src/util/feideApi.ts
Dette må på plass for at vi kan sende info om bruker i tracking.
Skulle helst ha fått til at fetchFeideUserWithGroups hadde fungert, men eg får ikkje til chaining av promises. Fint om nokon andre som skjønner dette bedre enn meg kan ta det videre.
=> Plassering av bruker i authcontext

src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts
=> Bytt opphav og lisens

package.json, yarn.lock
Tar i bruk den raskere versjonen av Zendesk.
=> Bumped zendesk

src/config.ts, src/server/helpers/openidHelper.ts
Flyttet variablene ut av den generelle configen.
=> Moved some secrets around to only exist on the server

src/components/FeideLoginButton/FeideLoginButton.tsx, src/containers/ArticlePage/ArticlePage.tsx, src/containers/LearningpathPage/LearningpathPage.jsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectArticlePage.tsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectPage.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinarySubjectArticle.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopic.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopicWrapper.tsx, src/containers/ProgrammePage/ProgrammePage.jsx, src/containers/ResourcePage/ResourcePage.tsx, src/containers/SubjectPage/SubjectContainer.tsx, src/containers/SubjectPage/SubjectPage.tsx, src/containers/SubjectPage/components/Topic.tsx, src/containers/SubjectPage/components/TopicWrapper.tsx, src/containers/ToolboxSubject/ToolboxSubjectContainer.tsx, src/containers/ToolboxSubject/ToolboxSubjectPage.tsx, src/containers/ToolboxSubject/components/ToolboxTopicContainer.tsx, src/containers/ToolboxSubject/components/ToolboxTopicWrapper.tsx, src/util/feideApi.ts, src/util/trackingUtil.ts
Fixes NDLANO/Issues#2944
Legger på sporing av innlogga bruker.
Test
* Kjør lokalt med feidestøtte
* Logg inn med en feidebruker
* Sett et breakpoint i returen i trackingUtil og sjå at dimensions-objektet har informasjon om brukeren.
=> 2944 add user dimensions

src/components/license/AudioLicenseList.tsx, src/components/license/ImageLicenseList.tsx
Fixes https://github.com/NDLANO/Issues/issues/2976
Hvordan teste: Åpne en artikkel som inneholder lydfiler. Sjekk at lydfilene har titler under "regler for bruk"
=> Added title and source to AudioLicenseList

src/containers/ErrorPage/__tests__/__snapshots__/ErrorPage-test.js.snap, src/containers/Page/Page.tsx, src/containers/Page/components/Footer.tsx
Fixes https://github.com/NDLANO/Issues/issues/2984
Teit fiks, men det funker. Kilde: Jeg har mac.
=> Moved Zendesk button in order for it to appear properly in Safari

src/iframe/IframePageContainer.tsx, src/iframe/IframePageWrapper.tsx, src/iframe/__tests__/IframeArticlePage-test.tsx, src/iframe/index.tsx, src/interfaces.ts, src/server/helpers/render.js, src/server/routes/iframeArticleRoute.tsx
Samme som fiksen for `defaultRoute`, bare litt mer innviklet.
=> Fixed client-side hydration of apollo cache for iframe endpoints

src/components/Article/Article.tsx, src/components/CompetenceGoals.tsx, src/components/__tests__/CompetenceGoals-test.js, src/components/__tests__/__snapshots__/CompetenceGoals-test.js.snap, src/containers/ArticlePage/ArticlePage.tsx, src/containers/SubjectPage/SubjectContainer.tsx
Fixes NDLANO/Issues#2991
Legger på søk etter subject i tillegg til grepkode fra både artikkel og subject.
=> Adds param to add subjectid to search.

src/containers/ArticlePage/ArticlePage.tsx, src/containers/Masthead/MastheadContainer.tsx, src/containers/Masthead/mastheadHelpers.ts, src/containers/MovedResourcePage/MovedResourcePage.tsx, src/containers/PlainLearningpathPage/PlainLearningpathContainer.tsx, src/containers/ResourcePage/ResourcePage.tsx, src/containers/Resources/resourceHelpers.ts, src/gqlSchema.json, src/graphqlTypes.ts, src/routeHelpers.tsx, src/util/getArticleProps.ts, src/util/getContentType.tsx, src/util/trackingUtil.ts
Fikser typefeil som kommer av at vi oppdaterte GraphQL-typene.
=> Updated codebase to reflect changes in GQL types

src/components/Article/Article.tsx, src/components/license/AudioLicenseList.tsx, src/components/license/ConceptLicenseList.tsx, src/components/license/H5pLicenseList.tsx, src/components/license/ImageLicenseList.tsx, src/components/license/TextLicenseList.tsx, src/components/license/VideoLicenseList.tsx, src/containers/ArticlePage/components/ArticleHero.tsx, src/containers/FilmFrontpage/FilmFrontpage.tsx, src/containers/FilmFrontpage/MovieCategory.tsx, src/containers/Masthead/MastheadContainer.tsx, src/containers/Page/Page.tsx, src/containers/SearchPage/searchHelpers.tsx
Sitter nå igjen med 21 ts-ignore, hvorav 8 skyldes mangle TS i frontend-packages. Resten er "vår" feil.
=> Removed unnecessary ts-ignores

src/data/subjects.ts
Legger til ny liste av fag for deploy til 1. mars.
=> Added new list of subjects.

src/containers/WelcomePage/WelcomePage.tsx
Fixes https://github.com/NDLANO/Issues/issues/3012
Hopper til utdanningsprogram.
=> Added skipToContent on WelcomePage

codegen.yml, src/components/SubjectLinkList.tsx, src/containers/AllSubjectsPage/AllSubjectsPage.tsx, src/graphqlTypes.ts, src/queries.ts
Enkel og grei. Ber bare om litt mindre data.
=> Convert AllSubjectsPage to make use of colocated fragments

src/components/Article/Article.tsx, src/containers/ArticlePage/ArticlePage.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopic.tsx, src/containers/PlainArticlePage/PlainArticleContainer.tsx, src/containers/SearchPage/SearchInnerPage.tsx, src/gqlSchema.json, src/graphqlTypes.ts, src/iframe/IframeArticlePage.tsx, src/iframe/IframeTopicPage.tsx, src/queries.ts, src/util/getArticleScripts.ts, src/util/getStructuredDataFromArticle.ts, src/util/trackingUtil.ts, src/util/transformArticle.ts
Avhengig av https://github.com/NDLANO/graphql-api/pull/236. Må tas i bruk for at ndla-frontend skal funke.
=> Fixed type errors that occurred after updating schema

src/components/SocialMediaMetadata.tsx, src/containers/ArticlePage/ArticlePage.tsx, src/containers/LearningpathPage/LearningpathPage.tsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectArticlePage.tsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectPage.tsx, src/containers/PlainArticlePage/PlainArticleContainer.tsx, src/containers/PlainLearningpathPage/PlainLearningpathContainer.tsx, src/containers/SubjectPage/SubjectContainer.tsx, src/containers/ToolboxSubject/ToolboxSubjectContainer.tsx, src/containers/WelcomePage/WelcomePage.tsx, src/iframe/IframeArticlePage.tsx, src/iframe/IframeTopicPage.tsx
Blir litt overkill å ta i bruk `GQLMetaImage` når vi bare trenger en `string`.
=> Changed SocialMediaMetaData image parameter to accept an url instead of an object

src/containers/Resources/Resources.tsx, src/containers/Resources/getResourceGroups.ts, src/graphqlTypes.ts
Denne må inn før man kan jobbe videre på `Topic`- og `Subject`. Skal ikke utgjøre noen funksjonell forskjell.
=> Added colocation to Resources component

src/components/VisualElement/VisualElement.tsx, src/components/VisualElement/VisualElementLicenseButtons.tsx, src/components/VisualElement/VisualElementWrapper.tsx, src/graphqlTypes.ts
Byggeklosser til fremtidig bruk.
=> Added colocation to VisualElement components

src/components/Article/Article.tsx, src/containers/ArticlePage/ArticlePage.tsx, src/containers/ArticlePage/components/ArticleHero.tsx, src/graphqlTypes.ts, src/util/getArticleScripts.ts, src/util/getStructuredDataFromArticle.ts
Trengs -ish for både Learningpath og ResourcePage, så tar den for seg selv.
=> Added colocation to ArticlePage and related components

src/containers/SubjectPage/SubjectContainer.tsx, src/containers/SubjectPage/SubjectPage.tsx, src/containers/SubjectPage/components/MovedTopicPage.tsx, src/containers/SubjectPage/components/SubjectPageAbout.tsx, src/containers/SubjectPage/components/SubjectPageContent.tsx, src/containers/SubjectPage/components/SubjectPageInformation.tsx, src/containers/SubjectPage/components/SubjectTopical.tsx, src/containers/SubjectPage/components/TopicWrapper.tsx, src/graphqlTypes.ts
Tror bottlenecken i innlastingstid av subjects nå ligger i Masthead.
Avhengig av https://github.com/NDLANO/graphql-api/pull/239
=> Added colocation to SubjectPage components

src/components/Learningpath/LastLearningpathStepInfo.tsx, src/components/Learningpath/Learningpath.tsx, src/components/Learningpath/LearningpathEmbed.tsx, src/containers/LearningpathPage/LearningpathPage.tsx, src/containers/Resources/resourceHelpers.ts, src/containers/SubjectPage/components/SubjectPageInformation.tsx, src/containers/SubjectPage/components/SubjectTopical.tsx, src/graphqlTypes.ts, src/routeHelpers.tsx, src/util/trackingUtil.ts
Mer moro! Siste som må inn før ResourcePage kan tas tak i.
=> Learningpath colocation

src/containers/SearchPage/SearchInnerPage.tsx, src/util/apiHelpers.ts
Ser ut til å fikse det meste av problemer utenom at det hopper til toppen.
=> Remove toString when searching for more

src/containers/PlainArticlePage/PlainArticleContainer.tsx, src/containers/PlainArticlePage/PlainArticlePage.tsx, src/containers/PlainLearningpathPage/PlainLearningpathContainer.tsx, src/containers/PlainLearningpathPage/PlainLearningpathPage.tsx, src/graphqlTypes.ts, src/queries.ts
`PlainArticlePage` går fra 2s~ til 300ms~, mens `PlainLearningpathPage` går fra 8-10s~ til 5s~.
=> Colocation for plain article and learningpath pages

src/containers/SearchPage/SearchPage.tsx
Skjuler forklaringstreff midlertidig til vi har fått ferdig designet på forklaringsblokk.
=> Do not show concept-searchresult temporarily

src/data/programmes.ts
Sjekker med ndla om det ser greit ut.
=> Update subjects according to NDLA

src/containers/SearchPage/SearchContainer.tsx, src/containers/SearchPage/components/SearchResults.tsx
Viser valg for å bytte mellom grid og liste i søkeresultat.
Test:
* Endre visning skal endre alle visninger.
=> Viser knapp for bytte mellom grid og list

public/static/flag_of_Ukraine.svg, public/static/flag_of_ukraine.svg, src/constants.ts, src/containers/WelcomePage/WelcomePage.tsx, src/server/server.ts
Fixes https://github.com/NDLANO/Issues/issues/3077
Teksten er hardkodet. Skal jeg flytte den inn i `messages` eller er den grei som den er?
=> Add Ukrainian banner card

src/data/programmes.ts
Det gamle bildet har blitt bytta med eit meir passande.
=> Bytter headerbilde på IDD

package.json, src/server/server.ts, yarn.lock
Skal visstnok funke helt likt!
=> Replace body-parser with the built-in express functionality

src/util/getStructuredDataFromArticle.ts
Fixes NDLANO/Issues#2979
Burde vore gjort for lenge siden.
Test:
* Sjekk at alle mediafelt har acquireLicensePage som peiker på url i zendesk.
=> Add acquireLicensePage

src/util/getStructuredDataFromArticle.ts
Forsøker en enklere måte å definere skjema.
=> Trying out simplified breadcrumb schema

src/data/programmes.ts
Legger til Biologi 1 i programfag der det mangler.
=> Add biologi1 to programmes

src/server/helpers/Document.tsx
Som tittelen sier. Sjekk at json+ld finnes i head både med og uten SSR.
=> Move helmet scripts inside head instead of body

src/constants.ts, src/containers/ProgrammePage/ProgrammePage.tsx, src/routeHelpers.tsx, src/routes.tsx
Første compat-route!
Inntil videre ser routes litt hårete ut p.g.a compat, men etter hvert kan vi begynne å bruke nøstede paths! Kan testes ved å sjekke at navigering til programfag og forskjellige grades fungerer som før.
=> Programme page rr-6 compat

src/containers/PodcastPage/PodcastSeries.tsx, src/containers/PodcastPage/PodcastSeriesListPage.tsx, src/containers/PodcastPage/PodcastSeriesPage.tsx, src/routes.tsx
Veldig isolerte, og derfor veldig greie å skrive om! Sjekk at du kan navigere deg fram og tilbake mellom /podkast og /podkast/:id
=> Add rr6-compat to podcast pages

src/constants.ts, src/containers/SearchPage/SearchPage.tsx, src/routes.tsx
Veldig enkel, da SearchPage såvidt tar i bruk RR på grunn av LTI.
=> Add rr6-compat to search page

src/containers/PlainArticlePage/PlainArticlePage.tsx, src/routes.tsx
Enda en grei overgang til RR-6. Sjekk at du kan gå inn på en plain article (`/article/:id`) som før.
=> Add rr6-compat to PlainArticlePage

src/data/programmes.ts, src/data/subjects.ts
https://trello.com/c/GxlraT2u/1701-it-fag-uten-beta-inn-i-fagoversikter
=> IT-fag uten "beta" inn i fagoversikter

package.json, public/static/mathjax-config.js, src/style/index.css, src/util/getArticleScripts.ts, yarn.lock
https://ndla-frontend-pr-1006.ndla.sh/en/subject:1:734bd33b-da6d-49b0-bb34-c6df5b956f8e/topic:1:2737083d-8400-4a9f-b864-b05c42a470df/topic:1:2cd30524-12fe-41c6-9008-f36146369953/resource:20290ac7-9bad-4b1b-91cd-ef266bc9a028
Visning av pipes (absolutt-verdi) av formler skal fungere
=> Fix mathml styling

src/containers/PlainArticlePage/PlainArticlePage.tsx, src/graphqlTypes.ts
NDLANO/Issues#3123
Viser også visuelt element på plain article.
=> Visual element also in plain article

src/containers/SearchPage/SearchInnerPage.tsx
Fixes https://github.com/NDLANO/Issues/issues/3112
Legger til en `useEffect` som oppdaterer typefiltre når språket endrer seg.
=> Replace typeFilters when language changes

src/containers/SearchPage/SearchInnerPage.tsx, src/util/apiHelpers.ts
Fixes https://github.com/NDLANO/Issues/issues/3127
Jeg har ikke nok peiling på søke-API'et til å heeelt vite hvorfor vi matcher på `aggregations`, men å fjerne matchingen løser problemet. Er det noen som har peiling på om dette vil ha noen andre uønskede konsekvenser?
=> Remove aggregation based matching when merging search results

src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts
=> Nye blogginnlegg på forsida.

src/data/programmes.ts, src/data/subjects.ts
Tilbakemeldinger på https://trello.com/c/bzxFMh5h/1738-restfix-fagnavn-og-oversikter-h22
=> Oppdateringer etter prodsetting av nye fag.

package.json, src/components/MyNdla/AddResourceToFolder.tsx, src/components/MyNdla/LoginComponent.tsx, src/containers/MyNdla/Folders/ResourceList.tsx, src/containers/MyNdla/MyNdlaPage.tsx, src/containers/MyNdla/Tags/TagsPage.tsx, yarn.lock
Klargjort for oppdatering av ndla-ui
=> Add tagLinkPrefix to prepare for updated ndla-ui for MinNDLA

src/components/FeideLoginButton/FeideLoginButton.tsx
(https://trello.com/c/s8UcdfDY/97-juster-fontvekt-og-hoverstil)
=> Adjust styling of logged in My NDLA link in masthead to match the logged out button

src/containers/MyNdla/Folders/FolderBreadcrumb.tsx, src/containers/MyNdla/Folders/FoldersPage.tsx
Menyvalg for sletting av mappe skal ikke lenger vises på Favoritter-mappen. Dette gjelder både i trestruktur og mappevisning.
=> Disable deleting favorite folder

src/data/programmes.ts, src/data/subjects.ts
=> Ny ressursgruppe entrepenørskap og bedriftsutvikling

src/containers/MyNdla/Folders/ResourceList.tsx, src/containers/MyNdla/MyNdlaPage.tsx, src/containers/MyNdla/Tags/TagsPage.tsx
https://trello.com/c/D8g9VZlo/136-valg-om-%C3%A5-fjerne-tag-p%C3%A5-ressurs-i-tag-siden
https://trello.com/c/GIXQqUB6/132-mine-tags-har-ikke-samme-utlistingsmuligheter-som-mapper
Endrer også overskriften på MyNdlaPage til h1, ref https://trello.com/c/ogNkqp0s/126-feil-tittelniv%C3%A5-p%C3%A5-overskrift-h2-over-h2
=> Add view types in Tag Page. Add ability to edit tags in Tag Page.

src/components/Article/Article.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinarySubjectArticle.tsx
Avhengig av https://github.com/NDLANO/graphql-api/pull/263
Kan testes ved å spinne opp graphql lokalt, for deretter å legge til en tverrfaglig artikkel i min NDLA.
=> Add support for multidisciplinary topic articles

src/components/MyNdla/LoginComponent.tsx
https://trello.com/c/uZTXezKt/141-visning-av-ressurs-n%C3%A5r-en-ikke-er-logget-inn-p%C3%A5-mobil-m%C3%A5-tilpasses
Var tydeligvis litt usikkert om dette skulle være det endelige designet, men er uansett merkbart bedre enn nåværende.
=> Make the login component more mobile friendly

src/containers/PodcastPage/PodcastSeriesListPage.tsx, src/graphqlTypes.ts, src/schema.graphql
Depends on https://github.com/NDLANO/graphql-api/pull/262
Fixes NDLANO/Issues#3190
Testes ved å sjekke at `/podkast` sidene inneholder like mange resultater på riktig språk.
=> #3190: Make use of `fallback` param for podcast searching

src/containers/MyNdla/folderMutations.ts
Avslutter opp i https://trello.com/c/vs0rhm0l/112-kluss-med-sletting-av-mine-favoritter
=> Fetch new favorite folder when all folders are deleted

e2e/integration/frontpage.spec.ts, src/containers/Page/Layout.tsx, src/routeHelpers.tsx
Test for å vise header på forside.
=> Header on frontpage

src/data/programmes.ts
Disse ligger under utgåtte fag og skal inn på utdanningsprogram fordi vi ikke får inn noen revisjoner på en stund:
Åarjelsaemien voestesgïeline (Utgått) (PB) > på påbyggssiden fellesfag
Åarjelsaemien voestesgïeline (Utgått) (SR vg2) > på studiespes vg2 fellesfag
Åarjelsaemien voestesgïeline (Utgått) (SR vg3) > på studiespes vg3 fellesfag
https://trello.com/c/QFg3XSUH/1766-utgåtte-sørsamiskfag-inn-i-utdanningsprogramoversikter
=> Åarjelsaemien voestesgïeline

src/containers/Masthead/MastheadContainer.tsx
https://trello.com/c/ch6dArKa/139-ingen-indikasjon-p%C3%A5-innlogget-status
Litt redd for lange navn, men det får bare være.
=> Show given name in place of my ndla when logged in

src/components/FeideLoginButton/FeideLoginButton.tsx, src/containers/Page/components/FeideFooter.tsx
https://trello.com/c/tMMMpMIH/149-kan-vi-endre-dialogvindu-ved-innlogging-fra-bunn-til-samme-dialogvindu-som-innlogging-via-topp
=> Show new login component from footer when logged out

src/data/subjects.ts
Bitteliten bindestrek som skal bort
https://www.udir.no/lk20/tip01-03/kompetansemaal-og-vurdering/kv253?lang=nob
=> Produktivitet og kvalitetsstyring (TP-TIP vg1)

src/components/FeideLoginButton/FeideLoginButton.tsx, src/containers/ArticlePage/components/ArticleHero.tsx
Ingen konsekvenser annet enn mindre rødt i konsollen.
=> Do not forward invalid props to html

src/containers/MultidisciplinarySubject/components/MultidisciplinarySubjectArticle.tsx
Hjerte på tverrfaglig tema vises alltid. Legger inn sjekk på feideEnabled istedet.
=> Hiding heart from page

src/containers/MyNdla/Folders/EditFolderModal.tsx
Flytter også headeren inn i ModalHeader.
=> Use labelledBy instead of label for EditFolderModal

src/containers/MyNdla/Tags/TagsPage.tsx
https://trello.com/c/hSC8aExc/200-opplesning-av-emneknagger-inkluderer-emneknagg-tegnet
=> Put all tags inside a nav element. Use a HashTag icon instead of a symbol. Puts tags inside of a list

src/containers/ArticlePage/ArticlePage.tsx, src/containers/PlainArticlePage/PlainArticleContainer.tsx
Tester å legge inn alternate link for oembed.
Test:
* Åpne pr-installasjon, finn en artikkel, og sjekk at du får en link alternative med oembed/json som format. Lenka skal gi deg oembedversjonen av artikkelen-
=> Test adding oembed-meta link.

src/components/AuthenticationContext.tsx, src/containers/Login/LoginProviders.ts, src/containers/Login/LoginSuccess.tsx, src/server/helpers/openidHelper.ts, src/util/authHelpers.ts
Reverts NDLANO/ndla-frontend#1110
=> Revert "Implement promptless login to feide"

package.json, yarn.lock
Bumper ndla-ui med konfig-endring i i18n.
Test:
* Logg på med feide-bruker og sjekk at det står feks "2 mapper" og ikkje "2 mappe"
=> Fikser plurals i oversettelser

src/App.tsx, src/server/server.ts, src/util/authHelpers.ts
Slik får vi verifisert at pålogging fungerer i prod.
=> Endrer slik at det går an å logge på ved å gå til /minndla.

src/components/SocialMediaMetadata.tsx, src/containers/ArticlePage/ArticlePage.tsx, src/containers/FilmFrontpage/FilmFrontpage.tsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectArticlePage.tsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectPage.tsx, src/containers/PlainArticlePage/PlainArticleContainer.tsx, src/containers/ProgrammePage/ProgrammeContainer.tsx, src/containers/SubjectPage/SubjectContainer.tsx, src/containers/ToolboxSubject/ToolboxSubjectContainer.tsx, src/iframe/IframeTopicPage.tsx
Rydder opp i litt `<meta name="description"...>` tags og fikser så side-tittel reflekterer innholdet i `SubjectContainer`.
Kan testes ved å sjekke at side-tittelen reflekterer emnet dersom man trykker seg videre på en fagforside :^)
=> Update title based on selected topic in `SubjectContainer`

package.json, src/containers/MyNdla/Tags/TagsPage.tsx, yarn.lock
https://trello.com/c/qViUICEW/221-hvis-jeg-sletter-en-emneknagg-s%C3%A5-b%C3%B8r-jeg-sendes-til-siden-mine-emneknagger
Avventer pakke-bump
=> Encode tags in urls. Navigate back to tags page if no tags exist after deletion

package.json, src/containers/MyNdla/MyNdlaPage.tsx, yarn.lock
https://trello.com/c/c6YQBcqW/219-p%C3%A5-slutten-av-informasjonen-om-hva-feide-henter-legger-vi-til-tekst
Avhengig av https://github.com/NDLANO/frontend-packages/pull/1331
=> Add translations for user info support

src/components/MyNdla/AddResourceToFolder.tsx, src/components/MyNdla/AddResourceToFolderModal.tsx, src/containers/MyNdla/Folders/ResourceList.tsx
https://trello.com/c/HXo4ZwyG/247-n%C3%A5r-man-endrer-mappe-tags-b%C3%B8r-mappen-du-st%C3%A5r-i-vises-som-default-i-stedet-for-favoritter
=> Select the currently used folder as default when changing resources from the folders page

src/components/MyNdla/NewFolder.tsx
https://trello.com/c/BI62gmqC/223-ikke-vise-feilmelding-om-manglende-tekst-i-inputfelt-ved-%C3%A5pning
=> Do not show error message until user has written

src/server/contentSecurityPolicy.ts
Henger sammen med pr i backend og ed.
=> New embeds

src/containers/MyNdla/Folders/FoldersPage.tsx, src/containers/MyNdla/Folders/ResourceList.tsx
https://trello.com/c/Xi6HZSof/252-tastaturfelle
Usikker på hvordan vi skal kombinere dette med DnD, men vi finner en løsning når den tid kommer!
=> Focus folder or resource link instead of list item when list changes

public/static/mathjax-config.js, src/components/Learningpath/LearningpathEmbed.tsx, src/containers/ArticlePage/ArticlePage.tsx, src/containers/PlainArticlePage/PlainArticleContainer.tsx, src/iframe/IframeArticlePage.tsx, src/iframe/IframeTopicPage.tsx, src/util/getArticleScripts.ts
Setter locale på mathjax fra valgt språk i app.
Test:
* Finn en artikkel med matte, og høgreklikk på formel. Velg Accessibilty -> Speech -> Language og sjekk at korrekt språk er valgt.
=> Sets locale to parameter from url

src/containers/MyNdla/MyNdlaPage.tsx
https://trello.com/c/aaOahs7p/233-uu-feil-tittelniv%C3%A5er-repeterende-h2
=> Fix heading levels on my page

package.json, yarn.lock
Denne var litt mer oppdatert enn de andre, så litt enklere :^)
=> Bump typescript & eslint config

package.json, src/containers/MyNdla/MyNdlaPage.tsx, yarn.lock
Nylig lagt til skal ikke lenger vises dersom det ikke finnes nylige lagt til ressurser. Dropper også fallbackmelding med instrukser om hvordan bruke min ndla. https://trello.com/c/VFAdlVHC/256-tittel-for-nylige-b%C3%B8r-ikke-st%C3%A5-der-f%C3%B8r-det-finnes-nylige
aticle-scripts ble ikke oppdatert i forrige merge ved et uhell. Oppdaterer den nå i tilfelle det skulle hatt noen kosekvenser.
https://github.com/NDLANO/ndla-frontend/pull/1164#issuecomment-1274259651
=> Fjern "Nylig lagt til" dersom ingen ressurser finnes

src/client.tsx, src/server/routes/defaultRoute.js
Superenkel fiks, men veldig mulig eg det er ting eg ikkje har tenkt på. Ser ut til å fungere lokalt, men greit å få testa.
=> Only handle cookie on client.

src/components/WhileLoading.tsx, src/containers/MyNdla/Folders/FolderAndResourceCount.tsx, src/containers/MyNdla/Folders/FolderList.tsx, src/containers/MyNdla/Folders/FoldersPage.tsx, src/containers/MyNdla/Folders/FoldersPageTitle.tsx
Første versjon av mitt forsøk på å få folderspage til å se penere ut under loading når vi ikke kan SSR'e innholdet.
Åpen på forslag på alt 😄 
Kan testes ved å prøve å refreshe div sider på min ndla for å se hvordan loadingen ser ut
=> Add loading placeholders for `FoldersPage`

yarn.lock
Fikser https://github.com/NDLANO/ndla-frontend/security/dependabot/57
=> Upgrade async to fix vuln

.github/workflows/ci.yml, .github/workflows/release.yml
Berre bumpa alle actions. Ser ikkje ut som om vi treng endre config på grunn av dette.
=> Bumps all versions.

src/containers/ArticlePage/components/ArticleHero.tsx
Fixes https://github.com/NDLANO/Issues/issues/3310
=> Remove alt text from article hero

package.json, yarn.lock
Hvordan teste: Se at testene passerer i pipeline
=> Bump nock to newest

package.json, yarn.lock
Bumper en major. Ser ut til å fungere fint å logge inn og ut, så kan ikke se for meg at altfor mye annet skal brekke.
=> Bump open-id-client one major

package.json, src/components/__tests__/RedirectExternal-test.js, src/server/routes/__tests__/forwardingRoute-test.js, yarn.lock
Det vi bruker Sinon til nå kan fint erstattes med jest-funksjonalitet.
=> Replace sinon dependency with jest

src/components/AlertsContext.tsx, src/components/AuthenticationContext.tsx
Tror egentlig ikke at dette har så mye å si, men kan hende at vi får litt færre renders enn før.
=> Use callbacks in providers

src/containers/ArticlePage/ArticlePage.tsx, src/containers/LearningpathPage/LearningpathPage.tsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectArticlePage.tsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectPage.tsx, src/containers/SubjectPage/SubjectContainer.tsx, src/containers/ToolboxSubject/ToolboxSubjectContainer.tsx
=> Bruker navn fra fagforside kun på programfag

src/data/programmes.ts
Legger til Yrkesfaglig fordypning (TP-TOL vg2) på
utdanning/teknologi-og-industrifag/vg2
=> TP-TOL vg2

src/server/contentSecurityPolicy.ts
https://github.com/NDLANO/Issues/issues/3363
La til støtte for jeopardy i content rules
=> Added jeopardylabs url to content

src/components/Learningpath/LastLearningpathStepInfo.tsx, src/containers/ArticlePage/ArticlePage.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinarySubjectArticle.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopic.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopicWrapper.tsx, src/containers/Resources/Resources.tsx, src/containers/Resources/ResourcesTopicTitle.tsx, src/containers/SubjectPage/components/Topic.tsx, src/containers/ToolboxSubject/components/ToolboxTopicWrapper.tsx, src/interfaces.ts
Fjerner også bruk av `Resources` i MultidisciplinaryTopic som jeg tror ikke brukes. Gjerne rett meg om det er feil.
=> Improve heading structure for resource lists

public/robots.txt, src/containers/ErrorPage/ErrorPage.tsx, src/containers/Page/Layout.tsx, src/server/server.ts, src/statusCodes.ts
Kan testes med å bruke url https://ndla.no/nn/search/apachesolr_search/?language%5B%5D=und&language%5B%5D=nn&sm_ndla_grep_competence_aims_id%5B%5D=K17637&im_vid_100016%5B%5D=82728 men bytte ut med pr-installasjonsurl.
Fixes NDLANO/Issues#3387
=> Returnerer 410 på gamle urler

src/containers/Masthead/drawer/ProgrammeMenu.tsx
Fixes https://trello.com/c/l8EAx86j/298-n%C3%A5r-jeg-er-p%C3%A5-et-utdanningsprogram-p%C3%A5-vg1-s%C3%A5-er-utdanningsprogrammet-valgt-i-menyen-men-velger-jeg-vg2-eller-vg3-s%C3%A5-er-det-ikke
=> Fix programme grade error in masthead drawer

src/containers/AllSubjectsPage/AllSubjectsPage.tsx
Det var etterlyst egen gruppe for andre ressurser på fagsida.
=> Added new collection of subjects

src/containers/ToolboxSubject/ToolboxSubjectContainer.tsx
Fixes https://github.com/NDLANO/Issues/issues/3405
=> Fix scrolling to toolbox topic

src/components/FeideLoginButton/FeideLoginButton.tsx, src/components/MyNdla/AddResourceToFolderModal.tsx, src/components/MyNdla/LoginComponent.tsx, src/components/MyNdla/LoginModal.tsx, src/containers/Masthead/MastheadContainer.tsx, src/containers/MyNdla/Folders/EditFolderModal.tsx, src/containers/MyNdla/MyNdlaPage.tsx, src/containers/MyNdla/components/DeleteModal.tsx, src/containers/Page/components/FeideFooter.tsx, src/containers/Resources/ResourcesTopicTitle.tsx, src/lti/components/LtiEmbedCode.tsx
Modal -> ModalV2. Dette gjør også at noen av modalene tar opp en del mindre plass. Test gjerne både på mobil og desktop.
=> Rewrite from Modal to ModalV2

src/containers/ErrorPage/__tests__/__snapshots__/ErrorPage-test.js.snap, src/containers/Page/components/Footer.tsx
Ny lenke i footer.
Fixes NDLANO/Issues#3417
=> Add new link

src/containers/AllSubjectsPage/utils.ts
Skjuler forklaringsfag fra alle fag
=> Filter forklaringsfag

src/config.ts
=> Change matomo address.

src/graphqlTypes.ts, src/schema.graphql
PR bestilt av @Jonas-C 📦 
Oppdaterer ndla frontend med nytt skjema fra graphql@master
=> Update gql schema

src/containers/Masthead/MastheadContainer.tsx
fixes https://github.com/NDLANO/Issues/issues/3440
Gjorde den avhengig av subjectId, testet den rundt omkring på nettsiden og ser ut som ønsket funksjonalitet kommer tilstedet med å gjøre det slikt.
=> Fixed masthead bug

src/App.tsx, src/graphqlTypes.ts, src/routes.tsx, src/schema.graphql
La til egen side for å vise innholdssideartikler. 
Eksemple: localhost:3000/p/jonas-er-min-test-idag-a
=> Added frontpagearticlePage

src/client.tsx, src/lti/LtiProvider.tsx
Fixes https://github.com/NDLANO/Issues/issues/3454
=> Set SameSite to lax when changing language

.babelrc, webpack/getConfig.ts, webpack/plugins.ts
Kan testes ved å lage en component selector i en styled component.
=> Changed babel setup to fix emotion component selectors

package.json, src/config.ts, src/server/helpers/Document.tsx, src/server/helpers/Matomo.tsx, src/server/helpers/Tagmanager.tsx, yarn.lock
Depends on https://github.com/NDLANO/frontend-packages/pull/1570 and https://github.com/NDLANO/deploy/pull/480
Legger til tagmanager for matomo.
=> Added tag-manager code

src/containers/SubjectPage/components/Topic.tsx
Kan testes på test.ndla.no/subject:8ede7bb4-be9e-4039-911c-e2d14f7c033d/topic:1a3140d7-3a78-4115-9466-a799c9b8de9f/
=> Do not show empty meta images on topic page

cypress/e2e/integration/search_page.spec.ts, src/components/FeideLoginButton/FeideLoginButton.tsx, src/components/MyNdla/LoginModal.tsx
Fikser sånn at login fra header sender deg til korrekt side.
=> Login fra masthead og footer sender deg til /minndla

src/containers/MyNdla/components/MyNdlaBreadcrumb.tsx, src/containers/MyNdla/components/TitleWrapper.tsx
https://trello.com/c/2fxzHLf8/293-st%C3%B8rre-klikkflate-p%C3%A5-tilbakeknappene-p%C3%A5-min-ndla
=> Make entire back button into a link on my ndla

src/containers/MyNdla/MyNdlaPage.tsx
https://www.figma.com/file/EqBVpeUUFZi258hkMQ8OOA/Min-NDLA?node-id=1497%3A22270&t=g445ZtVsbJIQomwx-0
Har avklart med Hedvig at vi skal beholde "Dette henter vi om deg" og diverse informasjon på bunnen av siden.
=> New look for My NDLA page

src/containers/MyNdla/FavoriteSubjects/FavoriteSubjectsPage.tsx, src/containers/MyNdla/MyNdlaLayout.tsx, src/containers/MyNdla/MyNdlaPage.tsx
https://trello.com/c/s9kRdXIo/321-favorittfag-i-min-ndla
=> Replace book open with menu book

cypress/tsconfig.json, package.json, src/containers/MyNdla/Folders/DraggableFolder.tsx, src/containers/WelcomePage/WelcomePage.tsx, yarn.lock
Reduksjon på rundt 1 sekund når man kjører `tsc`. Tar ikke inn noen særlig nye features nå, men tror det er litt nytt som kan hjelpe oss i fremtiden.
=> Typescript 5

src/components/VisualElement/VisualElementWrapper.tsx
Wrong translation key license heading
=>  button wrong translation key

src/containers/SharedFolderPage/SharedFolderPage.tsx, src/containers/SharedFolderPage/components/Folder.tsx, src/containers/SharedFolderPage/components/FolderResource.tsx
Fixes https://trello.com/c/G80ejp0b/332-endre-rekkef%C3%B8lge-trestruktur
=> Update folder preview list styling

src/containers/MyNdla/FavoriteSubjects/FavoriteSubjectsPage.tsx, src/containers/MyNdla/MyNdlaMobileMenuPage.tsx, src/containers/MyNdla/components/MyNdlaBreadcrumb.tsx
https://trello.com/c/czpLuHuO/337-favorittfag-er-borte-fra-menyen-p%C3%A5-mobilvisning
=> Improve mobile view for favorite subjects. Add it to the mobile menu

src/containers/SubjectPage/SubjectContainer.tsx, src/data/subjects.ts
Melding om kommende læreplaner er misvisende. Bedre å ikkje vise.
=> Fjerner beta-melding for kommende fag.

src/containers/SharedFolderPage/SharedFolderPage.tsx
https://trello.com/c/uxfJi6jk/344-endre-metatekst-p%C3%A5-delte-mapper
=> New meta description for shared folder

src/containers/FilmFrontpage/FilmFrontpage.tsx, src/containers/FilmFrontpage/NdlaFilmFrontpage.tsx
Nye slideshow forventer at man faktisk har data når den lastes. Viser en spinner inntil dataen er hentet.
=> Show a loading indicator in palce of the slideshow until data is ready

src/containers/Masthead/drawer/SubjectMenu.tsx, src/containers/Masthead/drawer/TopicMenu.tsx
Fixes NDLANO/Issues#3537
Test http://localhost:3000/subject:1:83ce68bc-19c9-4f2b-8dba-caf401428f21/topic:1ab90c95-899d-4009-967b-832772cd5bee/topic:fb060868-ad01-49e5-8312-38f708ddc630/resource:cc8681c1-80f7-416a-b3d5-5019e12c3113 og sjå at du kan klikke på meny uten at den krasjer.
=> Add extra null checks

src/containers/SharedFolderPage/components/FolderMeta.tsx
Ellers blir det veldig tomt på delingssida
=> Viser standardbeskrivelse dersom tom

src/config.ts, src/containers/MyNdla/Folders/DraggableFolder.tsx, src/containers/MyNdla/Folders/FolderActions.tsx, src/containers/MyNdla/Folders/FolderForm.tsx, src/containers/MyNdla/Folders/FoldersPage.tsx, src/containers/MyNdla/MyNdlaPage.tsx, src/containers/SharedFolderPage/components/FolderMeta.tsx
Endrer flagg for deling til å brukes for å skjule redigering av beskrivelse
=> Add flag to hide folder description

src/containers/AllSubjectsPage/AllSubjectsPage.tsx
Fixes https://github.com/NDLANO/Issues/issues/3546
Bruker samme scrolling-kode som vi har andre steder. Den er ikke veldig vakker, men den fungerer til formålet.
=> Scroll to heading on all subjecs page

src/containers/PlainArticlePage/PlainArticlePage.tsx, src/iframe/IframePage.tsx, src/server/routes/iframeArticleRoute.tsx
Fixes https://github.com/NDLANO/Issues/issues/3547
Får ikke gjort så mye med 410 når vi disabler SSR.
=> Set Redirect status to 410 when encountering a 410 from graphql

src/containers/AllSubjectsPage/AllSubjectsPage.tsx, src/containers/ProgrammePage/ProgrammeContainer.tsx, src/containers/SharedFolderPage/components/FolderMeta.tsx, src/containers/SharedFolderPage/components/SharedArticle.tsx
Fixes https://github.com/NDLANO/Issues/issues/3568
=> Add main element to remaining pages

src/containers/ArticlePage/ArticlePage.tsx
Kjem nok meir etter kvart, men dette er en start.
=> Add meta-tag to prepare for monsido.

src/containers/MyNdla/Folders/DragHandle.tsx
Tror aldri dette har funket. Kan teste forskjellen på dnd på mobil i test og mobil her.
=> Fix dnd on mobile on my ndla

src/containers/Masthead/MastheadContainer.tsx
Fixes https://trello.com/c/HNofLUCQ/13-endre-header
=> Always show search in masthead

src/components/MyNdla/AddEmbedToFolder.tsx
Fixes https://github.com/NDLANO/Issues/issues/3615
=> Fill out heart if embed is favorited

src/graphqlTypes.ts, src/schema.graphql
Depends on https://github.com/NDLANO/graphql-api/pull/335
=> Removing unused props from graphql.

src/components/MyNdla/AddEmbedToFolder.tsx
Fixes https://github.com/NDLANO/Issues/issues/3624
=> Fix article issue with filled favorite button on embeds

src/containers/PodcastPage/PodcastSeriesPage.tsx, src/graphqlTypes.ts, src/schema.graphql
Don't generate rss-feed url if hasRSS is false
Part of [#3514](https://github.com/NDLANO/Issues/issues/3514)
=> Generate and use hasRSS field and query #3514

src/containers/FilmFrontpage/NdlaFilmFrontpage.tsx, src/containers/SearchPage/searchHelpers.tsx, src/graphqlTypes.ts, src/queries.ts, src/schema.graphql
Henter skjema og bruker nye felt fra søkekontekster. Krever oppdatert graphql
=> Use new fields in context

src/config.ts, src/index.js, tsconfig.json, vercel.json
Ser ut til å fungere.
Går mer og mer mot rene serverless funksjoner virker det som, så ville ikke blitt mega overrasket om det plutselig ikke var mulig å gjøre sånne ting som det her uten å skrive handlere direkte for "endepunktene".
=> Attempt to fix vercel deployment :^)

src/containers/MovedResourcePage/MovedResourcePage.tsx, src/graphqlTypes.ts, src/queries.ts, src/schema.graphql
Oppdaga at brødsmulesti og path ikkje alltid henger sammen på side for flytta ressurs. Med dette gjør det det.
Sjekk at lenkene i bunn peiker på samme faget som oppgitt:
/subject:1:470720f9-6b03-40cb-ab58-e3e130803578/topic:2:a317f589-7995-43aa-8b68-92182c0b23c6/topic:1:35efa357-acc7-4828-b241-cad5467d1dc6/resource:1:168358?disableSSR=true
=> Use paths from contexts to be sure links to moved page is ok.

package.json, src/containers/FilmFrontpage/FilmFrontpage.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinarySubjectArticle.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopic.tsx, src/containers/SubjectPage/SubjectContainer.tsx, src/containers/SubjectPage/components/Topic.tsx, src/containers/ToolboxSubject/ToolboxSubjectContainer.tsx, src/containers/ToolboxSubject/components/ToolboxTopicWrapper.tsx, yarn.lock
Bumper prettier til ny major. Ikke noe breaking som påvirker oss ser det ut som.
=> Bump Prettier to 3.0.0

src/containers/MultidisciplinarySubject/MultidisciplinarySubjectPage.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryArticleList.tsx
illustration. Slightly modernize styling.
Reduserer bundle-size noe.
=> Move MultidisciplinarySubject component to frontend. Use static

src/components/MyNdla/AddResourceToFolder.tsx, src/containers/MyNdla/Folders/FolderForm.tsx, src/containers/MyNdla/Folders/FolderShareModal.tsx
Fixes https://github.com/NDLANO/Issues/issues/3625
=> Use light buttons instead of primary buttons for my ndla actions

src/containers/Masthead/drawer/DrawerRowHeader.tsx
Fixes https://github.com/NDLANO/Issues/issues/3673
=> Start-align text content on root drawer menu items

src/containers/WelcomePage/WelcomePage.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
Fixes https://github.com/NDLANO/Issues/issues/3674
Punkt 2 er fikset i frontend-packages, og kommer med neste pakkebump
=> Add bottom margin to Banner card. Change link translations from "Read more" to "view tips"

src/containers/SubjectPage/components/Topic.tsx
Fixes NDLANO/Issues#3676
Viser kun nederste nivå. 
Sammenlign feks /subject:1:6951e039-c23e-483f-94bf-2194a1fb197d/topic:c12f7a1f-4a4d-4e39-b362-48fc931df908/topic:46b003a6-5182-4afa-b809-913645c7a707/ i test og i pr-installasjon.
=> Only show lowest level of resources

src/containers/MyNdla/Folders/FoldersPage.tsx
fixes https://github.com/NDLANO/Issues/issues/3685
=> Fix copy to clipboard for shared folder not working

src/containers/WelcomePage/Components/Programmes.tsx, src/containers/WelcomePage/WelcomePage.tsx
fixes 
Forandret forsiden til å ta i bruk lister rundt programkortene.
=> Added ul and li around programmecards

src/containers/MyNdla/Folders/FolderActions.tsx
Da skal det være mulig å kopiere lenke når man går fra menyen på høyre side og!
=> Possible to copy link from menu

src/containers/Masthead/MastheadContainer.tsx, src/containers/Masthead/drawer/MastheadDrawer.tsx
Fixes https://github.com/NDLANO/Issues/issues/3693
Fikser også et lignende problem, bare med program-menyen.
=> Only show subject menu in drawer if subject id exists

package.json, yarn.lock
=> Bump typescript to 5.2

src/components/Article/ArticleContents.tsx, src/components/Learningpath/LearningpathEmbed.tsx, src/config.ts, src/containers/AboutPage/AboutPageContent.tsx, src/containers/ArticlePage/ArticlePage.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinarySubjectArticle.tsx, src/containers/MyNdla/Folders/FolderForm.tsx, src/containers/MyNdla/Folders/FoldersPage.tsx, src/containers/PlainArticlePage/PlainArticleContainer.tsx, src/containers/ResourceEmbed/components/ResourceEmbed.tsx, src/containers/SearchPage/SearchInnerPage.tsx, src/containers/SharedFolderPage/components/FolderMeta.tsx, src/containers/SharedFolderPage/components/SharedArticleContainer.tsx, src/server/contentSecurityPolicy.ts
=> Remove feature-flags not longer needed.

src/containers/ProgrammePage/ProgrammePage.tsx
Fixes https://github.com/NDLANO/Issues/issues/3704
=> Fallback to first grade if gradeParam has no matches

src/containers/SearchPage/SearchPage.tsx, src/containers/WelcomePage/WelcomePage.tsx
https://github.com/NDLANO/Issues/issues/3449
Usikker på om det er noe annet det er verdt å tracke her?
Ser forresten ikke ut som at vi klarer å logge bruker på første pageload, er det viktig?
=> Add tracking to search page and frontpage

src/components/TabFilter.tsx
Fixes https://trello.com/c/Y0FAruKM/430-fagvelger-gir-vertikal-scroll-i-400-view
=> Wrap subject tab filter on zoom

src/containers/Masthead/MastheadContainer.tsx
https://trello.com/c/NdcYCsxn/431-endre-aria-tag-p%C3%A5-logo-p%C3%A5-forsiden-slik-at-det-ikke-blir-redundans-med-skjult-h1
=> NDLA as logo label text

src/config.ts, src/server/helpers/Document.tsx
Fixes https://github.com/NDLANO/Issues/issues/3709
https://trello.com/c/pVj16YR5/410-monsido-tracking-i-body-tag
Tenkte det var greit å skru på dette med en env-variabel. Tror ikke token er farlig, så bryr meg ikke om at det blir dumpet til klient. Vil jo ligge i bundle uansett.
=> Add monsido

src/containers/SharedFolderPage/SharedFolderPage.tsx, src/containers/SharedFolderPage/components/SharedArticleContainer.tsx
Fixes https://github.com/NDLANO/Issues/issues/3712
Fixes https://trello.com/c/J0WBw7Cc/380-ogimg-for-delte-mapper
=> Set og:img from first resource with meta image

src/containers/MyNdla/FavoriteSubjects/FavoriteSubjectsPage.tsx, src/containers/MyNdla/Folders/FoldersPage.tsx, src/containers/MyNdla/MyNdlaPage.tsx, src/containers/MyNdla/Tags/TagsPage.tsx
Fixes https://github.com/NDLANO/Issues/issues/3449
https://trello.com/c/6RUMwRnA/119-minndla-feide-tette-m%C3%A5lehull
Den tracker ikke første page-view etter innlogging.
=> Add tracking to my ndla pages

src/containers/Resources/Resources.tsx
Denne koden er litt skummel. Prøver å gjøre den litt mindre skummel
=> Make resources rendering slightly faster

src/components/Article/Article.tsx, src/graphqlTypes.ts, src/schema.graphql
depends on https://github.com/NDLANO/graphql-api/pull/355
=> Add language as field on Article

src/containers/AllSubjectsPage/AllSubjectsPage.tsx, src/containers/AllSubjectsPage/SubjectCategory.tsx
Fixes https://trello.com/c/Y0FAruKM/430-fagvelger-gir-vertikal-scroll-i-400-view
=> Fix all subjects overflow on 400% zoom

src/config.ts, src/containers/MyNdla/MyNdlaPage.tsx
Fant ut at om eg går via config-objektet så fungerer filtreringa som den skal. Åpner for alle på test (og staging).
=> Add all fylker to filter in test and staging

src/containers/Resources/resourceApi.js, src/server/routes/__tests__/oembedArticleRoute-test.js
Ny versjon av Spring REST liker ikkje slashes på slutten av paths dersom dei ikkje trengs.
=> Loose trailing slashes

src/containers/AboutPage/AboutPageFooter.tsx, src/containers/FilmFrontpage/FilmFrontpage.tsx
Fixes https://github.com/NDLANO/Issues/issues/3760
Gjør dette ved å sjekke om metaImage er satt. Litt hacky
=> Filter out existing slideshow movies without existing article by

package.json, yarn.lock
Inn- og utlogging har aldri funket bedre.
Neida, det er helt likt.
=> Bump openid-client

src/containers/ResourceEmbed/components/ResourceEmbedWrapper.tsx
Fixes https://github.com/NDLANO/Issues/issues/3775
=> Fix heading style on embed resource page

src/containers/ResourceEmbed/components/ResourceEmbed.tsx, src/containers/SharedFolderPage/SharedFolderPage.tsx, src/containers/SharedFolderPage/components/SharedArticleContainer.tsx
Fixes https://github.com/NDLANO/Issues/issues/3771
=> Make page titles similar for articles and embeds

package.json, src/__tests__/_initTestEnv.js, src/__tests__/raf-polyfill.js, src/server/helpers/Document.tsx, src/server/helpers/__tests__/Document-test.js, src/server/helpers/__tests__/__snapshots__/Document-test.js.snap, src/server/routes/defaultRoute.tsx, src/server/routes/iframeArticleRoute.tsx, src/server/routes/iframeEmbedRoute.tsx, src/server/routes/ltiRoute.tsx, webpack/client.base.ts, yarn.lock
Vi polyfillet egentlig bare features fra IE11, og det er ikke særlig nødvendig lenger. Babel gjør uansett denne jobben for oss
=> Remove old polyfills

src/util/__tests__/apiHelpers-test.ts, src/util/apiHelpers.ts
=> Invert role check

src/components/AuthenticationContext.tsx, src/graphqlTypes.ts, src/schema.graphql
Depends on https://github.com/NDLANO/graphql-api/pull/375
=> Fix using correct types from graphql-api for configuration parameters

src/containers/ResourceEmbed/components/ResourceEmbed.tsx
Fixes NDLANO/Issues#3825
Fikser gloseside etter endring av graphq.
=> Adds gloss same way as podcast

src/util/getStructuredDataFromArticle.ts
Kom frem et ønske om å legge til url når et bilde er copyrighted: https://trello.com/c/waM4uBUK/474-bilder-leggje-til-metadata
=> Update licence for image copyright jsonld

src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts
Det kan hende fylkeskommuen har stengt tilgang til praterobotane. Me må vise varsel før dei prøver å komme seg til dei. Ikkje lagt inn varsel på messagesSE.ts
Bytta AI til KI.
=> ingen ki ved eksamen

src/containers/MyNdla/MyNdlaPage.tsx
Sjekka designet her:  https://www.figma.com/file/fyzyLEJ8GtOef12Ya3xAIz/MinNDLA-redesign?type=design&node-id=1-6&mode=design&t=CLrcDFTcGOqdcUHz-0
Alt av profilting ligger på profilsida, unntatt Spør NDLA, men den ligger på alle sider uansett.
=> Sletter profildata fra forsida min ndla.

src/containers/SubjectPage/components/SubjectLinks.tsx
Fjerner en feilmelding i konsollen
=> Remove key warning caused by sneaky fragment

src/containers/MyNdla/folderMutations.ts, src/containers/SharedFolderPage/SharedFolderPage.tsx, src/graphqlTypes.ts, src/schema.graphql
=> Show owner name on shared folder if it exists

src/containers/MyNdla/MyNdlaLayout.tsx, src/containers/MyNdla/components/NavigationLink.tsx
Fixes https://github.com/NDLANO/Issues/issues/3845
Legger ikke inn keyboard-navigasjon. Tror dette helt fint kan være en nav-liste, som da heller ikke trenger å støtte piltast-navigering.
=> Remove custom roles from my ndla navbar

src/messages/messagesNN.ts
Retta i samråd med språkmektige.
Dukkar opp om ein redigerer beskrivinga av ei delt mappe.
=> Beskrivelse-> Beskriving

src/containers/MyNdla/MyNdlaPage.tsx, src/containers/MyNdla/arenaQueries.ts, src/graphqlTypes.ts
Kan det være noen situasjoner der man har tilgang til ndla-frontend, men ikke å hente ting fra arena? Hvis nei, så er denne klar.
Avventer https://github.com/NDLANO/frontend-packages/pull/1992
=> Show recent topics on my ndla front page

src/containers/MyNdla/Arena/PostsPage.tsx, src/containers/MyNdla/Arena/components/PostCard.tsx, src/containers/MyNdla/arenaMutations.ts, src/containers/MyNdla/arenaQueries.ts, src/graphqlTypes.ts, src/schema.graphql, src/util/apiHelpers.ts
Avhengig av https://github.com/NDLANO/graphql-api/pull/406
=> Enable following and unfollowing topics

src/containers/SharedFolderPage/components/Folder.tsx
[https://trello.com/c/GFaE28Ng/544-minndla-klikk-p%C3%A5-delt-tittel-p%C3%A5-delt-mappe-kan-gjerne-utvide-opne-mappa](https://trello.com/c/GFaE28Ng/544-minndla-klikk-p%C3%A5-delt-tittel-p%C3%A5-delt-mappe-kan-gjerne-utvide-opne-mappa
)
=> Open shared folder on link click

src/containers/MyNdla/MyNdlaPage.tsx
=> Removing info texts from my page.

src/containers/MyNdla/Arena/components/ArenaCard.tsx
Fixes https://trello.com/c/BZVORQxk/565-kategorier-har-kun-ikon-ved-mouseover-p%C3%A5-mobil
=> Do not show arena icons on mobile

src/containers/MyNdla/MyNdlaLayout.tsx
Fixes https://trello.com/c/1X9f36rZ/572-feil-ikon-i-meny-p%C3%A5-mobil
=> Proper icon for mobile menu on my ndla

src/containers/MyNdla/Arena/components/ArenaForm.tsx
Minor adjustment i Arenaform for å få Information ikonet til å skalere bedre
=> Fixed styling of informationLabel icon on mobile

src/containers/MyNdla/MyProfile/components/MyPreferences.tsx
Fixes https://trello.com/c/UEG9waTZ/574-feedback-til-brukere-deling-av-mapper-med-uten-navn
=> Show snack when updating name preference

src/containers/MyNdla/components/SettingsMenu.tsx
Popover når du hoverer Settingsmeny
=> Add title attribute to SettingsMenu

src/containers/MyNdla/Arena/components/ArenaForm.tsx, src/containers/MyNdla/Arena/components/ArenaTextModal.tsx
https://trello.com/c/9uyGQ1Qe/583-teksteditor-modal-pixlepushing
Gjør Markdown-editoren litt mer compressed.
=> Markdown editor spacing

src/containers/MyNdla/Arena/components/FlagPostModalContent.tsx, src/containers/MyNdla/MyProfile/components/MyPreferences.tsx
Fikser: [Trello](https://trello.com/c/LuMrlGU1/536-ny-sidemal-min-profil)
=> wrapped RadioButtonGroup with form

src/containers/Masthead/MastheadContainer.tsx
Avhengig av https://github.com/NDLANO/frontend-packages/pull/2017
=> Show "Min NDLA" when logged in, and "Log in" when logged out

src/components/MarkdownEditor/EditorToolbar.tsx
https://trello.com/c/qTWdwtct/577-sett-inn-lenke-knapp-kan-ikke-n%C3%A5s-ved-tabulator
=> Make link button grey when disabled

src/containers/MyNdla/components/MenuModalContent.tsx
Skjuler arena-ikon på mobil. Deployer denne til prod snart.
=> Hides arena icon on mobile

src/components/MarkdownEditor/FloatingLinkEditorPlugin.tsx
Fixes https://github.com/NDLANO/Issues/issues/3855
=> Autofocus link editor when it appears

src/components/MarkdownEditor/MarkdownEditor.tsx, src/containers/MyNdla/Arena/components/ArenaForm.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
Trenger ikkje placeholdertekst
=> Remove placeholder from editor

src/containers/MyNdla/Arena/components/ArenaForm.tsx
[Trello task.](https://trello.com/c/Jm2LuL7T/606-feil-knappemodus-i-nytt-innlegg)
=> Changed color on LoadingButton to match design

src/containers/PodcastPage/PodcastSeriesPage.tsx, src/graphqlTypes.ts
Henter alt-tekst fra ed på podcast-serie.
=> Viser alt-tekst fra ed på serie.

src/containers/MyNdla/ArenaUserPage.tsx, src/routes.tsx
fixes https://github.com/NDLANO/Issues/issues/3863
=> Added correct userpage routes. Fixed navigation when reloading

src/containers/MyNdla/Arena/components/PostCard.tsx
Viser dato på hovedposten. Viser også tidsstempel som title på span.
I henhold til oppdatert design.
=> Viser tidsstempel på hovedpost

src/components/MarkdownEditor/MarkdownEditor.tsx, src/containers/MyNdla/Arena/components/ArenaForm.tsx
fixes https://github.com/NDLANO/Issues/issues/3869
Gjett om jeg var naiv da jeg trodde `markdownToString` metoden skulle være snill med meg!!
=> Made content counter only count characters/text content and not markdown

src/containers/MyNdla/Arena/components/FlagPostModalContent.tsx
=> Add flag modal title translation

src/containers/MyNdla/Arena/components/ArenaForm.tsx
Mikroendring for å fikse https://trello.com/c/Y1cuCzUU/613-ulike-hjelpetekster-til-samme-felt
=> novalidate gjør at nettleser ikkje viser tooltips

src/containers/MyNdla/components/MyNdlaPageWrapper.tsx
Fixes https://trello.com/c/0YZP7RyW/626-arena-legg-til-landemerke-main
Wrapper content i main og ikkje div
=> Adds main in page wrapper

src/components/license/AudioLicenseList.tsx, src/components/license/ConceptLicenseList.tsx, src/components/license/H5pLicenseList.tsx, src/components/license/ImageLicenseList.tsx, src/components/license/PodcastLicenseList.tsx, src/components/license/TextLicenseList.tsx, src/components/license/VideoLicenseList.tsx, src/components/license/licenseStyles.tsx
Fjerner litt klassenavn som https://github.com/NDLANO/frontend-packages/pull/2039 fjerner korresponderende scss for.
=> Medialist to emotion

src/components/Article/Article.tsx, src/iframe/__tests__/__snapshots__/IframeArticlePage-test.tsx.snap, src/util/transformArticle.ts
https://github.com/NDLANO/Issues/issues/3856
=> Set 'no' when article langage is 'nb' for improved accessibility

src/containers/AllSubjectsPage/SubjectCategory.tsx
bare en liten console error fiks
=> refactored to remove console error

src/containers/MyNdla/MyNdlaLayout.tsx, src/containers/MyNdla/MyNdlaPage.tsx
=> My NDLA text bug

src/containers/MyNdla/components/NotificationList.tsx
https://trello.com/c/mYeoujOS/602-lest-ulest-vises-kun-med-prikk-og-veldig-lys-bl%C3%A5
=> Update not viewes notification colors

src/containers/ErrorPage/ErrorPage.tsx, src/containers/Page/Layout.tsx, src/iframe/EmbedIframePageContainer.tsx, src/iframe/IframePageContainer.tsx, src/lti/LtiIframePage.tsx, src/lti/LtiProvider.tsx, src/server/helpers/__tests__/Document-test.js, src/server/helpers/__tests__/__snapshots__/Document-test.js.snap
Oppdaterer lang attributt på html-element, ser ut som at det skal holde å sette her!
https://trello.com/c/iyFj1tC7/592-uu-endre-span-nb-til-span-no
=> Update html lang attribute

src/containers/MyNdla/Arena/ArenaPage.tsx, src/containers/MyNdla/Arena/components/ArenaCard.tsx
Skjuler antall innlegg i kategori for å unngå at sletta innlegg roter med antallet.
=> Do not show topic count on category.

src/containers/SubjectPage/components/Topic.tsx, src/containers/ToolboxSubject/components/ToolboxTopicWrapper.tsx
=> H2 for resources

src/containers/ResourceEmbed/components/ResourceEmbed.tsx
Det er en ekstra border på "Regler for bruk" _Accordion_ [Trello](https://www.figma.com/file/jiZ86RzWFZZZHrjZUse866/NDLA-pages?node-id=3145%3A53461&mode=dev)
=> delete extra border

src/containers/MyNdla/Arena/components/ArenaForm.tsx
Hedvig vil ha en beskjed om man overskriver 32000 ord så da legger vi inn det 👯
=> Maxlength rule arenaform

src/containers/Resources/ResourcesTopicTitle.tsx
fikser: [#3913](https://github.com/orgs/NDLANO/projects/2/views/9?pane=issue&itemId=50361059)
=> add focus to switch component

.github/workflows/ci.yml, package.json, yarn.lock
=> Set version to 4.1.0

src/containers/MyNdla/MyNdlaPage.tsx
Bytter om lister, ref https://trello.com/c/AMDxwkcS/739-min-ndla-bytte-plass-p%C3%A5-nylig-lagt-til-i-mine-mapper-og-nye-innlegg-i-arenaen
=> Change order of lists on myndla page

src/components/FeideLoginButton/FeideLoginButton.tsx, src/containers/MyNdla/Arena/components/ArenaCard.tsx, src/containers/MyNdla/Arena/components/TopicCard.tsx, src/containers/MyNdla/components/Avatar.tsx, src/containers/MyNdla/components/MyContactArea.tsx, src/containers/MyNdla/components/UserAvatar.tsx, src/containers/MyNdla/components/UserProfileTag.tsx
Gjør noen endringer i et forsøk på å gjøre accessibility bedre:
- Min NDLA / Login-knappen hadde feil tekst
- Antall svar / innlegg og teksten "svar" / "innlegg" ble lest opp hver for seg
- Gjemt noen avatarer som kun er dekorative, og ikke hadde annen funksjon (og som dermed er med på å hindre bruker fra å effektivt finne relevant sideinnhold).
=> Some accessibility changes

src/graphqlTypes.ts, src/queries.ts
=> Remove frontpage search query

src/containers/MyNdla/Arena/PostsPage.tsx, src/containers/MyNdla/Arena/components/ArenaForm.tsx, src/containers/MyNdla/Arena/components/PostCard.tsx
Fixes https://github.com/NDLANO/Issues/issues/3969
=> Adding a reply field at the bottom of the topic page

src/containers/Masthead/drawer/AboutMenu.tsx, src/containers/Masthead/drawer/MastheadDrawer.tsx
Fikser to bugs i menyen:
- Flaky oppførsel når man gikk et par nivå ned og prøvde gå helt ut igjen (tilbake-knappen til rotnivået ble ikke-responsiv)
- Tom og stygg meny når menu array er tomt
=> Menu bugfixes

src/components/Article/Article.tsx, src/components/CompetenceGoals.tsx, src/components/MyNdla/AddResourceToFolderModal.tsx, src/containers/SubjectPage/SubjectContainer.tsx
Kommer mer senere, men tar det i en annen PR.
=> Fetch less data

src/containers/PodcastPage/PodcastSeriesListPage.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
Subnivå på podkastlister for å ha h1 > h2 > h3
=> Adding h2 subtitle to podcast list.

package.json, yarn.lock
Fikser typefeil 'Element is not assignable to type ReactNode.'
=> Bump react types

src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopicWrapper.tsx
Bilder skal nå dukke opp på 
https://ndla-frontend-pr-1795.ndla.sh/subject:d1fe9d0a-a54d-49db-a4c2-fd5463a7c9e7/topic:077a5e01-6bb8-4c0b-b1d4-94b683d91803/topic:6edcd362-b2b5-4d30-80e3-9b0164b352e1/
=> Include subtopics fetch when on third level of multidisciplinary

src/server/api.ts
Dette er en branch fra versjonen i prod slik at vi kan få ut denne fort. Commit er henta fra #1803
=> Use correct path to file

src/containers/MyNdla/components/Toolbar.tsx
Skjuler toolbar dersom man ikke er logget inn.
=> Only show toolbar when logged in

src/server/api.ts
Fikser det slik at utlogging fra /minndla fører deg til forsida.
=> Compare with basepath to redirect to frontpage

src/components/SocialMediaMetadata.tsx, src/containers/MyNdla/MyNdlaPage.tsx
Litt meir luft.
Fikser også twitter-bilde metatag.
=> Adds gap between sections

src/server/contentSecurityPolicy.ts
http://localhost:3000/article/38623
=> Add uio to csp

src/config.ts
Flag for redesign av folder, gjør det lettere å sammenkjøre dette for meg å john'ern
=> Added folder redesign environment

src/containers/SharedFolderPage/components/Folder.tsx
fikser: [Trello](https://trello.com/c/RmfnX26M/817-minndla-delte-mapper-venstrejuster-mappenamn)
Kan testes i Daniel sine delte mapper
=> made text alight left and button will keep min-width

src/components/DefaultErrorMessage.tsx, src/containers/AccessDeniedPage/AccessDeniedPage.tsx, src/containers/ErrorPage/__tests__/__snapshots__/ErrorPage-test.tsx.snap, src/containers/FilmFrontpage/AboutNdlaFilm.tsx, src/containers/NotFoundPage/NotFoundPage.tsx, src/containers/SearchPage/SearchPage.tsx, src/iframe/IframePage.tsx, src/iframe/__tests__/__snapshots__/IframeArticlePage-test.tsx.snap
`clear` og `clear-desktop` ser ikke ut til å gjøre stort.
=> Remove all OneColumn css modifiers, expect for wide

src/components/Learningpath/Learningpath.tsx, src/containers/LearningpathPage/LearningpathPage.tsx, src/containers/PlainLearningpathPage/PlainLearningpathContainer.tsx
Fikser [#4019](https://github.com/orgs/NDLANO/projects/2/views/9?pane=issue&itemId=61418428)
Snakket med Hedvig og hu ville fjerne muligheten å navigere mellom stier med høyre og venstre tastatur tastene. Læringssti skal få en makeover etterhvert og da blir det annerledes uansett
=> Learningpath navigation bug

src/containers/FilmFrontpage/FilmFrontpage.tsx, src/containers/FilmFrontpage/FilmMovieSearch.tsx
Det ser ikke helt likt ut; Overskriften er mindre og marginer/paddinger er litt forskjellige. Er dette likt nok?
=> Move FilmMovieSearch to ndla-frontend

src/components/Article/ArticleContents.tsx, src/components/TabFilter.tsx, src/components/Topic/TopicMetaImage.tsx, src/containers/AllSubjectsPage/AllSubjectsPage.tsx, src/containers/Masthead/components/MastheadSearch.tsx, src/containers/MultidisciplinarySubject/Illustrations.tsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectHeader.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopic.tsx, src/containers/MyNdla/InfoPart.tsx, src/containers/MyNdla/MyProfile/components/MyPreferences.tsx, src/containers/MyNdla/components/SettingsMenu.tsx, src/containers/MyNdla/components/UserInfo.tsx, src/containers/ResourcePage/ResourcePage.tsx, src/containers/WelcomePage/Components/Programmes.tsx, src/containers/WelcomePage/WelcomePage.tsx, src/lti/components/LtiBasicLaunch.tsx
Tok i bruk spacing og misc verdier noen steder. Fjernet noen tomme spaces i import listen
=> Small clean up in code

src/containers/Masthead/MastheadContainer.tsx
Lager release fra branch og legger i staging.
=> Send reactnode to Masthead to display rendered html

.github/workflows/ci.yml, Dockerfile, README.md, package.json, yarn.lock
Fixes Snyk vulnurability https://security.snyk.io/vuln/SNYK-ALPINE318-OPENSSL-6593964
=> Upgrade node to 20.13.1

src/components/Learningpath/LastLearningpathStepInfo.tsx, src/components/Learningpath/Learningpath.tsx
Litt opprydning, men ikke noe drastisk.
=> Learning path cleanup

package.json, src/containers/MyNdla/Arena/ArenaPage.tsx, src/containers/MyNdla/Arena/CategoryEditPage.tsx, src/containers/MyNdla/Arena/NewCategoryPage.tsx, src/containers/MyNdla/Arena/NewTopicPage.tsx, src/containers/MyNdla/Arena/PostsPage.tsx, src/containers/MyNdla/Arena/TopicPage.tsx, src/containers/MyNdla/Arena/components/ArenaCard.tsx, src/containers/MyNdla/Arena/components/ArenaCategoryForm.tsx, src/containers/MyNdla/Arena/components/DeleteCategoryModal.tsx, src/containers/MyNdla/Arena/components/SortableArenaCards.tsx, src/containers/MyNdla/Arena/components/temporaryNodebbHooks.ts, src/containers/MyNdla/arenaMutations.ts, src/containers/MyNdla/arenaQueries.ts, src/containers/MyNdla/nodebbQueries.ts, src/graphqlTypes.ts, src/schema.graphql, yarn.lock
Depends on https://github.com/NDLANO/backend/pull/447
Depends on https://github.com/NDLANO/graphql-api/pull/454
Legger til støtte for underkategorier (både nodebb og ikke).
=> Implement subcategories for arena

src/containers/SearchPage/SearchContainer.tsx
fikser [#4042](https://github.com/orgs/NDLANO/projects/2/views/9?pane=issue&itemId=63094245)
kan testes på [localhost](http://localhost:3000/search?query=fjell&selectedFilters=topic-article%2Clearning-path)
=> adjust filter logic to show selected filter even if there are no resources

src/containers/SubjectPage/components/TopicWrapper.tsx, src/util/handleError.ts
messages even if the error was a 5xx
=> Fix naive 404 error handling for TopicWrapper, causing 404 return

src/containers/AllSubjectsPage/SubjectCategory.tsx
Fikser: [#4045](https://github.com/orgs/NDLANO/projects/2/views/9?pane=issue&itemId=63914287)
=> add width so that subject text doesnt wrap

src/components/Learningpath/Learningpath.tsx
Fikser: [#4037](https://github.com/orgs/NDLANO/projects/2/views/9?pane=issue&itemId=62963698)
Virker som det beste stedet å legge til width for å fikse varierende bredde problemet. Fant også en liten feil med top padding i samme sleng
=> added width to learningpath container div

src/components/Learningpath/LastLearningpathStepInfo.tsx
Fixes https://github.com/NDLANO/Issues/issues/4048
=> Added space above the last step-block in learningpaths

src/containers/ErrorPage/ErrorPage.tsx, src/containers/ErrorPage/__tests__/__snapshots__/ErrorPage-test.tsx.snap
https://github.com/NDLANO/Issues/issues/4052
=> Replace Content component with plain div. It does nothing but provide a class

src/containers/ErrorPage/__tests__/__snapshots__/ErrorPage-test.tsx.snap, src/containers/Masthead/components/Masthead.tsx
https://github.com/NDLANO/Issues/issues/4052
=> Do not use classname for masthead

src/containers/Page/Layout.tsx
=> Remove another Content component

src/containers/MyNdla/Arena/ArenaToolbar.tsx, src/containers/MyNdla/Arena/components/ArenaForm.tsx, src/containers/MyNdla/FavoriteSubjects/FavoriteSubjectsPage.tsx, src/containers/MyNdla/Folders/FolderButtons.tsx, src/containers/MyNdla/Folders/FolderCreateModal.tsx, src/containers/MyNdla/Folders/FolderDeleteModal.tsx, src/containers/MyNdla/Folders/FolderEditModal.tsx, src/containers/MyNdla/Folders/FoldersPageTitle.tsx, src/containers/MyNdla/components/NotificationButton.tsx, src/containers/MyNdla/components/toolbarStyles.ts
Det eneste som er "ordentlig" skrevet om her er notifikasjons-knappen. Sørget for at tallet som indikerer uleste notifikasjoner legger seg enklere på både venstre og høyre side.
=> Remove even more css usage

src/containers/MyNdla/Folders/FolderList.tsx, src/containers/MyNdla/folderMutations.ts, src/graphqlTypes.ts, src/schema.graphql
Caching sluttet å fungere på rot nivå for mapper. Det var jo min feil så her er en løsning for å håndtere cachingen mot det problemet.
=> Fixed the cache logic for root folders after folder return type change

src/containers/MyNdla/folderMutations.ts, src/containers/SharedFolderPage/components/SaveLink.tsx, src/graphqlTypes.ts, src/schema.graphql
Renamed favoriteSharedFolder for better consistency. Added method for unfavoriting a shared folder.
=> Legger til støtte for å fjerne favoritisering av en delt mappe

src/server/contentSecurityPolicy.ts
https://trello.com/c/Z7DtDFFd/877-godta-flere-domener-som-embed-url
=> Support some more urls for embeds

src/util/handleError.ts, vite.config.ts
Legger til støtte for safari < 16.
=> Lower es-version to es2020.

src/App.tsx
Fixes NDLANO/Issues#4073
Min PR#2000
Gjør at lagra urler til mappe med ressursid funker. Testes med http://localhost:3000/nb/folder/9a939e4a-e47c-4891-8f51-16b974962389/9a939e4a-e47c-4891-8f51-16b974962389/d8229082-3c96-4e37-af98-9c5488d84713
=> Catch extra info in folder-url

src/components/MyNdla/LoginComponent.tsx, src/components/TabFilter.tsx, src/containers/AllSubjectsPage/AllSubjectsPage.tsx, src/containers/AllSubjectsPage/FavoriteSubjects.tsx, src/containers/AllSubjectsPage/LetterNavigation.tsx, src/containers/AllSubjectsPage/SubjectCategory.tsx, src/containers/AllSubjectsPage/SubjectLink.tsx, src/containers/AllSubjectsPage/utils.ts, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
Skriver om Alle fag-siden til panda/nytt design.
**NB:** En ting jeg er usikker på er hvordan mobilvisning skal se ut, jeg syntes ikke den selecten som ble vist istedenfor TagFilter var nødvendig, så den fjernet jeg, men jeg tror kanskje vi burde vurdere å gjøre noe med bokstav-filteret i mobilvisning (?). Kom gjerne med innspill! eventuelt om det finnes noe design på det?
=> All subjects page

src/components/Article/ArticleContents.tsx, src/containers/MultidisciplinarySubject/components/MultidisciplinaryTopic.tsx, src/containers/SubjectPage/SubjectContainer.tsx, src/containers/SubjectPage/components/SubjectTopic.tsx
Ser ikke helt likt ut, men det tenker jeg går fint. SubjectPage skal skrives om uansett!
=> Remove article header wrapper usage

e2e/specs/unauthenticated/frontpage.spec.ts, e2e/specs/unauthenticated/subjects.spec.ts, e2e/specs/unauthenticated/topicMenu.spec.ts, package.json, src/components/MediaList/LicenseBylineDescriptionList.tsx, src/containers/PodcastPage/PodcastSeriesPage.tsx, src/containers/ResourceEmbed/components/ResourceEmbed.tsx, src/containers/SubjectPage/components/TopicVisualElementContent.tsx, src/containers/WelcomePage/Components/Programmes.tsx, src/containers/WelcomePage/WelcomePage.tsx, src/iframe/__tests__/__snapshots__/IframeArticlePage-test.tsx.snap, yarn.lock
Ny accordion! 
NB: Jeg har ikke lagt all verdens innsats i innholdet i accordion på forsiden, så det får vi justere når vi vet designet der!
NB2: Skrev om forsiden til panda, men ikke tilpasset noe mer etter designet, tenker det burde være en egen PR (?)
=> New Accordion

src/containers/Masthead/MastheadContainer.tsx, src/containers/Masthead/components/MastheadSearch.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
Denne er ikke 100% lik designet, men tenker at vi kanskje skal ta inn denne som en midlertidig første versjon? Vil gjerne kvitte meg med de gamle komponentene i ndla/ui.
Mangler fortsatt litt småplukk, men vil gjerne ha et review allerede nå!
Tror blant annet jeg skal teste list-komponenten og `composite`-propen.
=> Initial version of masthead combobox

src/components/MovedNodeCard.tsx, src/containers/MovedResourcePage/MovedResourcePage.tsx, src/containers/SearchPage/searchHelpers.tsx, src/containers/SubjectPage/SubjectPage.tsx, src/containers/SubjectPage/components/MovedTopicPage.tsx
Ikke noe design på dette, kommer rett fra hjertet. Kan sjekke hvordan det ser ut på http://localhost:3000/subject:1:9b7e7534-c072-4412-b8ef-df076308cad0/topic:4b7655b2-ae2f-4231-8124-569fe6d97bd6/resource:65771aa8-492f-4a94-8910-2a7d64c4d20b.
Kommer nok til å introdusere en variant av card som ikke har noe hover-effekt for situasjoner som dette.
=> Replace old SearchResultList component with a styled version of Card

src/containers/ErrorPage/__tests__/__snapshots__/ErrorPage-test.tsx.snap, src/containers/Masthead/components/Masthead.tsx
Flytter/skriver om MessageBanner til panda + skriver om Masthead til panda
=> Converted Masthead to panda. Updated MessageBanner.

src/components/CompetenceGoals.tsx
Fikser at riktig tab vises default her feks: localhost:3000/subject:1:470720f9-6b03-40cb-ab58-e3e130803578/topic:1:a317f589-7995-43aa-8b68-92182c0b23c6/topic:1:35efa357-acc7-4828-b241-cad5467d1dc6/resource:1:168362
=> Fix competenceGoals tabs default value

src/components/MyNdla/AddResourceToFolder.tsx, src/components/MyNdla/CopyFolder.tsx, src/containers/MyNdla/MyNdlaLayout.tsx, src/containers/ProgrammePage/ProgrammeContainer.tsx, src/containers/SearchPage/components/SubjectFilter.tsx, src/containers/SharedFolderPage/components/FolderMeta.tsx, src/containers/SharedFolderPage/components/SaveLink.tsx, src/containers/SubjectPage/SubjectContainer.tsx
Tar i bruk ny MessageBox
**NB:** For å holde det likt som tidligere satte jeg variant til warning på de uten noe variant fra før, det er mulig noen av disse kanskje burde være info-varianten istedet?
=> Use new MessageBox from @ndla/primitives

src/components/MyNdla/AddResourceToFolder.tsx, src/components/MyNdla/CopyFolder.tsx, src/containers/AllSubjectsPage/SubjectLink.tsx, src/containers/MyNdla/Arena/PostsPage.tsx, src/containers/MyNdla/Arena/components/DeleteCategoryModal.tsx, src/containers/MyNdla/Arena/components/FlagPostModalContent.tsx, src/containers/MyNdla/Arena/components/MainPostCard.tsx, src/containers/MyNdla/Arena/components/PostCard.tsx, src/containers/MyNdla/Arena/components/UserProfileAdministration.tsx, src/containers/MyNdla/Folders/FoldersTagPage.tsx, src/containers/MyNdla/Folders/components/DraggableResource.tsx, src/containers/MyNdla/Folders/components/FolderActions.tsx, src/containers/MyNdla/Folders/components/FolderButtons.tsx, src/containers/MyNdla/Folders/components/FolderShareModal.tsx, src/containers/SharedFolderPage/components/SaveLink.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
fixes https://github.com/NDLANO/Issues/issues/4090
**NB1:** Ser ikke ut som komponenten støtter å sende inn jsx-elementer, så måtte fjerne dette fra `AddResourceToFolder`
**NB2:** Mulig det er flere steder jeg burde ta i bruk kombinasjon av title/description (?)
=> New Toast component

package.json, src/containers/FilmFrontpage/Carousel.tsx, src/containers/FilmFrontpage/FilmMovieList.tsx, src/containers/FilmFrontpage/FilmSlideshow.tsx, yarn.lock
Lot stylingen være, bare skrev den over til panda. Denne carouselen blir sikkert kanskje bytta ut med noe fra Ark når de kommer med en ferdig laga en :^)
=> Moved Carousel to Ndla-Film. Refactored the code to panda

e2e/specs/unauthenticated/search.spec.ts, src/containers/SearchPage/components/SearchResultItem.tsx, src/containers/SearchPage/searchHelpers.tsx
første del av denne: https://github.com/NDLANO/Issues/issues/4088
**NB1:** Jeg var usikker på hva jeg skulle gjøre med den nederste teksten fra designet(Fag > emne > underemne), så det er utelatt inntil videre
**NB2:** Usikker på `LTIWrapper` og hvordan det kan testes evt, la todo på det!
=> Use new Card component for SearchResultItem

src/components/license/ConceptLicenseList.tsx
Fixes https://github.com/NDLANO/Issues/issues/4083
Kan verifiseres med /subject:1:8c5a9fdd-4fa4-456b-9afe-34e7e776b4e7/topic:5a2a8f85-cbf6-4f24-8311-404f30c38c02/resource:29474e43-eeb4-45aa-be4a-4450cf9c98f7 på localhost
=> Remove Download

src/containers/Masthead/components/SkipToMainContent.tsx
Fixes https://github.com/NDLANO/Issues/issues/4119
=> Add new SkipLink

src/containers/MyNdla/Folders/components/FolderForm.tsx
Ser litt bedre ut med textarea :^)
=> Changed folder description to textarea

src/containers/SharedFolderPage/SharedFolderPageV2.tsx
FIxes https://github.com/NDLANO/Issues/issues/4110
=> Fix hydration error on shared folder page

src/containers/SharedFolderPage/SharedFolderPageV2.tsx
fixes https://github.com/NDLANO/Issues/issues/4120
Feil plassering av en `)`
=> Fixed logical fault in containsFolder logic

src/containers/Masthead/drawer/MastheadDrawer.tsx
fixes https://github.com/NDLANO/Issues/issues/4106
Tror dette blir en bedre løsning. Problemet var at siden ikke hadde en breadcrumb å basesre seg på. Legger til førstenivå about som fallback
=> Added fallback menu option

package.json, src/components/Topic/TopicMetaImage.tsx, src/containers/MyNdla/Folders/components/FolderShareModal.tsx, src/containers/MyNdla/Folders/components/ListViewOptions.tsx, yarn.lock
Midlertidige løsninger på knapper :')
=> Remove remaining usage of ndla/button and ndla/tooltip

src/components/NavigationBox.tsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectPage.tsx, src/containers/Page/Layout.tsx, src/containers/ProgrammePage/ProgrammeContainer.tsx, src/containers/SubjectPage/components/SubjectPageContent.tsx, src/containers/ToolboxSubject/ToolboxSubjectContainer.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
Som skrevet i tittel; Tok litt forskjellige ting når jeg først var i gang med fagsiden. Er en viss fare for at NavigationBox skal vekk etterhvert (eller endres drastisk), så rører ikke altfor mye med den. 
Fjerner BottomPadding da det ikke lenger virker som at det er en faktisk fasit på hva den skal være. Da er det like greit å style det per side. På sikt kan vi legge det inn igjen. Legger til i tracking issue.
=> Refactor programmes, remove bottom padding and lightly refactor NavigationBox

src/components/MyNdla/AddResourceToFolder.tsx, src/components/MyNdla/AddResourceToFolderModal.tsx, src/containers/MyNdla/Folders/FoldersTagPage.tsx, src/containers/MyNdla/Folders/components/DraggableResource.tsx, src/containers/MyNdla/MyNdlaPage.tsx, src/containers/SharedFolderPage/SharedFolderPage.tsx, src/util/folderHelpers.tsx
Fixes https://github.com/NDLANO/Issues/issues/4128
=> Properly extract multidisciplinary resource type everywhere resources are used

src/components/MyNdla/AddResourceToFolder.tsx, src/components/MyNdla/CopyFolder.tsx, src/components/MyNdla/FolderSelect.tsx, src/containers/MyNdla/Arena/components/AlertModal.tsx
Dropper også litt delt styling. Det eneste det fører til er tregere bundling og circular dependencies :')
=> AddResourceFolder: Replace emotion with panda

src/containers/MyNdla/Folders/components/ListViewOptions.tsx, src/containers/MyNdla/components/MenuModalContent.tsx
Det går faktisk an å vise kort-versjonen av ressurser i Min NDLA på mobil nå. Da ser jeg ingen grunn til å ikke tillate det.
=> Always show all list options

src/containers/MyNdla/components/NotificationButton.tsx
Hadde egentlig tenkt å ta hele popoveren, men ser ut som at Gaute har begynt litt på den.
=> Rewrite notification button

src/containers/MyNdla/Folders/components/DraggableResource.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
fixes https://github.com/NDLANO/Issues/issues/4114
Improvisert hvordan dette ser ut, gjerne kom med innspill om noen har!
=> Add menu option to show resource tags in dialog

src/components/TabFilter.tsx
=> Use fieldset components for labelling tab filter

src/components/CompetenceGoals.tsx, src/containers/AllSubjectsPage/LetterNavigation.tsx
=> Fix LetterNavigation transition + remove icon in CompetenceGoals dialog

src/containers/ErrorPage/__tests__/__snapshots__/ErrorPage-test.tsx.snap, src/containers/Page/components/Footer.tsx
Fixes https://github.com/NDLANO/Issues/issues/4141
=> Make footer logo printer friendly

src/containers/MyNdla/Arena/components/temporaryNodebbHooks.ts, src/containers/MyNdla/ArenaUserPage.tsx, src/containers/MyNdla/components/UserProfileTag.tsx, src/containers/MyNdla/nodebbQueries.ts, src/graphqlTypes.ts, src/schema.graphql
Depends on https://github.com/NDLANO/graphql-api/pull/480
Denne koden blir bare styggere og styggere så lenge løsningene får leve side by side.
Vi bør nok bestemme oss for en av de relativt snart spør du meg.
Blir synd å slette den koden som åpenbart hadde fungert best, men om det er det ndla vil så tenker jeg at vi bør gjøre det fremfor å vedlikeholde det monsteret her lenge nok til at det blir stress å fjerne igjen.
=> Fetch arena user by id and allow missing user on posts

src/containers/ErrorPage/ErrorPage.tsx, src/containers/ErrorPage/__tests__/__snapshots__/ErrorPage-test.tsx.snap
Skjønner egentlig ikke helt hvorfor vi har en ZendeskButton her? Noen som har peiling?
=> Make ErrorPage use panda

src/containers/AllSubjectsPage/AllSubjectsPage.tsx
Samme logikk som på søkesiden at default valg alltid er valgt
=> Update all subjects page filtering logic

src/components/Article/Article.tsx, src/components/Article/articleHelpers.ts, src/containers/ArticlePage/ArticlePage.tsx
Er ikke lett dette med ny ressurs-seksjon.
Dette skal være klin likt som å bruke `Article` fra `Article.tsx ` og `Article` fra frontend-packages. Gi meg kjeft dersom det ikke stemmer.
=> Give article resources section a background color

src/containers/MyNdla/Arena/ArenaAdminPage.tsx, src/containers/MyNdla/Arena/ArenaFlagPage.tsx, src/containers/MyNdla/Arena/ArenaUserListPage.tsx, src/containers/MyNdla/Arena/components/AdminNavLink.tsx
Tilsvarende som for profile page. Eneste mål med denne er å skrive ut emotion + gamle Text og Heading-komponenter.
=> Get rid of emotion in admin page

src/lti/components/LtiBasicLaunch.tsx, src/lti/components/LtiDeepLinking.tsx, src/lti/components/LtiDefault.tsx
Oppdaterer LTI-knappene. Kan testes med saLTIre ved å gjøre følgende ting:
* Oppdatere "Message URL" under "Security Model"
* Endre message type under "Message".
=> Refactor LTI buttons

src/containers/MyNdla/Arena/components/PostAction.tsx, src/containers/MyNdla/Folders/components/FolderActions.tsx
Oppdaterer til henhold til designet
=> Updated settingsmenu icons

src/containers/MyNdla/Folders/components/FolderForm.tsx, src/containers/MyNdla/components/FieldLength.tsx
=> Updated styling new folder modal

src/containers/MyNdla/Folders/components/ListViewOptions.tsx
Har prøvd å finne andre steder `IconButton` skal være liten men fant ingen. Venter til i morgen for å dobbeltsjekke med Hedvig
=> change icon button size 

src/components/ContentPlaceholder.tsx, src/containers/AboutPage/AboutPage.tsx, src/containers/MultidisciplinarySubject/MultidisciplinarySubjectArticlePage.tsx, src/containers/PlainArticlePage/PlainArticlePage.tsx, src/containers/PodcastPage/PodcastSeriesPage.tsx, src/containers/ResourcePage/ResourcePage.tsx
Fixes https://github.com/NDLANO/Issues/issues/4149, men kommer nok til å kreve et par oppfølgnings-PR'er. Vi har en del forskjellige loading-behavior rundt omkring.
=> Refactor ContentPlaceholder to align more closely with PageContent

src/App.tsx, src/server/api.ts
https://github.com/NDLANO/Issues/issues/4146
=> Redirect /utdanning route

src/components/NavigationSafeLinkButton.tsx, src/containers/ProgrammePage/ProgrammeContainer.tsx, src/containers/ProgrammePage/ProgrammePage.tsx
Ser ikke fantastisk ut med de gamle bildene, men alt skal være på plass
=> New iteration of the Programme page

src/containers/Masthead/MastheadContainer.tsx
Liten ikon fix i masthead. Skal vise et annet ikon hvis brukeren er pålogget
=> change icon if user is logged in

src/containers/SearchPage/components/SearchHeader.tsx, src/containers/SearchPage/components/SearchResults.tsx
fixes https://github.com/NDLANO/Issues/issues/4153
=> Add skip to content to search page

src/components/NavigationBox.tsx, src/components/NavigationSafeLinkButton.tsx, src/containers/AboutPage/AboutPageFooter.tsx, src/containers/ProgrammePage/ProgrammeContainer.tsx, src/containers/SubjectPage/components/SubjectPageContent.tsx, src/containers/SubjectPage/components/SubjectTopic.tsx
Fixes https://github.com/NDLANO/Issues/issues/4154
=> Use aria-current for NavigationSafeLinkButton instead of aria-selected

src/containers/SubjectPage/SubjectRouting.tsx
Fixes https://github.com/NDLANO/Issues/issues/4161
=> fix: Add key to SubjectPage usage to avoid sharing data between different subject pages

src/containers/AllSubjectsPage/AllSubjectsPage.tsx
Lik oppførsel som filter på søkesiden!
=> Update all subjects page filter to behave as search page filter

src/containers/Resources/Resources.tsx
fikser [trello](https://trello.com/c/erD8JDqX/32-launchpad-overskrift-og-underline)
- la til border bottom under tittel
- la til litt space mellom tittel og border
- justerte gap på første elementet
=> fix: adjust launchpad design

src/components/TabFilter.tsx, src/containers/AllSubjectsPage/AllSubjectsPage.tsx, src/containers/AllSubjectsPage/utils.ts, src/containers/FilmFrontpage/FilmFrontpage.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
Oppdaterer filtre på alle fag siden til å oppføre seg som radiobuttons etter beskjed fra Hedvig!
=> Update filter behaviour on all subjects page

src/containers/ArticlePage/ArticlePage.tsx, src/containers/Resources/ResourceItem.tsx, src/containers/Resources/ResourceList.tsx, src/containers/Resources/Resources.tsx
https://trello.com/c/Nt70hNpa/68-feil-farge-p%C3%A5-hover-selcted-p%C3%A5-oppgaver-og-aktiviteter
=> Update ListItem color theme

src/components/SocialMediaMetadata.tsx
https://trello.com/c/ehVjTaMf/919-metatags-fjerne-twitterspesifikke-meta-tags
=> Use opengraph metas only

src/containers/SearchPage/components/SearchResultItem.tsx
Unngår at "+ 4 flere steder" står inni brødsmulestien.
=> Adding 4 pixels spacing before dialog to show more contexts

e2e/specs/unauthenticated/topic.spec.ts, src/containers/SubjectPage/components/SubjectTopic.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
Fikser siste punkt i https://trello.com/c/5xY2A3cb/13-transportside-typografi
=> chore: update topic title translation

src/containers/Resources/ResourceItem.tsx
Som Johannes ba om, kun vis label om tilleggstoff.
https://trello.com/c/xFSwODi9
=> Only show label for additional

src/components/FavoriteSubject.tsx, src/containers/AllSubjectsPage/SubjectLink.tsx, src/containers/SubjectPage/SubjectContainer.tsx
https://trello.com/c/oF3uREBx/70-favorittmarkering-av-fag-p%C3%A5-fagsidene
=> Add possibility to favorite subject from subject page

src/containers/MyNdla/Arena/ArenaNotificationsPage.tsx, src/containers/MyNdla/components/NotificationButton.tsx, src/containers/MyNdla/components/NotificationList.tsx, src/containers/MyNdla/components/NotificationPopover.tsx
Tror ikke design var helt på plass ennå da dette ble gjort. Har duplisert litt logikk for å gjøre a11y på popoveren litt bedre.
=> Match notifications to design

src/containers/MyNdla/Arena/ArenaSingleFlagPage.tsx, src/containers/MyNdla/Arena/components/FlagCard.tsx, src/containers/MyNdla/Arena/components/FlaggedPostCard.tsx
Litt duplisert stil fra `MainPostCard`, men det går kanskje fint?
=> feat: refactor flag page

src/containers/MyNdla/Arena/ArenaAdminPage.tsx, src/containers/MyNdla/Arena/ArenaFlagPage.tsx, src/containers/MyNdla/Arena/ArenaPage.tsx, src/containers/MyNdla/Arena/ArenaUserListPage.tsx, src/containers/MyNdla/Arena/CategoryEditPage.tsx, src/containers/MyNdla/Arena/NewCategoryPage.tsx, src/containers/MyNdla/Arena/NewTopicPage.tsx, src/containers/MyNdla/Arena/TopicPage.tsx, src/containers/MyNdla/Arena/components/AdminNavLink.tsx, src/containers/MyNdla/Arena/components/SortableArenaCards.tsx
Prøver å unngå alt pirk-arbeidet vi kommer til å få når de skal teste arena
=> chore: make page layouts more like the design

src/containers/FilmFrontpage/AboutNdlaFilm.tsx, src/containers/FilmFrontpage/FilmContentCard.tsx
Skal være siste del av denne: https://trello.com/c/QSuoBvAb/23-bildehj%C3%B8rner-mangler-avrunding
=> Rounded image corners

src/components/NavigationSafeLinkButton.tsx
https://trello.com/c/fRFlAxCn/87-tekst-i-emneknapp-m%C3%A5-venstrestilles
=> Fix text placement in NavigationSafeLinkButton

src/containers/MyNdla/Folders/FoldersPage.tsx, src/containers/MyNdla/components/NavigationLink.tsx
Avventer egentlig en pakke-bump, men dette er uansett mer riktig enn det som er i dag.
=> chore: make tags and navigation links yellow (my ndla color)

src/components/MyNdla/ListResource.tsx, src/containers/Resources/ResourceItem.tsx, src/containers/SearchPage/components/SearchResultItem.tsx
Fikser https://trello.com/c/oftL19UC/80-uu-launchpad-feil-alt-tekst-p%C3%A5-thumbs
=> Do not show alt for image in launchpad

src/components/Topic/Topic.tsx
https://trello.com/c/c2vRS05H/97-lange-ord-i-tittel-sprenger-emneingress-slik-at-den-ikke-kan-leses
=> Hyphens with loooooong titles

src/containers/Masthead/components/MastheadSearch.tsx
fikser https://trello.com/c/TFpelgKd/88-tekst-i-s%C3%B8keresultat-m%C3%A5-venstrestilles og skriver om til å bruke ListItem i Masthead
=> Use ListItem in MastheadSearch + left align text

src/components/MyNdla/FolderSelect.tsx, src/components/MyNdla/TreeStructure.tsx
Fixes https://github.com/NDLANO/Issues/issues/4175
Løste gåten til Katrine. Vi kommer ikke til å bruke denne utenfor ndla-frontend, vil jeg tro.
=> Move tree structure over

src/components/license/ImageLicenseList.tsx, src/components/license/VideoLicenseList.tsx, src/containers/ResourceEmbed/components/ResourceEmbedLicenseContent.tsx
Håper vi har bestemt oss for godt nå 😅
[trello](https://trello.com/c/a7UjVLWZ/24-sitere-eller-gjenbruke-bilder-mangler-bilde)
=> added back images to image and video licenses

src/components/MyNdla/BlockWrapper.tsx, src/components/MyNdla/Folder.tsx, src/components/MyNdla/ListResource.tsx, src/containers/MyNdla/Arena/components/ArenaListItem.tsx, src/containers/MyNdla/Folders/FoldersPage.tsx, src/containers/MyNdla/Folders/FoldersTagPage.tsx, src/containers/MyNdla/Folders/components/DraggableResource.tsx, src/containers/MyNdla/Folders/components/ListViewOptions.tsx, src/containers/MyNdla/Folders/components/ResourceList.tsx, src/containers/MyNdla/components/DragHandle.tsx, src/containers/Resources/ResourceItem.tsx, src/containers/SharedFolderPage/SharedFolderPage.tsx
Fikser https://trello.com/c/a960RntN/77-klipping-av-tittel-i-stedet-for-oppg
Klin umulig å skalere disse ordentlig. Tror dette er bedre enn det var, men gjerne gi kjeft om noe kan være bedre (eller om noe er feil).
=> List resource scaling

src/components/MarkdownEditor/FloatingLinkEditorPlugin.tsx
https://trello.com/c/3FGv1L8S/98-vindu-for-%C3%A5-legge-inn-lenke-i-innlegg-p%C3%A5-arenaen-henger-igjen
Måtte til litt justering for å få denne til å plassere seg fint rett under ordet.
=> Fix floating link position after creation.

src/containers/SearchPage/SearchContainer.tsx, src/containers/SearchPage/components/SearchResults.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
=> Add fieldset/legend to searchPage checkbox-groups

src/containers/FilmFrontpage/AboutNdlaFilm.tsx
Sikkert fint at den ikke tar all plassen den kan få.
=> chore: treat ndla film article more like an actual article by wrapping it in PageContent

src/containers/MyNdla/components/SettingsMenu.tsx
Fikser både i toolbar og på selve liste-itemet.
=> fix: properly return focus to settings menu dropdown trigger when closing a dialog

src/containers/AllSubjectsPage/LetterNavigation.tsx
Tar i bruk SafeLinkIconButton i LetterNavigation. 
**NB:** Skal sjekke opp om det er OK for Hedvig at de blir litt mindre + skal sjekke hvordan det ser ut på mobil!
=> Use SafeLinkIconButton in LetterNavigation

src/containers/Masthead/drawer/DrawerMenuItem.tsx, src/containers/Masthead/drawer/DrawerPortion.tsx, src/containers/Masthead/drawer/SubjectMenu.tsx
=> feat: support showing current indicators for masthead subjects, topic and resources

src/components/license/PodcastLicenseList.tsx
fixes https://github.com/NDLANO/Issues/issues/4178
tror dette er alt som skal til (?)
=> Possible to add podcasts to my ndla

package.json, src/components/Learningpath/LearningpathEmbed.tsx, src/containers/ArticlePage/ArticlePage.tsx, src/iframe/IframeArticlePage.tsx, src/util/transformArticle.ts, yarn.lock
Kan testes med https://github.com/NDLANO/editorial-frontend/pull/2453
=> feat: add content type to some article transforms

src/components/FeideLoginButton/FeideLoginButton.tsx, src/containers/Masthead/MastheadContainer.tsx, src/containers/Masthead/components/MastheadSearch.tsx, src/containers/Masthead/drawer/MastheadDrawer.tsx
Prøver å gjøre ting litt likere designet. Hedvig har gitt tommel opp!
Fixes https://github.com/NDLANO/Issues/issues/4151
=> fix: scale down masthead buttons on smaller screens

src/containers/MyNdla/Folders/components/FolderForm.tsx, src/containers/SharedFolderPage/SharedFolderPage.tsx
https://trello.com/c/LM0KW3PV/135-endre-tekst-i-modal-for-mapper-ta-bort-siste-linje
relatert til https://github.com/NDLANO/frontend-packages/pull/2510
=> Update folder description

src/containers/SearchPage/components/SearchHeader.tsx
Fixes https://trello.com/c/guaVm3Qp/136-mangler-mellomrom-mellom-tekst-og-foresl%C3%A5tt-ord-s%C3%B8kesiden
=> fix: add some margin before search suggestion

src/containers/MyNdla/Arena/components/ArenaListItem.tsx
https://trello.com/c/LAiUZ6gF/140-padding-arenacard
=> Make count in arena cards take same amount of space

src/components/license/LicenseBox.tsx, src/iframe/__tests__/__snapshots__/IframeArticlePage-test.tsx.snap
Legger til mer padding for lisensboks. ([Trello](https://trello.com/c/jyTZRka0/16-sitere-eller-gjenbruke-padding))
=> Add more license box padding

src/components/Learningpath/Learningpath.tsx, src/containers/ErrorPage/ErrorPage.tsx, src/containers/ErrorPage/__tests__/__snapshots__/ErrorPage-test.tsx.snap, src/containers/LearningpathPage/LearningpathPage.tsx, src/containers/MovedResourcePage/MovedResourcePage.tsx, src/containers/PlainLearningpathPage/PlainLearningpathContainer.tsx, src/containers/ResourceEmbed/components/ResourceEmbed.tsx, src/containers/SharedFolderPage/SharedFolderPage.tsx, src/containers/SubjectPage/components/MovedTopicPage.tsx, src/lti/LtiProvider.tsx
fixes https://github.com/NDLANO/Issues/issues/4174
Har ikke greit å finne flere som mangler main!
=> Add main element to learning path

src/containers/MyNdla/components/Toolbar.tsx
kommentar her: https://trello.com/c/Dad6oeIW/121-feil-str-pa-knapper-i-toolbar-min-ndla#comment-66fd03318bd13912f42b8601
=> Update padding toolbar

src/components/Topic/Topic.tsx
fikser https://trello.com/c/bcs6p4pZ/158-ulik-m%C3%A5te-%C3%A5-vise-overskrift-i-emneartikkel-noen-ganger-venstrejustert-andre-ganger-kanskje-midtstilt
=> Make header fill width

src/containers/MyNdla/Arena/components/FlaggedPosts.tsx, src/containers/MyNdla/Arena/components/Users.tsx
fixes https://github.com/NDLANO/Issues/issues/4183
=> add wordbreak to arena admin page

src/containers/SubjectPage/components/TopicVisualElementContent.tsx
fikser https://trello.com/c/6G03Q6SS/154-fjerne-bildetekst-p%C3%A5-emnesider
=> Hide image caption on topicVisualElement

src/containers/SubjectPage/components/TopicVisualElementContent.tsx
=> hideCaption is to be removed. Remove text instead

src/containers/MyNdla/Folders/components/DraggableFolder.tsx, src/containers/MyNdla/Folders/components/FolderList.tsx, src/containers/MyNdla/folderMutations.ts, src/graphqlTypes.ts, src/schema.graphql
Fixes https://github.com/NDLANO/Issues/issues/4172
Fikser så sortering av lagrede delte mapper fungerer :nerd_face: 
Depends on https://github.com/NDLANO/graphql-api/pull/490
Depends on https://github.com/NDLANO/backend/pull/528
=> Add support for sorting saved shared folders

src/containers/FilmFrontpage/AboutNdlaFilm.tsx
https://trello.com/c/s2HfWqjD/1025-iframe-p%C3%A5-ndla-film-m%C3%A5-ha-title
=> Show title for iframe on filmfrontpage

src/containers/MyNdla/Arena/components/SortableArenaCards.tsx, src/containers/MyNdla/Folders/components/FolderList.tsx, src/containers/MyNdla/Folders/components/ResourceList.tsx
fikser https://trello.com/c/dkVwmsrA/161-uu-minndla-folders
=> Made context wrap lists they are defining a context for

src/containers/Masthead/components/MastheadSearch.tsx, src/containers/SearchPage/SearchInnerPage.tsx, src/containers/SearchPage/SearchPage.tsx, src/containers/SearchPage/components/SearchHeader.tsx
fikser https://trello.com/c/wHej4PNL/160-legg-til-s%C3%B8k-heller-ordforslag-i-masthead
=> Add search phrase and suggestion to masthead search

src/lti/LtiProvider.tsx
fixes https://github.com/NDLANO/Issues/issues/4072
Tenkte sessionstorage er bedre en localstorage da vi sikkert ikke vil lagre dette gjennom flere sessions 🤔
=> Add searchparams in sessionstorage when searching

package.json, yarn.lock
Hadde ikke kjempetroa på at issuet mitt skulle ha noe å si, men de var rett på ball 😄
=> Bump `express-prom-bundle`

src/components/Scripts/Formbricks.tsx, src/components/Scripts/Scripts.tsx, src/config.ts, src/server/contentSecurityPolicy.ts
Legger til formbricks.
Fixes NDLANO/Issues#4188
=> Add formbricks script

src/containers/SearchPage/components/SearchResultItem.tsx
Mindre (småere) bilder i søkeresultat.
=> Stop fetching images at 1440 for search-results

src/containers/Masthead/components/MastheadSearch.tsx
fixes https://github.com/NDLANO/Issues/issues/4193
=> Added else if statement for handling onEnter when highlighted value

src/containers/PodcastPage/PodcastSeriesListPage.tsx, src/containers/PodcastPage/PodcastSeriesPage.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
https://trello.com/c/PrE08HNb/1072-landingsside-podkast-oppdatere-metatekst
=> Adds new description to podcastspage

src/server/api.ts
Fikser innlogging i feide på vercel.
=> Only sets dot-cookie if on ndla.no domain

src/util/sentry.ts
Ser at vi får ganske mange av disse.
Antar det skjer av "naturlige årsaker" og ikke noe vi kan fikse (Extensions, nettverksbytter, etc...)
Ikke at det er noe informasjon i de som hjelper oss å finne ut av det either way.
=> Sentry: Filter network errors that don't provide information

src/util/getStructuredDataFromArticle.ts
https://trello.com/c/kcvbDfbF/1095-frontend-brightcove-uploaddate-manglar-tidssone
=> Do not format video date

src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts
Robotlandskapet har endra seg. Tekstane må oppdaterast. Sjekka av språk.
=> Oppdatert kampanjeblokk minndla for robotar

src/containers/MyNdla/Arena/components/ArenaListItem.tsx
=> Fix ListItemContent items alignment

src/containers/MyNdla/components/NavigationLink.tsx
Dette unngår bare en irriterende typefeil som kommer fra https://github.com/NDLANO/frontend-packages/pull/2568
=> fix: restrict navigation link "to" type to string.

src/containers/MyNdla/MyNdlaPage.tsx
=> fix: only slice favorite subjects if they exist

src/App.tsx, src/components/NavigationBox.tsx, src/constants.ts, src/containers/CollectionPage/CollectionPage.tsx, src/graphqlTypes.ts, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts, src/routes.tsx
Bittelitt avhengig av https://github.com/NDLANO/frontend-packages/pull/2586
=> feat: add CollectionPage

src/containers/MyNdla/MyNdlaLayout.tsx
=> Fix shortName typo

src/server/api.ts, src/util/handleError.ts
Legger også til litt utvidet logging for `AggregateError` siden jeg har sett den litt i loggene uten noe mer info.
=> Return 400 for OPError

.github/workflows/ci.yml, package.json, src/containers/PodcastPage/PodcastSeriesListPage.tsx, yarn.lock
Måtte oppdatere yarn for å få dette til å funke ordentlig.
=> chore: bump typescript to 5.6

src/config.ts, src/containers/MyNdla/MyNdlaLayout.tsx, src/containers/MyNdla/MyNdlaPage.tsx, src/containers/MyNdla/components/NavigationLink.tsx
Setter EXTERNAL_ARENA i config-map for test slik at NDLA kan ha brukertest i test.
=> Display external arena for test

src/containers/ProgrammePage/ProgrammeContainer.tsx
Oppdaget denne mens jeg testet med skjermleser
=> Update GradesList aria-label

src/config.ts, src/server/api.ts, src/server/routes/forwardingRoute.ts
Christian ønsker at vi går all in på nye urler i det vi skrur det på.
=> Use only one flag for pretty urls

src/containers/Masthead/components/MastheadSearch.tsx
Fixes https://github.com/NDLANO/Issues/issues/4225
=> fix: use standalone ComboboxContent in Masthead

src/containers/AllSubjectsPage/AllSubjectsPage.tsx, src/containers/AllSubjectsPage/utils.ts, src/util/runQueries.ts
We should never end up with `any`
=> chore: require generics to be passed into `useGraphQuery`.

e2e/apiMock.ts, src/containers/MyNdla/Arena/components/AlertModal.tsx, src/containers/MyNdla/Arena/components/ArenaForm.tsx, src/containers/MyNdla/Arena/components/DeleteCategoryModal.tsx, src/containers/SearchPage/components/SubjectFilter.tsx
ESLint mener dette er bedre, og jeg er egentlig enig.
=> refactor: do not perform function calls / logic in ternary operators

src/components/AlertsContext.tsx, src/components/MarkdownEditor/MarkdownEditor.tsx, src/server/server.ts
Kan argumentere for at noen av disse kan fjernes
=> chore: suppress console wherever it is used

e2e/apiMock.ts, src/components/MarkdownEditor/FloatingLinkEditorPlugin.tsx, src/components/MarkdownEditor/RefPlugin.tsx, src/containers/ErrorPage/ErrorBoundary.tsx, src/containers/SearchPage/SearchInnerPage.tsx, src/server/contentSecurityPolicy.ts, src/server/server.ts
=> chore: remove redundant parameters

src/containers/CollectionPage/CollectionPage.tsx, src/containers/LearningpathPage/LearningpathPage.tsx, src/containers/MyNdla/MyNdlaPage.tsx, src/containers/PlainLearningpathPage/PlainLearningpathContainer.tsx, src/containers/TopicPage/MultidisciplinarySubjectArticle.tsx, src/containers/TopicPage/TopicContainer.tsx
https://trello.com/c/ys3DkCM6/1132-meta-ogtitle-dobbel-ndla
=> fix: never duplicate ` - ndla` in page titles, meta titles or og:titles

src/components/Learningpath/LearningpathMenu.tsx, src/components/MyNdla/BlockWrapper.tsx, src/components/TransportationPage/TransportationPageNodeListGrid.tsx, src/containers/Resources/ResourceList.tsx, src/containers/TopicPage/MultidisciplinaryArticleList.tsx
Johannes hadde ønsker om at listene våre skulle bli mer strukturerte et par steder. Tok der jeg følte det ga mening.
=> fix: use ol where appropriate

src/components/ContentTypeFallbackIcon.tsx, src/containers/FilmFrontpage/Carousel.tsx, src/containers/Masthead/drawer/DrawerMenuItem.tsx, src/containers/Masthead/drawer/DrawerRowHeader.tsx
=> chore: remove some unused props

src/containers/Masthead/drawer/DefaultMenu.tsx
fixes https://github.com/NDLANO/Issues/issues/4222
=> MastheadDrawer: Render link directly if menu item has no children

src/containers/ArticlePage/ArticlePage.tsx, src/containers/TopicPage/MultidisciplinarySubjectArticle.tsx
Disse ble glemt ifbm. https://github.com/NDLANO/Issues/issues/4219
=> remove references to removed property "license" from ArticleByline

package.json, yarn.lock
De påstår at det er litt raskere!
=> chore: bump typescript to 5.7

public/static/h5p-resizer.js, src/util/getArticleScripts.ts
Fixes https://github.com/NDLANO/Issues/issues/4236
=> fix: use local h5p resizer to support edlib2

src/containers/ErrorPage/__tests__/__snapshots__/ErrorPage-test.tsx.snap, src/containers/Page/components/Footer.tsx
Usikker på om det skal vere slik full url.
=> Ny url til nyhetsbrev

src/components/license/AudioLicenseList.tsx, src/components/license/ConceptLicenseList.tsx, src/components/license/ImageLicenseList.tsx, src/components/license/PodcastLicenseList.tsx, src/components/license/VideoLicenseList.tsx
Vi må lagre relative pather for alt.
=> Only save relative resources

src/containers/CollectionPage/CollectionPage.tsx, src/containers/ProgrammePage/ProgrammeContainer.tsx
Fixes https://github.com/NDLANO/Issues/issues/4180
=> fix: set intrinsic image sizes on programme and collection pages

src/client.tsx
Når det er sagt: Vi krasjer på både emnesider og ressurssider både med og uten dette. Tar det som neste greie
=> refactor: do not use a memory router for google translate. It makes no difference

src/util/__tests__/sentry-test.ts, src/util/sentry.ts
Fant disse i sentry i tillegg til den som allerede var definert.
=> Ignore known errors when sending to sentry

src/containers/ArticlePage/ArticlePage.tsx, src/containers/SubjectPage/SubjectPage.tsx, src/containers/TopicPage/TopicPage.tsx, src/server/routes/contextRedirectRoute.ts
Burde fikse dei fleste 500 feila fra ndla-frontend!
=> Fiks diverse 500 feil i logger

src/components/AlertsContext.tsx, src/containers/MyNdla/components/Toolbar.tsx
Fjerne muligheten til å vise alerts i lokal arena om ekstern skal brukes
=> Hide alerts popover if external arena

src/containers/Masthead/drawer/DefaultMenu.tsx
=> fix: do not spread key onto a component. It's not valid in react

src/util/logger/winston.ts
Småflaut når feilhåndteringen vår tryner
=> fix: do not assume that extras exists

src/App.tsx, src/containers/MyNdla/Learningpath/LearningpathFormButtonContainer.tsx, src/containers/MyNdla/Learningpath/SaveLearningpathPage.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
Er to TODOs i koden dere gjerne kan ta stilling til.
=> feat: learningpath save step

src/App.tsx, src/components/Learningpath/Learningpath.tsx, src/components/Learningpath/LearningpathMenu.tsx, src/components/Learningpath/learningpathUtils.ts, src/containers/LearningpathPage/LearningpathPage.tsx, src/containers/MyNdla/Learningpath/PreviewLearningpathPage.tsx, src/containers/PlainLearningpathPage/PlainLearningpathContainer.tsx, src/graphqlTypes.ts, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts, src/routeHelpers.tsx
Lurer på om vi skal ta inn denne før jeg ser videre på å fikse forhåndsvisning av tekst- og external-steg. Er med andre ord ikke så stort poeng i å poengtere feil i de typene steg
=> feat: add learningpath preview

src/components/Learningpath/Learningpath.tsx
https://trello.com/c/OxyMO3bB/1183-l%C3%A6ringssti-p%C3%A5-ndla-h2-f%C3%B8r-h1
=> Use span for accordion root

src/containers/TopicPage/MultidisciplinarySubjectArticle.tsx
=> Add heart button to multidisciplinary cases

src/components/license/VideoLicenseList.tsx
Kan sjekkes på http://localhost:3000/r/matematikk-1t/implikasjon/7d5e384b32
Avhengig av https://github.com/NDLANO/graphql-api/pull/532
=> Adds displaying origin for video.

src/containers/MyNdla/Learningpath/EditLearningpathStepsPage.tsx, src/containers/MyNdla/Learningpath/EditLearningpathTitlePage.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
Legger til bedre brødsmuler for redigering av læringssti
=> Added breadcrumbs to edit title and edit steps

src/messages/messagesNB.ts, src/messages/messagesNN.ts
@AVNDLA og underteikna har retta litt i tekstane.
=> Læringssti25 tekst

.github/workflows/release.yml, package.json, src/server/api.ts, yarn.lock
Burde kanskje gått via graphql-api? Funker i det minste.
=> Check myndla-api for user before creating cookie

src/components/Article/Article.tsx
Som kommentert på her: https://trello.com/c/CTuiM1cN/1167-merking-av-tilgjengelighet
Legger til visning av disclaimer for plain artikkel-visning, iframe og i læringssti-visning
=> Show disclaimer in Article

src/components/Disclaimer.tsx
Oppdatering i henhold til design!
=> Show disclaimer in article in dialog

src/containers/AboutPage/AboutPageContent.tsx, src/containers/ArticlePage/ArticlePage.tsx, src/containers/CollectionPage/CollectionPage.tsx, src/containers/LearningpathPage/LearningpathPage.tsx, src/containers/PlainArticlePage/PlainArticleContainer.tsx, src/containers/PlainLearningpathPage/PlainLearningpathContainer.tsx, src/containers/SubjectPage/SubjectContainer.tsx, src/containers/TopicPage/MultidisciplinarySubjectArticle.tsx, src/containers/TopicPage/TopicContainer.tsx, src/iframe/IframeArticlePage.tsx, src/util/trackingUtil.ts
Only care about user dimensions
https://trello.com/c/LPdD8Nsm/1178-m%C3%A5ling-rydde-i-custom-dimentions
=> Only send fylke and rolle to matomo

src/messages/messagesNB.ts, src/messages/messagesNN.ts
Små tekstjusteringar frå språkfolka.
=> Prøv robotane våre

src/App.tsx, src/routes.tsx
Denne skal heite saming og ikkje collection
=> Change path for collection

src/containers/MyNdla/Learningpath/EditLearningpathStepsPage.tsx, src/containers/MyNdla/Learningpath/components/LearningpathStepForm.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
https://trello.com/c/oUeUhgM3/1194-legg-til-innhold-st%C3%A5r-to-steder
=> learningpath: remove redundant info text

src/components/TransportationPage/TransportationPageNodeListGrid.tsx
Sammenlign http://localhost:3000/e/matematikk-1p-y---na/algoritmer-og-programmering-python/f35acd9db7 med tilsvarende i test på mobil eller smale skjermer.
=> Handle grids on smaller screens

src/containers/AboutPage/AboutPageContent.tsx, src/containers/ArticlePage/ArticlePage.tsx, src/containers/TopicPage/MultidisciplinarySubjectArticle.tsx
=> Make parallax work on article-page

src/containers/ResourcePage/ResourcePage.tsx, src/containers/TopicPage/TopicPage.tsx
Tillat 404 ved henting av node.
=> Handle 404 from tax

src/containers/MyNdla/Learningpath/components/TextForm.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
https://trello.com/c/aU4ARnWr/1216-oppdatere-tekst-nederst-n%C3%A5r-man-deler-eget-innhold#
=> Learningpath: Add copyright info in TextForm

src/containers/MyNdla/Learningpath/components/ImagePicker.tsx, src/containers/MyNdla/imageQueries.tsx, src/graphqlTypes.ts, src/schema.graphql
Begrenser metabilder til kun være cc by sa
=> Limit imagesearch to CC-BY-SA-4.0

src/components/Learningpath/Learningpath.tsx, src/components/Learningpath/components/CopyLearningPath.tsx, src/components/MyNdla/ListResource.tsx, src/components/MyNdla/LoginModalContent.tsx, src/containers/MyNdla/Learningpath/learningpathMutations.ts, src/graphqlTypes.ts, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts, src/schema.graphql
depends on https://github.com/NDLANO/graphql-api/pull/542, https://github.com/NDLANO/graphql-api/pull/544
fixes https://github.com/NDLANO/Issues/issues/4275
https://trello.com/c/OG8IX8pN/1215-l%C3%A6ringssti-knapp-for-kopier-til-egen-mappe
=> Add functionality to copy learning path

src/components/MediaList/MediaList.tsx, src/iframe/__tests__/__snapshots__/IframeArticlePage-test.tsx.snap
Fikser https://trello.com/c/mW2TED9Y/1160-lisenstekst-kommer-dobbelt
=> Only show rights if more than one

src/containers/MyNdla/Learningpath/components/LearningpathStepForm.tsx
Fixes https://trello.com/c/lGtlRPoj/1257-validering-i-min-ndla
=> fix: disable native validation for learning path forms

src/containers/MyNdla/Learningpath/EditLearningpathStepsPage.tsx, src/containers/MyNdla/Learningpath/components/LearningpathStepForm.tsx, src/containers/MyNdla/Learningpath/components/LearningpathStepListItem.tsx, src/containers/MyNdla/Learningpath/types.ts, src/containers/MyNdla/Learningpath/utils.ts, src/util/guards.ts, src/util/handleError.ts
=> Improve learningpath form typing

src/containers/MyNdla/Learningpath/components/ExternalStepForm.tsx
=> Adds error for checkbox

src/client.tsx, src/components/SiteThemeContext.tsx, src/containers/ErrorPage/ErrorEntry.tsx, src/containers/ErrorPage/__tests__/__snapshots__/ErrorPage-test.tsx.snap, src/containers/Page/components/Footer.tsx, src/containers/WelcomePage/WelcomePage.tsx, src/interfaces.ts, src/server/render/defaultRender.tsx, src/server/render/errorRender.tsx, src/util/siteTheme.ts
Avhengig av https://github.com/NDLANO/frontend-packages/pull/2711
=> add dynamic color to welcomepage and footer

src/components/CompetenceGoalTab.tsx
Fikser p tags her: https://test.ndla.no/r/religion-og-etikk/sikhismen---menneskesyn/797ae96668
=> Handles p-tags from grep for core elements

src/components/RichTextEditor/plugins/link/LinkElement.tsx, src/containers/MyNdla/Learningpath/EditLearningpathStepsPage.tsx, src/containers/MyNdla/Learningpath/components/LearningpathStepForm.tsx, src/containers/MyNdla/Learningpath/components/LearningpathStepListItem.tsx, src/containers/MyNdla/Learningpath/components/TextStepForm.tsx
Med gammelt oppsett klarte vi ikke å fjerne slate fra hoved-bundle, da vi brukte det delvis når vi serialiserte/deserialiserte.
=> fix: lazy load more to ensure that slate is only loaded when needed

src/containers/MyNdla/Learningpath/components/FolderStepForm.tsx, src/containers/MyNdla/Learningpath/types.ts, src/containers/MyNdla/Learningpath/utils.ts
Glemte å legge til denne i form-typen!
=> Also handle folder form in toFormValues

src/containers/MyNdla/Learningpath/components/LearningpathStepForm.tsx
Fikser https://trello.com/c/oKbWft7A/1264-dobbelklikket-p%C3%A5-neste-og-samme-ressurs-ble-lagt-til-to-ganger
=> Prevent double save of step

src/containers/MyNdla/Learningpath/components/FolderResourcePicker.tsx, src/containers/MyNdla/folderMutations.ts, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
Tredje punkt her: https://github.com/NDLANO/Issues/issues/4292
=> Error handling in folder resource picker

src/containers/CollectionPage/CollectionPage.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
https://trello.com/c/Efntu2bG/1276-ressurssamlingssidene-med-stor-forbokstav-p%C3%A5-spr%C3%A5k
=> Lower case language at collection page

src/containers/MyNdla/Learningpath/components/FolderResourcePicker.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
Fikser punkt 2 i https://github.com/ndlano/issues/issues/4292
=> fix: show text indication when a user hasn't added any resources to their folders

src/containers/MyNdla/Learningpath/EditLearningpathStepsPage.tsx, src/containers/MyNdla/Learningpath/learningpathFragments.ts, src/containers/MyNdla/Learningpath/learningpathMutations.ts, src/containers/MyNdla/Learningpath/learningpathQueries.ts, src/graphqlTypes.ts
Fikser slik at henting av stier ikkje feiler dersom en sti har steg med feil.
=> Only fetch steps when editing them

src/containers/MyNdla/Learningpath/EditLearningpathStepsPage.tsx, src/containers/MyNdla/Learningpath/EditLearningpathStepsPageContent.tsx, src/containers/MyNdla/Learningpath/components/LearningpathStepForm.tsx, src/containers/MyNdla/Learningpath/components/LearningpathStepListItem.tsx, src/containers/MyNdla/Learningpath/learningpathFormUtils.ts, src/containers/MyNdla/Learningpath/utils.ts
Hvis vi skal lazy-loade slate må vi nesten lazy-loade hele EditLearningpathStepsPage
=> fix: lazy load entirety of learning path edit page

src/containers/ArticlePage/ArticlePage.tsx, src/containers/TopicPage/MultidisciplinarySubjectArticle.tsx
En fortsettelse av: https://github.com/NDLANO/ndla-frontend/pull/2358
Var visst flere tilfeller med overflow: https://ndla-frontend-master.vercel.app/r/driftsstotte-im-itk-vg2/ipv6/cbe4475f45
=> Introduce overflowX: 'clip' to prevent page overflow

src/containers/MyNdla/Learningpath/EditLearningpathStepsPageContent.tsx, src/containers/MyNdla/Learningpath/components/LearningpathStepListItem.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
Sikkert dårlige tekster så slakt meg gjerne 🥉
=> Add toast when creating and deleting steps

src/components/Learningpath/components/CopyLearningPath.tsx
Contributor settes ved opprettelse, men ikkje ved kopi. Kan sikkert også gjøres serverside, men dette fikser på klienten. Kan garantert gjøres bedre.
=> Add user to contributor list

src/containers/TopicPage/TopicContainer.tsx
Kan sjekkes på http://localhost:3000/e/yrkesfaglig-fordypning-sr-srl-vg2/yrker-innen-salg-og-reiseliv/20e9db3274
Fixes https://github.com/NDLANO/Issues/issues/4308
=> Display grep-codes for topics.

src/containers/MyNdla/Folders/components/ResourceList.tsx, src/queries.ts, src/server/podcastRssFeed.ts, src/server/render/defaultRender.tsx, src/server/routes/oembedArticleRoute.ts, src/util/DebugInMemoryCache.ts, src/util/apiHelpers.ts, src/util/error/NDLAApolloErrors.ts, vite.config.ts
Ser ut som at dette har et utslag på hvor mye plass apollo tar i bundle.
=> refactor: reduce apollo bundle size

src/containers/MyNdla/Learningpath/SaveLearningpathPage.tsx, src/containers/MyNdla/Learningpath/components/LearningpathActionHooks.tsx, src/containers/MyNdla/Learningpath/components/LearningpathShareDialogContent.tsx, src/containers/MyNdla/Learningpath/components/LearningpathShareLink.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts
=> Implement new design for learningpath save page when shared

src/components/Article/articleHelpers.ts, src/containers/ErrorPage/ErrorPage.tsx, src/containers/ErrorPage/__tests__/__snapshots__/ErrorPage-test.tsx.snap, src/containers/Masthead/MastheadContainer.tsx, src/containers/Masthead/components/Masthead.tsx, src/containers/Page/Layout.tsx, src/util/useIsMastheadSticky.ts
Fixes https://github.com/NDLANO/Issues/issues/4310
Overraskende tricky oppgave! Selve det med å sette/unsette sticky fikk vi jo gratis, men vi må også reagere på det for å justere scrolling.
=> feat: do not set sticky on screens zoomed in more than 150%

src/components/Learningpath/LearningpathMenu.tsx
Fikser https://trello.com/c/BSQzeTDs/1300-endre-datoformatet-i-sist-oppdatert-p%C3%A5-eksterne-l%C3%A6ringsstier
=> Use formatDate for learningpath

src/containers/MyNdla/Learningpath/components/LearningpathActionHooks.tsx, src/containers/MyNdla/Learningpath/components/LearningpathShareLink.tsx, src/containers/MyNdla/Learningpath/utils.ts
Om du har valgt nn i språkvelger og deler stien din bør lenka gjenspeile det.
=> Use selected language in learningpath link

src/containers/MyNdla/Learningpath/components/ResourceStepForm.tsx
fixes https://github.com/NDLANO/Issues/issues/4314
=> ResourceStepForm: Fix that form is not dirty when resource is added and deleted

src/containers/MyNdla/Learningpath/EditLearningpathStepsPageContent.tsx
fixes https://github.com/NDLANO/Issues/issues/4309
=> Scroll to content when new learningpath step is added

src/containers/MyNdla/components/NavigationLink.tsx
Den andre stylingen holdt visst ikke :(
=> Actually resize external link icon

src/containers/AboutPage/AboutPage.tsx, src/containers/PlainArticlePage/PlainArticlePage.tsx, src/containers/ResourcePage/ResourcePage.tsx
Fixes https://github.com/ndlano/issues/issues/4254
En litt mindre magisk løsning på mathjax-problematikken. Ser i det minste ut til å fikse eksemplet i issuet. Dere får velge hvilken løsning dere liker best.
=> fix: ensure mathjax re-renders articles when navigating back and forth

src/iframe/__tests__/IframeArticlePage-test.tsx
=> fix: mock alerts response in test

src/components/NavigationBox.tsx
Så slipper vi denne warningen!
=> Add fallback key value to list elements in NavigationBox

src/containers/MyNdla/Learningpath/components/LearningpathStepForm.tsx, src/containers/MyNdla/Learningpath/components/TextStepForm.tsx
fixes https://github.com/NDLANO/Issues/issues/4325
=> Use correct initialValue for RichTextEditor

src/components/Learningpath/LastLearningpathStepInfo.tsx, src/components/Learningpath/components/LearningpathStep.tsx
=> Show learningpath last step info regardless of embed type

src/util/sentry.ts
Vi har egentlig skrudd på filtrering av extension-feil i sentry, men det ser ut til at vi fortsatt får en del. Se f.eks https://ndlano.sentry.io/issues/35103805/?project=4508018776735824&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D%20failed%20to%20fetch&referrer=issue-stream&sort=freq&stream_index=2
=> fix: add additional layer of extension error filtering

Dockerfile, build.sh, src/config.ts, src/util/sentry.ts, vite.config.ts
This should hopefully make it more easy to identify versions causing trouble on sentry.
https://docs.sentry.io/platforms/javascript/configuration/releases/
=> feat(sentry): Add release name to sentry at build & runtime

src/containers/Masthead/MastheadContainer.tsx, src/containers/Masthead/components/MastheadSearch.tsx, src/graphqlTypes.ts, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts, src/queries.ts
fixes https://github.com/NDLANO/Issues/issues/4338
=> New masthead search

src/mutations/learningpathMutations.ts
Oppdaget at hvis man bytter rekkefølge på steg, også prøver å oppdatere steget så gir det feilmelding, denne fikser!
=> Update revision in cache after dnd to be able to update resources after

src/components/RichTextEditor/plugins/link/LinkDialogContent.tsx, src/components/RichTextEditor/plugins/link/LinkElement.tsx
depends on https://github.com/NDLANO/backend/pull/639
https://trello.com/c/25XGYuKa/1323-%C3%A5pne-lenke-i-tekst-jeg-har-skrevet-selv-i-ny-fane
=> Open links in new tab

src/containers/MyNdla/Learningpath/components/TextStepForm.tsx
=> Make introduction of text learningstep not required

src/containers/SearchPage/GrepFilter.tsx
Siden grep-koder finnes på både emne og fag gir det meinig å vise boksen for alle søketypene
=> Always show grep-filter if present

src/LtiContext.tsx, src/client.tsx, src/components/AlertsContext.tsx, src/components/AuthenticationContext.tsx, src/components/BaseNameContext.tsx, src/components/LtiContext.tsx, src/components/SiteThemeContext.tsx, src/components/ToastContext.tsx, src/components/VersionHashContext.tsx, src/components/__tests__/RedirectExternal-test.tsx, src/containers/ErrorPage/ErrorEntry.tsx, src/containers/ErrorPage/ErrorPage.tsx, src/containers/Masthead/drawer/DrawerContext.tsx, src/iframe/embedIframeIndex.tsx, src/iframe/index.tsx, src/server/render/defaultRender.tsx, src/server/render/errorRender.tsx, src/server/render/iframeArticleRender.tsx, src/server/render/iframeEmbedRender.tsx
Kommer til å bli deprecated etterhvert!
https://react.dev/blog/2024/12/05/react-19#context-as-a-provider
=> Context as provider

src/containers/Masthead/components/MastheadSearch.tsx, src/containers/MyNdla/Learningpath/components/FolderStepForm.tsx, src/containers/MyNdla/Learningpath/components/ResourceStepForm.tsx, src/containers/MyNdla/Learningpath/components/StepSafeLink.tsx
Gjør det mulig å sjekke at artikkelen du har søkt opp til stien din faktisk er den du leita etter.
=> Add link to preview in step

src/App.tsx, src/containers/FilmRedirect/FilmRedirectPage.tsx
Kan teste ved å gå til film v.h.a lenken nederst på forsiden.
=> fix: ensure /film redirects during client-side navigation

src/components/Article/FavoritesButton.tsx, src/components/ContentPlaceholder.tsx, src/components/ContentTypeFallbackIcon.tsx, src/components/DialogCloseButton.tsx, src/components/Layout/PageContainer.tsx, src/components/MyNdla/FavoriteButton.tsx, src/components/MyNdla/NewFolder.tsx, src/components/NavigationSafeLinkButton.tsx, src/components/PageSpinner.tsx, src/containers/FilmFrontpage/Carousel.tsx, src/containers/MyNdla/components/SettingsMenu.tsx
Kommer til å bli deprecated etterhvert!
https://react.dev/blog/2024/12/05/react-19#ref-as-a-prop
=> No more forwardref

src/containers/ResourceEmbed/components/ResourceEmbed.tsx, src/containers/ResourceEmbed/components/ResourceEmbedLicenseContent.tsx, src/graphqlTypes.ts
Metabilde er sletta fra forklaringer.
=> Stop fetching missing metaimate

package.json, yarn.lock
Overrasket hvis dette har noe å si
=> chore: bump express to 5.1

src/containers/MyNdla/Learningpath/components/ResourcePicker.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts
Fixes https://trello.com/c/0HoX09ZS/1347-fjerne-s%C3%B8k-heller-etter-i-l%C3%A6ringssti-sett-inn-innhold-fra-ndla
=> chore: remove search suggestion from ResourcePicker

.github/workflows/ci.yml, Dockerfile, README.md, package.json, yarn.lock
Krysser fingrene for at jeg valgte riktig docker-image.
=> chore: upgrade to node 22

src/containers/MyNdla/Learningpath/components/ExternalStepForm.tsx
Fixes https://trello.com/c/SlNFOjGy/1360-lik-oppf%C3%B8rsel-p%C3%A5-lenkene-i-steg-for-l%C3%A6ringssti-p%C3%A5-min-ndla
=> fix: open copyright link in new tab

src/containers/SearchPage/SearchContainer.tsx
Fixes https://trello.com/c/9JKm3SOd/1365-s%C3%B8k-hermeteikn-m%C3%A5-behandlast
Fixes https://github.com/NDLANO/Issues/issues/4364
=> fix: decode query before sending to graphql

src/containers/Masthead/MastheadMenu.tsx, src/containers/Masthead/MastheadSearchV2.tsx, src/graphqlTypes.ts, src/schema.graphql
Dette pleide å være to separate queries, men tror vi kan slippe unna med en query!
=> fix: fetch and display subject when using masthead search in a context

src/components/LanguageSelector/LanguageSelector.tsx
Fikser siste kommentar her: https://trello.com/c/elzfbRtQ/1345-ny-meny
=> fix: flip language selector icon positioning

src/containers/MyNdla/Folders/components/DraggableResource.tsx
=> Disable resource link in folder if meta is missing

src/messages/messagesNB.ts, src/messages/messagesSE.ts
Verktøykassen i masthead skal vere Verktøykassa.
=> Typo: verktøykassa

src/components/RichTextEditor/RichTextEditor.tsx, src/components/RichTextEditor/Toolbar/RichTextToolbar.tsx, src/components/RichTextEditor/plugins/heading/HeadingToolbarSelect.tsx, src/components/RichTextEditor/plugins/heading/headingPlugin.ts, src/components/RichTextEditor/plugins/heading/headingTypes.ts, src/components/RichTextEditor/plugins/heading/headingUtils.ts, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
fixes https://github.com/NDLANO/Issues/issues/4350
=> Integrate heading plugin in learningstep editor

src/containers/ResourceEmbed/components/ResourceEmbed.tsx
Fixes https://trello.com/c/peiNWrub/1393-videoar-i-artiklar-til-google-sitt-videos%C3%B8k
=> feat: allow search engines to index video embeds

src/components/RichTextEditor/plugins/heading/HeadingElement.tsx
https://trello.com/c/MxyEKy2C/1410-l%C3%A6ringssti-h2-og-h3-m%C3%A5-ha-ulik-storleik-i-editor
Viser forskjellig størrelse på headers i læringssteg
=> Differ heading size in step

.github/workflows/ci.yml
ved nærmere ettertanke så trenger vi vel ikke å logge inn i docker her?
=> remove docker logins on ci

src/config.ts, src/index.ts, src/server/api.ts, src/server/helpers/gracefulShutdown.ts, src/server/middleware/activeRequestsMiddleware.ts, src/server/routes/healthRouter.ts, src/server/server.ts
ganske lik på [denne](https://github.com/NDLANO/graphql-api/pull/613)
=> feat: implement graceful shutdowns

src/components/Article/articleHelpers.ts, src/containers/AllSubjectsPage/AllSubjectsPage.tsx, src/containers/AllSubjectsPage/SubjectCategory.tsx
Fixes https://github.com/NDLANO/Issues/issues/4408
Denne irriterer meg litt. Vi fikser strengt tatt ikke problemet, vi bare lapper over. Såvidt jeg vet er det noe med hydrering av siden som fører til dette. Hvis man ikke hydrerer i det hele tatt funker dette helt fint.
=> fix: scroll to subject group heading

src/Document.tsx, src/components/SocialMediaMetadata.tsx, src/iframe/test-iframe.html
https://github.com/NDLANO/Issues/issues/4430
=> Remove old metatags

src/Document.tsx
https://trello.com/c/1Kdk9S1r/1457-rydde-metadata-i-head
=> feat: preload and preconnect to Fontshare

src/components/Scripts/Formbricks.tsx
=> fix: MIME mismatch for formbricks script

src/Document.tsx, src/components/Article/Article.tsx, src/containers/ArticlePage/ArticlePage.tsx, src/containers/Resources/ResourceItem.tsx, src/containers/TopicPage/MultidisciplinarySubjectArticle.tsx, src/iframe/__tests__/__snapshots__/IframeArticlePage-test.tsx.snap, src/util/transformArticle.ts
Siste del av https://github.com/NDLANO/Issues/issues/4430
=> Use lang from article

src/config.ts, src/containers/WelcomePage/WelcomePage.tsx, src/messages/messagesEN.ts, src/messages/messagesNB.ts, src/messages/messagesNN.ts, src/messages/messagesSE.ts
Fixes https://trello.com/c/uDdKHMdb/1463-oppdatering-tjenester-forside
Veldig gjerne gå over oversettelser.
=> feat: welcome page quick links

src/containers/AboutPage/AboutPage.tsx, src/containers/AboutPageV2/AboutPageV2.tsx, src/containers/CollectionPage/CollectionPage.tsx, src/containers/PlainArticlePage/PlainArticlePage.tsx, src/containers/PlainLearningpathPage/PlainLearningpathPage.tsx, src/containers/PodcastPage/PodcastSeriesPage.tsx, src/containers/ProgrammePage/ProgrammePage.tsx, src/routeHelpers.tsx
=> chore: drop typed params

src/containers/Page/components/Footer.tsx, src/i18n.ts, src/lti/LtiProvider.tsx
Ser ut som at vi fint kan gå over til nn/nb her også.
=> fix: prefer nn and nb over no everywhere

src/config.ts, src/containers/Resources/resourceHelpers.ts, src/server/routes/__tests__/forwardingRoute-test.ts
=> Remove redirect to learningpath-frontend
